### ISSUE TITLE
Add installation documentation

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#1]
https://github.com/Puzzlepart/prosjektportalen/wiki/Installation

**Comment by olemp** [comment]
- How to run Install.ps1
- How to do the manual setup needed

**Comment by olemp** [comment]
I've started some work on this @tarjeieo 

https://github.com/Puzzlepart/prosjektportalen/wiki/Installation

**Comment by olemp** [comment]
Can you do a QA, @tarjeieo?

**Comment by tarjeieo** [comment]
Done. Looks very good with the wiki syntax!
