### ISSUE TITLE
Debug-version of bundle does not seem to work in Internet Explorer

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#101]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment
[X ] SharePoint Online
[ ] SharePoint 2013

#### Summary

Getting an issue with "Syntax error" on the line where sp-pnp-js is included when the bundle is compiled using default gulp task. If I use "gulp release" and install, I do not get the error.

Not a critical issue, but I've spent a lot of time thinking it was another issue with the pdf export 😞 . If we can fix it, we should.

**Comment by tarjeieo** [comment]
Not sure if this is related to sp-pnp-js though, might be a coincidence. Can't find any relevant issues at https://github.com/SharePoint/PnP-JS-Core/issues anyway...

**Comment by olemp** [comment]
By design. Debug version doesn't compile/transpile modules in node_modules, so just a `const` or `let` will make it break in IE.
