### ISSUE TITLE
Add a risk status field to the usikkerhet content type

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#102]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ X] Enhancement

[ ] Bug

[ ] Question

Add a new field to the usikkerhet content type:
Status usikkerhet - choice field.
Choices: «Identifisert», «Tiltak gjennomført», «Ikke lenger aktuell»
Default choice: "Identifisert".
Internt navn: GtRiskStatus

Endre "Prosjektrapport" visningen i risikolisten til å ikke ta med elementer som har "Tiltak gjennomført" eller "Ikke lenger aktuell".

**Comment by olemp** [comment]
@tarjeieo Det er vel `Prosjektstatus`, ikke `Prosjektrapport`?

**Comment by olemp** [comment]
Set view query of Prosjektstatus view to:

```
<Where>
    <And>
        <Neq>
            <FieldRef Name="GtRiskStatus" />
            <Value Type="Text">Tiltak gjennomført</Value>
        </Neq>
        <Neq>
            <FieldRef Name="GtRiskStatus" />
            <Value Type="Text">Ikke lenger aktuell</Value>
        </Neq>
    </And>
</Where>
```
