### ISSUE TITLE
Support to also reference xml from web parts in the web part gallery in the extensions override config json

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#111]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ X] Enhancement

[ ] Bug

[ ] Question

#### Environment
[ ] SharePoint Online
[ ] SharePoint 2013

#### Summary

Please summarize the issue.

#### Version

Please specify what version ou are using: [ ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
https://github.com/SharePoint/pnp-js-provisioning/issues/17

**Comment by olemp** [comment]
Issues a pull request https://github.com/SharePoint/pnp-js-provisioning/pull/18

**Comment by olemp** [comment]
Temporarily reffing sp-pnp-provisioning from git+https://github.com/Puzzlepart/pnp-js-provisioning.git#dev until PR is merged.

**Comment by olemp** [comment]
Also added issue https://github.com/SharePoint/pnp-js-provisioning/issues/19

**Comment by olemp** [comment]
We can now do:

```javascript
  {
            Title: "Gevinstanalyse og gevinstrealiseringsplan",
            Zone: "LeftColumn",
            Order: 3,
            PropertyOverrides: [{
                name: "Title",
                type: "string",
                value: "Gevinstanalyse og gevinstrealiseringsplan",
            },
            {
                name: "ListUrl",
                type: "string",
                value: "{site}/Lists/Gevinstanalyse og gevinstrealiseringsplan",
            },
            {
                name: "TitleUrl",
                type: "string",
                value: "{site}/Lists/Gevinstanalyse og gevinstrealiseringsplan/AllItems.asp",
            }],
            Contents: {
                FileSrc: "{sitecollection}/Resources/ListViewWebPart.txt",
            },
            ListView: {
                List: "Gevinstanalyse og gevinstrealiseringsplan",
                View: {
                    Title: "",
                    ViewFields: ["LinkTitle", "GtChangeLookup", "GtGainsType", "GtRealizationTime"],
                    AdditionalSettings: {
                        RowLimit: 10,
                        Paged: true,
                        ViewQuery: "<OrderBy><FieldRef Name='Created' Ascending='FALSE' /></OrderBy>",
                    },
                },
            },
        }
```

**Comment by olemp** [comment]
PR merged https://github.com/SharePoint/pnp-js-provisioning/issues/19, waiting for npm update
