### ISSUE TITLE
Failed to install v1.12.0

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#112]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Environment
[x] SharePoint Online
[ ] SharePoint 2013

#### Summary

When running Install.ps1, the following error occures:

```
Add-Type : Could not load file or assembly 'file:///C:\Users\Ole Martin\Downloads\prosjektportalen-1.12.0.ff1734d3\bund
le\SharePointPnPPowerShellOnline\Microsoft.SharePoint.Client.Taxonomy.dll' or one of its dependencies. Operation is
not supported. (Exception from HRESULT: 0x80131515)
At C:\Users\Ole Martin\Downloads\prosjektportalen-1.12.0.ff1734d3\Install.ps1:52 char:5
+     Add-Type -Path "$BundlePath\Microsoft.SharePoint.Client.Taxonomy. ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand
```

#### Version

Please specify what version ou are using: [1.12.0]

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen/releases/tag/v1.12.0

**Comment by tarjeieo** [comment]
Cannot reproduce, installs fine at my end... Hmmm...

**Comment by olemp** [comment]
I'm going to try once more after my "local install" is done.

**Comment by olemp** [comment]
Tried again.

1. Downloaded `prosjektportalen-1.12.0.ff1734d3.zip` from https://github.com/Puzzlepart/prosjektportalen/releases/tag/v1.12.0
2. Unpacked it
3. Attempted to run Install.ps1
4. Got security warning `Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning message.`
5. Tried to run `Unblock-File` on all files (Install.ps1 and bundle files)
6. Still same eror message

````
Add-Type : Could not load file or assembly 'file:///C:\Users\Ole Martin\Downloads\prosjektportalen-1.12.0.ff1734d3\bund
le\SharePointPnPPowerShellOnline\Microsoft.SharePoint.Client.Taxonomy.dll' or one of its dependencies. Operation is
not supported. (Exception from HRESULT: 0x80131515)
At C:\Users\Ole Martin\Downloads\prosjektportalen-1.12.0.ff1734d3\Install.ps1:52 char:5
+     Add-Type -Path "$BundlePath\Microsoft.SharePoint.Client.Taxonomy. ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand
```

**Comment by olemp** [comment]
It works when unzipping using 7zip, but that can't be a prereq.

**Comment by tarjeieo** [comment]
Relevant: https://superuser.com/questions/38476/this-file-came-from-another-computer-how-can-i-unblock-all-the-files-in-a

**Comment by olemp** [comment]
Works. If I unblock the zip before unzipping, it works like a charm. Add to installation wiki page?
