### ISSUE TITLE
Taking a snapshot in IE11 or before results in a weirdly looking snapshot image

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#113]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment
[X ] SharePoint Online
[X ] SharePoint 2013

#### Summary

When snapshotting with IE 11, it doesn't look like the office ui fabric styling is being applied to the details lists. The list columns are listed vertically.

#### Version

Please specify what version you are using: [1.12.0]

**Comment by tarjeieo** [comment]
Finding: IE defaults uses IE10 user agent string, even in IE11. If I change user agent string to IE11 in the browser emulation, the export works perfectly! Need to investigate what we can do here...

**Comment by olemp** [comment]
cc @damsleth

**Comment by olemp** [comment]
@damsleth Could you assist us here?

**Comment by olemp** [comment]
Example:

![113-01](https://user-images.githubusercontent.com/7606007/29462847-ff11fa56-8430-11e7-8c77-8764617e791a.PNG)

**Comment by olemp** [comment]
```
Finding: IE defaults uses IE10 user agent string, even in IE11. If I change user agent string to IE11 in the browser emulation, the export works perfectly! Need to investigate what we can do here...
```

You mean `Document mode`, right @tarjeieo?

**Comment by olemp** [comment]
I've found the error. It's in `@microsoft\load-themed-styles`.

The error is in `registerStylesIE` which kicks in from IE 10 and below due to function `shouldUseCssText`.

**Comment by olemp** [comment]
Reported to https://github.com/Microsoft/web-build-tools

https://github.com/Microsoft/web-build-tools/issues/359

**Comment by olemp** [comment]
Nothing we can do at the moment. There's no hack no make it work for IE 10 document mode.
