### ISSUE TITLE
Status gevinstoppnåelse bør ikke være mandatory ved førstegangs registrering av egenskaper

### ISSUE THREAD

**Issue by pettersh** [Puzzlepart/prosjektportalen#114]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Environment
[x] SharePoint Online
[x] SharePoint 2013

#### Summary

Når prosjektet nylig er opprettet og egenskaper settes, er det unaturlig å måtte sette status gevinstoppnåelse til lav, medium eller høy. Enten bør det finnes et fjerde alternativ eller så burde ikke feltet være påkrevet.

**Comment by olemp** [comment]
Hi @pettersh,

This was solved in https://github.com/Puzzlepart/prosjektportalen/commit/5f3182876e132d6b89cb7a26e71f189058df3973 and should be included in the latest release.

**Comment by olemp** [comment]
You can download 1.12.0 from here https://github.com/Puzzlepart/prosjektportalen/releases/tag/v1.12.0

**Comment by olemp** [comment]
Did you test `v1.11.3` @pettersh? You can find the installed version in the bottom left corner.

**Comment by pettersh** [comment]
Yes @olemp https://pzlcloud.sharepoint.com/sites/ppdemo_v2/ shows v1.11.3

**Comment by olemp** [comment]
We will upgrade https://pzlcloud.sharepoint.com/sites/ppdemo_v2/ tomorrow J
