### ISSUE TITLE
New project errors in console

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen#116]
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment
[X] SharePoint Online
[ ] SharePoint 2013

#### Summary
Created a new project site called 
`Oppretter prosjektområde for Moscow mule er det bestenavnet på en området. D¨JEg elsker å skrive lange tittler, det gir meg behagog mye velstand`

Chose to have advanced features enabled. Did not change anything else

The project site appears to complete successfully, but my console is a red carpet of errors

![image](https://user-images.githubusercontent.com/170147/27081160-6e487b28-503f-11e7-8c87-5965f526a9cb.png)

**Comment by olemp** [comment]
`processList` in the list handler of `pnp-js-provisioning` uses `web.lists.ensure` from `sp-pnp-js` which does a get call to check if the list exist before eventually creating it.
