### ISSUE TITLE
Truncate suggested url for new project sites

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen#117]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Environment
[x] SharePoint Online
[ ] SharePoint 2013

#### Summary
Creating a new project site, the suggested url is not truncated. This may cause issues, especially on sp2013. Consider truncating the project url.

example 
https://pzlcloud.sharepoint.com/sites/ppdemo_v2/moscow-mule-er-det-bestenavnet-paa-en-omraadet.-d%C2%A8jeg-elsker-aa-skrive-lange-tittler,-det-gir-meg-behagog-mye-velstand/SitePages/ProjectHome.aspx

**Comment by olemp** [comment]
@okms You mean introducing a max url length?

**Comment by olemp** [comment]
Or use the builtin SP truncate function perhaps...

**Comment by okms** [comment]
Either, the main point is to consider disallowing arbitrary length for new project urls. I am aware this is an edge case

**Comment by olemp** [comment]
We might be able to use `Srch.U.truncateUrl` or  `Srch.U.truncat` @okms  @tarjeieo

**Comment by okms** [comment]
@olemp @tarjeieo please review commit and close if ok

**Comment by olemp** [comment]
I guess hyphens should be allowed aswell since we're replacing spaces.

**Comment by okms** [comment]
Agreed. Will update

**Comment by olemp** [comment]
Push it to the dev branch.

**Comment by tarjeieo** [comment]
Assume fixed in commit https://github.com/Puzzlepart/prosjektportalen/commit/699b0a8fb771a09f89dd2280996d860289867392

Thx Prime!

**Comment by tarjeieo** [comment]
Reopen til hyphens blir inkludert igjen

**Comment by okms** [comment]
commit 5d39841 should fix the issue that hyphens were replaced with empty string. closing
