### ISSUE TITLE
Using special characteres in project title yields an illigal URL 

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen#118]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Environment
[ ] SharePoint Online
[x] SharePoint 2013

#### Summary

In order to support various browser/platform scenarios we should not suggest URLs with special characters in them. I suggest keeping only the following chars

a-z, 0-9

transcoding 
æ=>ae
ø=>o
å=>a

Its especially important that characters like '?' and '&' is dropped or URL encoded

![image](https://user-images.githubusercontent.com/170147/27081610-82f126c2-5041-11e7-9fe8-4ab56c32b2a4.png)

**Comment by olemp** [comment]
Nice find. Would love if you if you push a fix for this regex-master.

The function that's being used is `generateUrl` at the following location `src\js\Util\index.ts`.

**Comment by tarjeieo** [comment]
Assume fixed in https://github.com/Puzzlepart/prosjektportalen/commit/699b0a8fb771a09f89dd2280996d860289867392. Thx Prime!
