### ISSUE TITLE
Project creation failure due to illigal URL gives no feedback

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen#119]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Environment
[x] SharePoint Online
[ ] SharePoint 2013

#### Summary

1. Try to create a project with some special characters in the url
2. Upon clicking "opprett prosjekt" the ui will flash and the title/description fields are reset. The url field is not
3. If you enter a new title (e.g. foobar) you will get a new project with the url "/foobar" even though the url field contains the old value

#### expected behaviour
alternative1: Keep the title/description field and reset the URL field. 
alternative2: reset all fields

also it would be nice with some feedback on what happened

![image](https://user-images.githubusercontent.com/170147/27081778-3efb54b4-5042-11e7-8c17-ad99a4393ba7.png)

**Comment by tarjeieo** [comment]
Shouldn't be an issue after commit https://github.com/Puzzlepart/prosjektportalen/commit/699b0a8fb771a09f89dd2280996d860289867392 IIRC. Good find Prime!
