### ISSUE TITLE
Support for snapshot generation on Project Status page

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#12]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Enhancement

[ ] Bug

[ ] Question

**Comment by olemp** [comment]
Probably not realistic for 1.0.0 @tarjeieo

**Comment by tarjeieo** [comment]
Oslo wants it bad for 1.0... Let's see what we can do

**Comment by olemp** [comment]
Having some issues with `jspdf is not defined` using SP.SOD to load `jspdf.min.js`.

**Comment by tarjeieo** [comment]
How far away are we with this? Is it just the question of loading the jspdf script in a working way?

**Comment by olemp** [comment]
Renamed to `Support for snapshot generation on Project Status page`.

Status here @tarjeieo?

**Comment by tarjeieo** [comment]
With that rename we are pretty much done. Will add an issue about IE snapshot styling.
