### ISSUE TITLE
Phase change form doesn't care about existing status of the check list items. 

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#123]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Summary
 
If you have filled out many of the phase check list items in a phase, and then try to change phase, the phase check list item's previous values are ignored. if the user continue, previous values are overwritten.

**Comment by olemp** [comment]
Will skip open checklist items.

**Comment by olemp** [comment]
Link to phase checklist all items view added to `SummaryView` of the dialog. Need to add a resource entry for the link markup (https://github.com/Puzzlepart/prosjektportalen/issues/128).

![123-01](https://user-images.githubusercontent.com/7606007/27132842-95ad16fc-5110-11e7-9d44-9a92a62b5128.PNG)
