### ISSUE TITLE
Support for exporting dynamic portfolio results to CSV/Excel

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#13]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[x] Enhancement

[ ] Bug

[ ] Question

**Comment by olemp** [comment]
Packages to look into:

- `react-excel-workbook` (https://www.npmjs.com/package/react-excel-workbook)
- `excel-export` (https://www.npmjs.com/package/excel-export)

**Comment by olemp** [comment]
We need to decide 

- fileName
- sheetName
- buttonLabel

It can be set as props for the `DownloadWorkbookButton` component.

```
<DownloadWorkbookButton fileName="Example.xlsx" sheetName="Sheet 1" buttonLabel="Eksporter til Excel" buttonIconName="ExcelLogo" data={items} columns={selectedColumns}  />

**Comment by tarjeieo** [comment]
fileName: <selected scope><dato og klokkeslett>.xlsx.
sheetname: <selected scope>

E.g. "Porteføljeoversikt2017-04-28-14-46.xlsx

**Comment by olemp** [comment]
https://github.com/SheetJS/js-xlsx/issues/285

**Comment by olemp** [comment]
Pushed to dev branch, but not ready for master branch yet.

**Comment by olemp** [comment]
Removed due to https://github.com/Puzzlepart/prosjektportalen/issues/93

**Comment by olemp** [comment]
Forked `react-excel-workbook` into https://github.com/Puzzlepart/react-excel-workbook and updated version of xlsx to ^0.10.3. Looks like this solved the webpack issues.

**Comment by olemp** [comment]
https://github.com/ClearC2/react-excel-workbook/pull/2
