### ISSUE TITLE
GNU GPL not distributed with the software

### ISSUE THREAD

**Issue by pettersh** [Puzzlepart/prosjektportalen#137]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

According to the last section of https://github.com/Puzzlepart/prosjektportalen/blob/master/license.md, the https://www.gnu.org/licenses/gpl.txt must be distributed with the software.

Contents of https://github.com/Puzzlepart/prosjektportalen/blob/master/license.md should also be updated to reflect the GPL v3. Please see section "How to Apply These Terms to Your New Programs" in https://www.gnu.org/licenses/gpl.txt

Here's a suggested update:
`
    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>`

#### Version

Please specify what version you are using: [ ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by tarjeieo** [comment]
Thanks for the input. Alas we should include license.md in the released zip-file. Updating text now.
