### ISSUE TITLE
Filtering on project manager and project owner in dynamic portfolio does not work

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#14]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version ou are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
I guess the config for portfolio and fields are not matching @tarjeieo.

**Comment by olemp** [comment]
I updated the configuration for the fields to match the refiner configuration.

- RefinableString52 - Fase
- RefinableString51 - Prosjektleder
- RefinableString50 - Prosjekteier
