### ISSUE TITLE
Need to review the benefits calculation - perhaps ask the experts

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#141]
I think we should change to calculate the gains based on the diff between the start and target numbers instead. I might ask some customers I know are good with this.

Some scenarios
- Start: 60000, End: 50000, Logged: 59000. Expected: 10%. Actual: 84%
- Start: 100, End: 0, Logged 10: 10. Expected: 90%, Actual: 100% (zero-division issue)

**Comment by tarjeieo** [comment]
Should've though of this earlier... Looks to be the correct formula. We need to take into consideration the startvalue. https://math.stackexchange.com/questions/51509/how-to-calculate-percentage-of-value-inside-arbitrary-range

Fix incoming...

**Comment by tarjeieo** [comment]
Enige i at dette er riktig @olemp og @ElsaNau? 
![image](https://user-images.githubusercontent.com/1837390/28679734-6be98b7e-72f4-11e7-807d-fd9b5a39238d.png)

**Comment by ElsaNau** [comment]
Bør ikke rad to ha grønn pil? Nedgangen er positiv i den forstand at den er ønsket - selv om ikke mål er nådd?

**Comment by tarjeieo** [comment]
Enig - var en bug på rad to over.

Oppdatert nå - denne tror jeg blir riktig!
![image](https://user-images.githubusercontent.com/1837390/28680177-dd9b026a-72f5-11e7-8855-252890ed7e36.png)
