### ISSUE TITLE
Update developer documentation: gulp must be installed globally before it can be used

### ISSUE THREAD

**Issue by pettersh** [Puzzlepart/prosjektportalen#147]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

You cannot run 'gulp' before it's globally installed.

Add instructions on how to install gulp globally:
`npm install gulp -g`

See https://github.com/Puzzlepart/prosjektportalen/wiki/Development

#### Version

Please specify what version you are using: [ ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
Did this solve https://github.com/Puzzlepart/prosjektportalen/issues/120?

**Comment by olemp** [comment]
Did this solve #120 @pettersh?

**Comment by olemp** [comment]
I think this is only applicable when using `gulp` from PowerShell. Not when using it built-in; e.g. with `Visual Studio Code`.

**Comment by pettersh** [comment]
Well, I get the same in vscode integrated terminal, but than I'm using PowerShell there as well. I think PowerShell has been the default for the integrated terminal on windows for some months now

**Comment by olemp** [comment]
Updated https://github.com/Puzzlepart/prosjektportalen/wiki/Development
