### ISSUE TITLE
Bug with "benefitsFollowup" and "BenefitsOverview"

### ISSUE THREAD

**Issue by aleksKoss** [Puzzlepart/prosjektportalen#165]
#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Bug with "benefitsFollowup" and "BenefitsOverview"

#### Version

Please specify what version you are using: `1.15.0`

#### Expected / Desired Behavior / Question
If you create an element in "benefitsFollowup" where "MeasurementValue" is indentical with your previous measurment, "BenefitsOverview" won’t show anything at all. Not even other unrelated entries.

**Comment by olemp** [comment]
Thanks for report this, @aleksKoss.

Can you add a screenshot?

**Comment by aleksKoss** [comment]
![benefitsoverview bug](https://user-images.githubusercontent.com/23027943/27334260-01203da8-55c9-11e7-87f8-94d6ab14a033.jpg)

**Comment by olemp** [comment]
Solved in https://github.com/Puzzlepart/prosjektportalen/commit/ed03dec55808f66f08a05f4a6f2576c64db4e526
