### ISSUE TITLE
When you have a long "goal" or "overall status" text and show that  on the project front page, the text gets super wide in IE and breaks the page

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#169]

**Comment by olemp** [comment]
Can't reproduce. Could you provide a screenshot?

This is IE for me:

![169-01](https://user-images.githubusercontent.com/7606007/27373224-c98f2dd2-5667-11e7-884d-a35cf3ed8bf9.PNG)

Does not break the page.

**Comment by olemp** [comment]
In https://github.com/Puzzlepart/prosjektportalen/commit/1a27e149f610bb267154a684b94d441f23ecd337 I set max-width to 95% for ProjectProperty. See if that helps, @tarjeieo.

**Comment by tarjeieo** [comment]
This is a non-issue, after further investigation it looks like they tested on an earlier version (created before the office ui fabric breaking change with col names). Looks fine in IE for me as well.

![image](https://user-images.githubusercontent.com/1837390/27424238-a9f8ea12-5734-11e7-9884-ad42047b9dcb.png)

**Comment by olemp** [comment]
Good stuff.
