### ISSUE TITLE
Multiple Zones SharePoint 2016

### ISSUE THREAD

**Issue by pzlespen** [Puzzlepart/prosjektportalen#170]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ X] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[X ] SharePoint 2016

#### Summary

When using multiple zones on a web application. Some of the assets uses the full URL of the zone where PP is installed. In my case we have this zone for installation purposes only, and the other zone for users to use. This for SAML authentication purposes.

Assets that fail: 
<link rel="stylesheet" type="text/css" href="https://domain.tld/sites/sitecollection/siteassets/pp/css/pp.main.css?rev=1.13.4"/>

<link rel="canonical" href="https://domain.tld/sites/sitecollection/SitePages/Home.aspx" />

<script type="text/javascript">
//<![CDATA[
             SP.SOD.registerSod('pp.loader.js', 'https://domain.tld/sites/sitecollection/siteassets/pp/js/pp.loader.js?rev=1.13.4');             EnsureScriptFunc('pp.loader.js', 'PP.Loader', function() {                 PP.Loader.loadBundle('https://domain.tld/sites/sitecollection', '1.13.4');             });(function(){

#### Version

Please specify what version you are using: [1.13.4 ]

**Comment by olemp** [comment]
Any idea here @tarjeieo? I guess it doesn't help to use `AssetsSiteUrl` as it will attempt to install to that URL, not only use it for script references etc.

**Comment by tarjeieo** [comment]
We could test converting the abs url to a relative url when we send it in as parameter?

**Comment by olemp** [comment]
We could convert to relative URL in the custom action `pp.main.js` (templates\root\Objects\CustomActions.xml). I think that's where the problem occurs. And perhaps for the Alternate CSS in WebSettings?

**Comment by tarjeieo** [comment]
Yes, and for the SiteLogos...

We just need to take care that we can still support absolute urls in cases where we use a remote CDN.

**Comment by pettersh** [comment]
Make sure to support loading resources across site collections (ie /sites/cdn from /sites/pp)

**Comment by olemp** [comment]
Yeah, we want to support that and absolute URLs to CDN

**Comment by tarjeieo** [comment]
Solved by converting input params to relative urls if the urls point to the same webapp.
