### ISSUE TITLE
Should truncate overall status on Project Status page

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#171]
#### Category

[x] Enhancement

[ ] Bug

[ ] Question

#### Environment

[x SharePoint Online

[x] SharePoint 2013

[x] SharePoint 2016

#### Summary

Long status text makes the page very large.

![171-01](https://user-images.githubusercontent.com/7606007/27373150-75517a68-5667-11e7-94fb-646fa2e2f305.PNG)

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen/issues/196

**Comment by tarjeieo** [comment]
Will be solved by ProjectProperty: Add possibility to truncate string to a set length and add show more/show less #196.
