### ISSUE TITLE
Use Language param to pick localization

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#173]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[x] Enhancement

[ ] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Please summarize the issue.

#### Version

Please specify what version you are using: [ ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
Looks like a wontfix.

**Comment by tarjeieo** [comment]
We need to handle this in some way or another, worst case we need two different root.xml files. It's not working as is.

**Comment by olemp** [comment]
Two `root.xml` is not the worstcase. That's not possible. 

`Convert-PnPFolderToProvisioningTemplate` requires a folder with a template .xml file with the same name as the folder.

Worst case is a root folder for all languages we're going to support.

**Comment by olemp** [comment]
There is a way to just have several root xml files.

Let's say we have
* root-1044.xml
* root-1033.xml

in the folder `root`. Then we would have to create a copy of the root folder for each `root-*.xml` file residing in the `root` folder using `gulp`.

**Comment by olemp** [comment]
Could you report this in `PnP-Sites-Core` @tarjeieo https://github.com/SharePoint/PnP-Sites-Core/issues?

**Comment by olemp** [comment]
I attempted to use a parameter for `ResourceFile`

```xml
    <pnp:Localizations>
        <pnp:Localization LCID="1044" Name="Norwegian" ResourceFile="{parameter:Test1}" />
        <pnp:Localization LCID="1033" Name="English (US)" ResourceFile="{parameter:Test1}" />
    </pnp:Localizations>
```

but I got the following error

```powershell
Apply-PnPProvisioningTemplate : The given path's format is not supported.
```

**Comment by olemp** [comment]
Take a look at thttps://github.com/Puzzlepart/prosjektportalen/pull/204.
