### ISSUE TITLE
Scope configuration for dynamic portfolio

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#18]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Enhancement
[ ] Bug
[ ] Question

We don't need result sources anymore in the dynamic portfolio page. We need a way, however, to use a similar functionality. I suggest a portfolio configuration list (or add them as a different content type to the existing one) that defines Name, Query and Column to sort on as default. The two configurations that should be available as default are Portføljeoversikt and Porteføljeoppfølging. The queries should be the same as in the query configuration in today's result sources. They should both be sorted on Title.

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen/issues/20 is impeding this issue
