### ISSUE TITLE
Load assets from public CDN

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#188]
#### Category

[x] Enhancement

[ ] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[x] SharePoint 2013

[x] SharePoint 2016

#### Summary

Enable loading assets from public CDN (images, scripts and CSS).

#### Version

N/A

**Comment by olemp** [comment]
We could also look into https://rawgit.com/

**Comment by tarjeieo** [comment]
This is solvable, more of an internal discussion/offering. Closing this.

**Comment by olemp** [comment]
Agreed
