### ISSUE TITLE
Add opportunity matrix to project status report

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#19]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X ] Enhancement

[ ] Bug

[ ] Question

#### About
We should add a opportunity matrix and opprortunity list that is based on the opportunity content type in the "Usikerhet" list. Very similar to the risk matrix, but in this case the colors are flipped around.

**Comment by olemp** [comment]
Still need more details here @tarjeieo

**Comment by tarjeieo** [comment]
![image](https://user-images.githubusercontent.com/1837390/33374543-e7b906d4-d506-11e7-974c-860f4e2bfbe3.png)

Suggest to create another section in the project status, as well as a separate webpart for this. Will need  a separate matrix configuration file (same as for risk matrix).

**Comment by tarjeieo** [comment]
We don't need to create an upgrade action for this, but we should document how to add it as a new section in the project status list

**Comment by olemp** [comment]
Let's celebrate the 1 year anniversary of this issue on saturday @tarjeieo 🙌

**Comment by olemp** [comment]
Started some work here...

![image](https://user-images.githubusercontent.com/7606007/39189344-50897b1a-47d2-11e8-8b70-0ff17d2ddfed.png)

What labels do we want, @tarjeieo?

**Comment by tarjeieo** [comment]
Sannsynlighet: Samme som for risiko
Konsekvens: Ubetydelig, begrenset, moderat, vesentlig, stor

Hva tror du?

**Comment by olemp** [comment]
|OpportunityMatrix_Header_Insignificant|A|

**Comment by tarjeieo** [comment]
Yeah agreed. I've also asked GG for his input, but might take some time y'know. Go with this for now. :)

**Comment by olemp** [comment]
![image](https://user-images.githubusercontent.com/7606007/39192732-2834b79e-47da-11e8-9b5e-4c02a85e60a1.png)
