### ISSUE TITLE
Localization for list field GtProjectEventDateAndTitle

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#191]
#### Category

[x] Enhancement

[ ] Bug

[ ] Question

#### Summary

Localization for list field GtProjectEventDateAndTitle. A bit more advanced since its a `Calculcated` column.

**Comment by tarjeieo** [comment]
Looks like you've already solved this!? :)

`export const GtProjectEventDateAndTitle = `<Field ID="{7604dadc-d8e3-4f35-bc58-890d33d908b9}"  StaticName="GtProjectEventDateAndTitle" InternalName="GtProjectEventDateAndTitle" DisplayName="${__("SiteFields_GtProjectEventDateAndTitle_DisplayName")}" Type="Calculated" Required="FALSE" ResultType="Text" ReadOnly="TRUE" EnforceUniqueValues="FALSE" Indexed="FALSE" Percentage="FALSE"><Formula>=TEXT(${__("SiteFields_EventDate_DisplayName")},"yyyy-mm-dd")&amp;" "&amp;${__("SiteFields_Title_DisplayName")}</Formula><FieldRefs><FieldRef Name="${__("SiteFields_Title_DisplayName")}" /><FieldRef Name="${__("SiteFields_EventDate_DisplayName")}" /></FieldRefs></Field>`;`

**Comment by olemp** [comment]
No.

**Comment by olemp** [comment]
That didn't work. Not so quick on the close button.

**Comment by tarjeieo** [comment]
Then why is it in the dev branch? 😨

**Comment by olemp** [comment]
@tarjeieo To be more detailed (sorry), that didn't work for 1033, it works just fine for 1044.

**Comment by olemp** [comment]
Now attempting

```xml
<Field Type="Calculated" ID="{7604dadc-d8e3-4f35-bc58-890d33d908b9}" StaticName="GtProjectEventDateAndTitle" InternalName="GtProjectEventDateAndTitle" DisplayName="${__("SiteFields_GtProjectEventDateAndTitle_DisplayName")}"  Required="FALSE" ResultType="Text" ReadOnly="TRUE" Version="3" CustomFormatter=""><Formula>=TEXT(StartDate,"yyyy-mm-dd")&amp;" "&amp;Title</Formula><FieldRefs><FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" /><FieldRef ID="64cd368d-2f95-4bfc-a1f9-8d4324ecb007" Name="StartDate" /></FieldRefs></Field>
```

**Comment by olemp** [comment]
Error details

```
pp.main.js?rev=2.0.1:11705 Message: Error in request pipeline: Error making HttpClient request in queryable: [500] Internal Server Error Data: {"status":500,"statusText":"Internal Server Error","data":{"responseBody":{"error":{"code":"-2130575273, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The formula refers to a column that does not exist.  Check the formula for spelling mistakes or change the non-existing column to an existing column."}}},"responseHeaders":{}},"name":"ProcessHttpClientResponseException"}
```

**Comment by olemp** [comment]
Now attempting

```xml
<Field Type="Calculated" ID="{7604dadc-d8e3-4f35-bc58-890d33d908b9}" StaticName="GtProjectEventDateAndTitle" InternalName="GtProjectEventDateAndTitle" DisplayName="${__("SiteFields_GtProjectEventDateAndTitle_DisplayName")}"  Required="FALSE" ResultType="Text" ReadOnly="TRUE" Version="3" CustomFormatter=""><Formula>=TEXT(EventDate,"yyyy-mm-dd")&amp;" "&amp;Title</Formula><FieldRefs><FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" /><FieldRef ID="64cd368d-2f95-4bfc-a1f9-8d4324ecb007" Name="EventDate" /></FieldRefs></Field>
```

**Comment by olemp** [comment]
Same errror again

```json
{
  "status": 500,
  "statusText": "Internal Server Error",
  "data": {
    "responseBody": {
      "error": {
        "code": "-2130575273, Microsoft.SharePoint.SPException",
        "message": {
          "lang": "en-US",
          "value": "The formula refers to a column that does not exist.  Check the formula for spelling mistakes or change the non-existing column to an existing column."
        }
      }
    },
    "responseHeaders": {}
  },
  "name": "ProcessHttpClientResponseException"
}
```

Can't seem to find a working Schema XML for 1033.

**Comment by olemp** [comment]
Now trying

```xml
<Field Type="Calculated" DisplayName="Date and title" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1033" ResultType="Text" ReadOnly="TRUE" ID="{61c8e847-47ea-4846-9dd4-cdd78e308952}" SourceID="{17912a70-5ef8-451c-9bb3-415456e3dfe8}" StaticName="GtProjectEventDateAndTitle" Name="GtProjectEventDateAndTitle" ColName="sql_variant1" RowOrdinal="0" Version="4" CustomFormatter="" Required="FALSE"><Formula>=TEXT(EventDate,"yyyy-mm-dd")&amp;" "&amp;Title</Formula><FieldRefs><FieldRef Name="Title" /><FieldRef Name="EventDate" /></FieldRefs></Field>
```
which is a 100% copy of the schema XML from a working web.

**Comment by olemp** [comment]
Might have to specify `LCID` like above. Should create a resource for LCID in the `.resx` files if so.

**Comment by olemp** [comment]
Did not help.

**Comment by tarjeieo** [comment]
This is absurdely strange! And if you configure the same formula in the UX, everything works?

**Comment by olemp** [comment]
Yes! 😮

**Comment by olemp** [comment]
I've tried all kinds of schema xml now!

**Comment by olemp** [comment]
Not sure what to do here @tarjeieo? Do you want to have a try?

**Comment by tarjeieo** [comment]
Gonna juice it up

**Comment by tarjeieo** [comment]
No juice. Attempted several things
- Internalname vs displayname
- Square brackets vs no brackets
- Tried created the calc field at site level like suggested here: http://cameron-verhelst.be/blog/2012/11/17/sharepoint-calculated-column-calendar-start-time/

Not a critical feature... Let's close this.
