### ISSUE TITLE
Update gevinstoppfølging-query to support new status fiels and values

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#218]
Should be updated after new choice fields and values have been added.

**Comment by olemp** [comment]
What are the new fields? Should we try to make it dynamic perhaps?

**Comment by tarjeieo** [comment]
I don't think we should do dynamic for now, because I have some vague plans of giving these status fields values from e.g. 1-5 that can be translated to friendly values. Would be for a 2.2/3.0 release, and we need to discuss it. For now, this task entails including "Over budsjett", "Etter plan", Gevinstrealisering "Bak plan" etc.

**Comment by olemp** [comment]
Are we talking about the `BenefitsOverview` component here, @tarjeieo?
