### ISSUE TITLE
Date picker in the edit project item form gets stuck/hangs sometimes

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#244]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment

[X ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Date picker for start date and end date somestimes gets stuck/hangs. See if we have done anything to impact this with script or something else, e.g. test in a clean environment and compare.

#### Version

Please specify what version you are using: [ 2.0.1]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
I've seen this in several environments. It's a SP bug I'm pretty sure.

**Comment by olemp** [comment]
I guess these aren't related?

https://sharepoint.stackexchange.com/questions/72253/datepicker-not-working-correctly-on-sharepoint-2013-subsites
https://sharepoint.stackexchange.com/questions/88642/sharepoint-2013-datepicker-not-rendering-correctly
http://georgetowndctechie.blogspot.no/2014/09/datepicker-not-working-correctly-on.html

**Comment by tarjeieo** [comment]
Not related, no... This one looks kindof related, but I'm not sure if the solution is relevant for us? http://www.techmikael.com/2014/04/page-hanging-on-load-in-sharepointsolved.html

**Comment by tarjeieo** [comment]
Saw this in one env yesterday, but today I cannot reproduce for the life of me. Pretty sure it's some javascript loading issue in SharePoint OOTB.

**Comment by olemp** [comment]
That one seems a bit related. Not really sure if we can do anything about this.

**Comment by olemp** [comment]
I think we should close this @tarjeieo. Not related to any of our "code".
