### ISSUE TITLE
Tilbakemeldinger-liste (ikke i quicklaunch)

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#25]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Summary
- På hvilket område gjelder tilbakemeldingen 
- Beskrivelse av ønsket endring eller feilsituasjon 
- Status: Åpen, under utvikling, fullført, avvist 
- Kritikalitet: Genial idè, kjekt å ha, irriterende feil, alvorlig feil 
- Kommentar

**Comment by olemp** [comment]
List is added to root, but how should the list be accessible to users?

**Comment by tarjeieo** [comment]
Nice @olemp - We're not going to suggest usages of the list yet, but now it's possible to people to add it to quick launch if they want to use it.
