### ISSUE TITLE
Bug with Create project link

### ISSUE THREAD

**Issue by aleksKoss** [Puzzlepart/prosjektportalen#271]
#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

When using English version: Create project link doesn't show if you're a site collection admin, only for project owners.
#### Version

Please specify what version you are using: [2.0.1 ]

![ingen_nytt_prosjekt_knapp](https://user-images.githubusercontent.com/23027943/27695848-576335ca-5cf0-11e7-8ea1-06648ad3dbf8.PNG)

**Comment by olemp** [comment]
Hello @aleksKoss,

In https://github.com/Puzzlepart/prosjektportalen/issues/248 we added "code" to only show the link for project owners. We use audiencetargeting on group level, so if a admin is not a member of the owners group, it won't show. We've decided this is an edge case, and don't want to support the scenario where the user is only an admin.
