### ISSUE TITLE
Add a shortcut to open projectstatus for a project from the portfolio page

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#273]
There should be a way to open the project status page (in a dialog?) from the project portfolio page. Options
1. Include it in the project modal dialog
2. Include it as a special column that you can choose to include in the view
3. Include it as a clickable icon next to the title 

Input anyone?

**Comment by olemp** [comment]
Proposal:

![273-01](https://user-images.githubusercontent.com/7606007/28517988-aa383b54-7066-11e7-960c-df1db3772f15.PNG)

**Comment by tarjeieo** [comment]
I like this, but let's do the following
* Add it to all portfolio views
* Make it open in a dialog

**Comment by olemp** [comment]
@tarjeieo It does not look good in a dialog with all the scroll/sticky functionality. Requires too much work. You want it to be a default selected field in all views?

**Comment by tarjeieo** [comment]
I suggest that we then instead add it to the modal dialog as a button besides the home button. Less "intrusive"...

**Comment by olemp** [comment]
Done!
