### ISSUE TITLE
Change column order in default view for Endringsanalyse

### ISSUE THREAD

**Issue by ElsaNau** [Puzzlepart/prosjektportalen#277]
The default view in endringsanalyse has the title column as the third and last column making it confusing when you want to open an endring. The default should be title (Endring), Prosess, Endringsbeskrivelse.

**Comment by olemp** [comment]
I agree, but I think this is how it was specified. Input @tarjeieo?

**Comment by tarjeieo** [comment]
Similar to  #278 - I agree with you...

**Comment by olemp** [comment]
`LinkTitle` (title with menu) is now the first column. Will be included in the next minor release @ElsaNau
