### ISSUE TITLE
Change default view on gevinstanalyse og gevinstplan

### ISSUE THREAD

**Issue by ElsaNau** [Puzzlepart/prosjektportalen#278]
The default view in the gevinstanalyse og gevinstplan list now has the related endring as the first column. There is no clickable title-column for the actual gevinst. Gevinst should be the first column, and should be clickable in the default view so users can click to open the gevinst.

**Comment by tarjeieo** [comment]
I agree, although specification says that it should be as is now. But I'm inclined to go with your suggestion as that is more in line with default behavior. Let's change order.

**Comment by olemp** [comment]
Done. Will be included in next minor release @ElsaNau
