### ISSUE TITLE
Add clickable link to source-project in Erfaringslogg

### ISSUE THREAD

**Issue by ElsaNau** [Puzzlepart/prosjektportalen#279]
There should be a link to the project that reported the erfaring in the erfaringslogg on porteføljenivå.

**Comment by tarjeieo** [comment]
Not important, but we can leave it here to fix if it's very simple @olemp

**Comment by olemp** [comment]
It's kinda annoying, and not much work

**Comment by olemp** [comment]
Done, will be included in next minor version @ElsaNau
