### ISSUE TITLE
Farge på pil bør indikere om gevinstmåling er fordelaktig eller ufordelaktig

### ISSUE THREAD

**Issue by ElsaNau** [Puzzlepart/prosjektportalen#281]
Mange direkte gevinster vil måles på f.eks reduksjon av kostnad. Derfor er det litt misvisende å ha en rød pil på en fordelaktig nedgang og vice versa en grønn pil på en ufordelaktig økning. Er det mulig å gjøre slik at farge på pil reflekterer måleresultat?

**Comment by tarjeieo** [comment]
Den skal gjøre det. Kan du legge ved skjermbilde? Tror du kan copy paste rett inn i kommentarfeltet her :) 

Se forøvrig også #141 - vi har noen logiske brister i kalkulasjonene.

**Comment by ElsaNau** [comment]
![image](https://user-images.githubusercontent.com/29433316/28675150-44c61a7e-72e7-11e7-899a-b45d81a263d4.png)

**Comment by tarjeieo** [comment]
Enda mer interessant når en ser hele - haha. Tar en kikk...
![image](https://user-images.githubusercontent.com/1837390/28675699-e4a68d34-72e8-11e7-9c78-ebc1943da75d.png)

**Comment by ElsaNau** [comment]
LOL - my bad!

**Comment by tarjeieo** [comment]
NP! URL er forresten: https://pzlcloud.sharepoint.com/sites/ppdemo_v2/trivsel-pa-arbeidsplassen/SitePages/BenefitsOverview.aspx

**Comment by tarjeieo** [comment]
Spørsmål: Dersom en ønsker en nedgang, og har oppnådd det - da har man en positiv trend, selv om tallene har negativ retning. Hvordan skal pilen se ut da?

**Comment by tarjeieo** [comment]
Se #141
