### ISSUE TITLE
Copying default documents sometimes fails when you have folders with subfolders in standarddokumenter

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#282]
Sometimes the copying fails when using folders and subfolders. I created a folder Test and a subfolder Sikkert. Sometimes nothing except the Test folder is copied. I got this error message: 
````
pp.main.js?rev=2.0.1:1 Message: Error making HttpClient request in queryable: [500] Internal Server Error Data: {"responseBody":{"error":{"code":"-2130247139, Microsoft.SharePoint.SPException","message":{"lang":"nb-NO","value":"Finner ikke (null) sites/pp-pnp23/failcom/Delte dokumenter/Test/Sikkert."}}},"responseHeaders":{}}
t.ConsoleListener.e.log @ pp.main.js?rev=2.0.1:1
(anonymous) @ pp.main.js?rev=2.0.1:1
e.log @ pp.main.js?rev=2.0.1:1
t.Logger.e.log @ pp.main.js?rev=2.0.1:1
t @ pp.main.js?rev=2.0.1:1
(anonymous) @ pp.main.js?rev=2.0.1:1
pp.main.js?rev=2.0.1:1 Message: Error in request pipeline: Error making HttpClient request in queryable: [500] Internal Server Error Data: {"status":500,"statusText":"Internal Server Error","data":{"responseBody":{"error":{"code":"-2130247139, Microsoft.SharePoint.SPException","message":{"lang":"nb-NO","value":"Finner ikke (null) sites/pp-pnp23/failcom/Delte dokumenter/Test/Sikkert."}}},"responseHeaders":{}},"name":"ProcessHttpClientResponseException"}
````
I suspect that it errors out on copying the second folder, and the aborts the rest of the copying...

**Comment by olemp** [comment]
Was able to reproduce. Might happen because of the sequence the folders are created in? Could you have a look at `Provision\Data\Files\index.ts` @tarjeieo?

**Comment by tarjeieo** [comment]
I'm suspecting that since the creation happens through a set of promises executed with Promises.all(), we end up in a race condition where longest folder path will fail when it's the first folder path that is executed/created. Do you know of a good way to run the folder creation synchronously?

**Comment by olemp** [comment]
Yep, `list.reduce` can be used, but how do we make sure we create the shortest folder structure first?

**Comment by tarjeieo** [comment]
Run folders.sort() before we execute the promises...

**Comment by olemp** [comment]
Check if https://github.com/Puzzlepart/prosjektportalen/pull/289 solved this @tarjeieo
