### ISSUE TITLE
Support subtasks/multiple levels of tasks when copying tasks from "Standardoppgaver"

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#283]
This was supported in v1 using this approach: https://github.com/prosjektstotte/sp-prosjektportal/blob/master/Glittertind.SharePoint/Glittertind.SharePoint.Sherpa/content/SiteAssets/js/gt.project.setup.js#L753

We should support this in the new version as well.

**Comment by olemp** [comment]
Done!
