### ISSUE TITLE
IE 10 rendering issues

### ISSUE THREAD

**Issue by trillian74** [Puzzlepart/prosjektportalen#288]
#### Category

[ ] Enhancement

[ ] Bug

[X ] Question

#### Environment

[ X] SharePoint Online

[ X] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Hi guys, great update. I was wondering if you have a browsersupport matrix - because i have issues with operning the portal page and project homepage in IE 10

#### Version

Please specify what version you are using: [v2.0.2 ]

#### Expected / Desired Behavior / Question
Hi guys, great update. I was wondering if you have a browsersupport matrix - because i have issues with opening the portal page and project homepage in IE 10. It renders great in edge, chrome and firefox mm - but in IE 10 there is nothing to see.

It may be that it's not supposed to work properly in this browser version, but i couldn't find any information on it.

#### Observed Behavior
I expected to see both the project search and the most right "create new project area" and the project status information on the project home page.

#### Steps to Reproduce
Opening the portal page in an IE10 browser

**Comment by olemp** [comment]
@trillian74 Thanks for reporting this issue. We have not tested it out in IE 10 properly. Do you have some console output?

**Comment by trillian74** [comment]
yes it basically just dumps out SCRIPT1002: Syntax error
pp.main.js (11081,1) sorry to say: not very helpfull:)

**Comment by olemp** [comment]
@trillian74 How did you install? If you're using any of the watch gulp tasks, you need to use the one for production. The production build is automatically installed when installing from a zip generated from `gulp release`.

**Comment by trillian74** [comment]
Ok,  i didn't use the production one - i'll test that and reply. (tomorrow)

**Comment by olemp** [comment]
That's probably the reason. When running the regular `watch` gulp task, `node_modules` are not transpiled to save time. We will update the dev doc https://github.com/Puzzlepart/prosjektportalen/wiki/Development.

**Comment by trillian74** [comment]
sorry for the inconvenience, using the release version solved it :) thanks
I'm closing this aswell since the question was asked and answered.
