### ISSUE TITLE
English: Taxonomy installation fails when 1033 is default language in termstore

### ISSUE THREAD

**Issue by pettersh** [Puzzlepart/prosjektportalen#291]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

I'm installing the 1033 version of pp and English labels are not created as part of taxonomy provisioning because the default language of the termstore is 1033. 

End result result is that all terms are installed with 1044 labels only. You must expect that 1033 tenants have 1033 as default language in termstore (and likewise that 1044 labels has 1044 as default language, and so forth)

Maybe issue can be resolved using resources? If not the taxonomy template probably needs to be duuped for each language

#### Version

Please specify what version you are using: [dev branch]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by tarjeieo** [comment]
Good find!

**Comment by olemp** [comment]
Could you have a look at this @pettersh?

**Comment by pettersh** [comment]
@olemp og @tarjeieo I think we need to detect the default language of the term store before applying the/a taxonomy template.

Here's how:

`Connect-PnPOnline -Url https://tenant.sharepoint.com
$session = Get-PnPTaxonomySession
$ts = $session.GetDefaultSiteCollectionTermStore()
$lcid = Get-PnPProperty -ClientObject $ts -Property DefaultLanguage`

Then we simply load the correct template.

The current template has terms defined in 1044, with labels for both 1033 and 1044. If default language is 1044, 1044 labels are dropped, but terms are still imported with Norwegian content, which is fine.

Id default language is 1033, the terms should have English texts.

I'll also see if we can use resx files to avoid the duplication

cc: @okms

**Comment by pettersh** [comment]
I've tested installing to a term store with English as default language, with current result:
<img width="227" alt="taxonomy-pp-1033" src="https://user-images.githubusercontent.com/2064929/29216593-71f0fe3c-7eaf-11e7-9b18-e86c57938a9c.png">

The Norwegian labels are also present
<img width="228" alt="taxonomy-pp-1044" src="https://user-images.githubusercontent.com/2064929/29216599-776ab100-7eaf-11e7-9b14-2ef2da4e6864.png">

If installed into a term store with Norwegian as default language, term group names and term set names will be in Norwegian.

**Comment by olemp** [comment]
Is this after your fix @pettersh?

**Comment by olemp** [comment]
Looks good. I merged the PR.

Just added the _retrieve language_ bit to ahelper function `Get-TermStoreDefaultLanguage`.
