### ISSUE TITLE
Filter the frontpage lists webparts (tasks, documents, risk) only if the web part titles includes "(gjeldende fase)"/"(current phase)"

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#293]
If someone has renamed the web parts, it's to be interpreted as a sign that they don't want the view to be filtered on changing phase. 

Feasible @olemp?

**Comment by olemp** [comment]
There's no easy way to support a `{webTitle}` token. Requires quite big changes (and feel it will be a bit hacky). Is this something a lot of users is requesting?
