### ISSUE TITLE
Add the name of the project site after "Hjem/Home" in the quick launch

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#294]
Can we support tokens in Provision/Template/Objects/Navigation/index.ts so that we can write e.g. 
```
        {
            Url: __("Project_WelcomePage"),
            Title: __("Navigation_Home_Title") + " ({siteTitle})",
            IgnoreExisting: true,
        },
```

**Comment by olemp** [comment]
There's no easy way to support a `{webTitle}` token. Requires quite big changes (and feel it will be a bit hacky). Is this something a lot of users is requesting?

**Comment by tarjeieo** [comment]
Well, only one customer for v2, but others requested it for v1 as well, so a few people want it, sure. 

Is this harder now because we don't have the _spPageContextInfo object for the new project site? 

(I agree with you, if it's too hacky we skip it)

**Comment by olemp** [comment]
No, we don't have the _spPageContextInfo.

**Comment by olemp** [comment]
I suggest we skip it because it's too hacky. If people want in their project site, it's quite simple to do it manually.

**Comment by tarjeieo** [comment]
I agree, let's not do this. Another reason for not doing it is that the contextual information will be improved in the modern experience in O365 (and hopefully SP2016), e.g. the following screenshot:
![image](https://user-images.githubusercontent.com/1837390/29067950-0cb72496-7c35-11e7-9aab-b4664be5488f.png)
