### ISSUE TITLE
Installation failed: Adding field {31e405e0-2890-439d-9c9f-42354154feda} failed: The field was found invalid:  {Site.URL}

### ISSUE THREAD

**Issue by pettersh** [Puzzlepart/prosjektportalen#295]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Installing the 1033 version of pp from dev failed during site fields provisioning.
Deploying root-package with fields, content types, lists and pages...
Error installing main template to https://skodvinhvammen.sharepoint.com/sites/projects

The site is a fresh team site (1033) and build being installed is (1033) from dev.

The log refers to field id, which is defined in templates\root\Objects\SiteFields.xml(se below).
It seems that **{Site.URL}** is not valid as default value for the Note field named **GtDpSearchQuery**

`<Field Type="Note" DisplayName="Query" ID="{31e405e0-2890-439d-9c9f-42354154feda}" StaticName="GtDpSearchQuery" Name="GtDpSearchQuery" Group="{resource:SiteFields_Group}" Description="For more information about writing search queries, see Keyword Query Language (KQL) syntax reference https://dev.office.com/sharepoint/docs/general-development/keyword-query-language-kql-syntax-reference">
        <Default>ContentTypeId:0x010109010058561f86d956412b9dd7957bbcd67aae0100* Path:{Site.URL}</Default>
    </Field>` 

#### Version

Please specify what version you are using: [dev]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
`
powershell.exe Information: 0 : 2017-08-04 11.17.00.3330	[Fields]	[7]	[Debug]	Adding field {31e405e0-2890-439d-9c9f-42354154feda} to site	79898ms	82411523-e98e-4e36-a755-7783f54a44f8
powershell.exe Error: 0 : 2017-08-04 11.17.00.3641	[Fields]	[7]	[Error]	The field was found invalid:  {Site.URL}	79929ms	82411523-e98e-4e36-a755-7783f54a44f8
powershell.exe Error: 0 : 2017-08-04 11.17.00.3641	[Fields]	[7]	[Error]	Adding field {31e405e0-2890-439d-9c9f-42354154feda} failed: The field was found invalid:  {Site.URL} :    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectField.CreateField(Web web, XElement templateFieldElement, PnPMonitoredScope scope, TokenParser parser, String originalFieldXml)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectField.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)	79930ms	82411523-e98e-4e36-a755-7783f54a44f8

`

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by tarjeieo** [comment]
Weird that this is thrown in the english version and not the 1044 one...

**Comment by pettersh** [comment]
Could be related to this https://github.com/SharePoint/PnP-Sites-Core/issues/1045.

I'm provisioning without bundled pnp. I'll see if upgrading to a new version of pnp-powershell will resolve the issue

**Comment by pettersh** [comment]
I used the following module:

`PS C:\dev-git\prosjektportalen\dist> Get-Module
PS C:\dev-git\prosjektportalen\dist>
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandler, Set-PSReadlineKeyHandler...}
Binary     2.12.17... SharePointPnPPowerShellOnline       {Add-PnPContentType, Add-PnPContentTypeToDocumentSet, Add-PnPContentTypeToList, Add-PnPCustomAction...}`

**Comment by pettersh** [comment]
I have upgraded SharePointPnPPowerShellOnline from 2.12.1702.0 to 2.16.1706.1 and rerunning the installation to see if it helps.

**Comment by pettersh** [comment]
Oppgradering av PnP-PowerShell løste denne.
