### ISSUE TITLE
Make the Projectstatus page more configurable

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#296]
Would be cool if we could allow people to configure which sections and which lists to show on the project status page. It's probably not realistic to have everything possible, would it's probably achievable to make the list views generic and allow people to show different lists in different sections....

Let's discuss this @olemp

**Comment by olemp** [comment]
There's so many possibilities. I'd prefer a sketch on your thoughts here, boss.

**Comment by tarjeieo** [comment]
Yeah, will do! A lot of options, but I'm thinking something in the lines of a root list "Sections" with the fields Title*, InternalName*, StatusField, InternalFieldNames, ListName,  

The convention would be that each section only supports one list. You can also use "InternalFieldsNames" which will render the fields chosen in a section similar to the "EvonomySection" we have now. Not sure how/if we should support the risk matrix in the configuration, or if it should be just a "hardcoded" exception.

**Comment by olemp** [comment]
Root content type `Section`

Then we'll have a few content types that inherits from the base.

* List Section
** Options: List, Fields
* Status Section
** Options: None
* Economy Section
** Options: Fields
* Risk Section
** Options: Fields, ShowRiskMatrix

**Comment by tarjeieo** [comment]
Yeah, maybe if it's not too much overhead.... May I also suggest that we keep the query in a Query-field for the list section. That way it's possible to change

**Comment by olemp** [comment]
What query?

**Comment by tarjeieo** [comment]
viewquery

**Comment by olemp** [comment]
Oh, I was thinking pointing to an existing view.

**Comment by tarjeieo** [comment]
I think I want to have both viewfields and viewquery in the config list, to support any type of list. Else the views would need to be added to all the lists...

**Comment by olemp** [comment]
@tarjeieo Have a look at https://github.com/Puzzlepart/prosjektportalen/tree/%23296

**Comment by olemp** [comment]
Re-opened. `Economy Section` will be renamed to `Project Properties Section` and will have the field `FieldName` so it can optionally show status for a field.
