### ISSUE TITLE
Support copying URL fields with tokens

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#298]
For å støtte "standard lenkeliste" i rommene trenger vi å legge inn støtte for følgende
1.	Støtte URL-felt i kopiering av standarddata
2.	Støtte tokens i kopiering av standarddata (for å kunne linke til e.g. /{site}/Dokumenter istedenfor å hardkode)

Merk: SharePoint URL-felter validerer URLene, slik at URLene må starte med enten https:// eller /. Derfor må vi støtte relative url tokens, slik som f.eks. {relativeWebUrl} og {relativeSiteColUrl}. Bruk standardnavn på tokens om det finnes/er brukt andre steder.

**Comment by olemp** [comment]
Added support for token {webRelativeUrl}

Let's say we have the URL `https://contoso.sharepoint.com{webRelativeUrl}/Lists/Oppgaver/` and we're creating the web `Test 1` with URL `test-1` on the site `https://contoso.sharepoint.com/sites/projectportal` the URL will be `https://contoso.sharepoint.com/sites/projectportal/test-1/Lists/Oppgaver/` after tokens are replaced. 

I'm making sure double slashes are replaced so we can support both `https://contoso.sharepoint.com{webRelativeUrl}/Lists/Oppgaver/` and `https://contoso.sharepoint.com/{webRelativeUrl}/Lists/Oppgaver/`.

**Comment by olemp** [comment]
Is there any point in support site collection tokens? It's static anyways.

**Comment by tarjeieo** [comment]
Nice @olemp - and you're right of course abt. sitecol tokens - no need.
