### ISSUE TITLE
Add column for controlling index of phase check list items

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#3]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ X ] Enhancement

[ ] Bug

[ ] Question

#### Description
Add a new field "Order index" that is used in the view to sort on. This way, it's possible to control the order of phase checklist items when adding new items later.

**Comment by olemp** [comment]
@tarjeieo 
1. Should the field be included in the default view on root level?
2. Should the field be included in the default view on project level?
3. Should the field have some default values?

**Comment by tarjeieo** [comment]
@olemp - good questions
1. yes
2. no
3. yes, 10, 20, 30 etc. in the order they are implemented in today
