### ISSUE TITLE
Forslag til forbedringer av prosjektstatus-siden

### ISSUE THREAD

**Issue by ThomasGranheim** [Puzzlepart/prosjektportalen#303]
Forslag til forbedringer av prosjektstatus-siden
1. Navigeringen på siden burde ha en farge som ikke går igjen i status (e.g. blå, grå), også den grønne toppmenyen kunne hatt en mer nøytral farge 
2. På små skjermer bryter navigeringsknappene ut av beholderen 
3. Historikkfiler: Start filnavn med dato 
4. Noe mindre skrift og luft på øverste seksjon 
5. Navigeringen viser ikke hvilket element som er valgt 
6. Risiko: Sorter på risikofaktor

**Comment by tarjeieo** [comment]
Dette er gode innspill fra UiB

**Comment by olemp** [comment]
Foreslår noe sånt for navigasjonslinjen. Fargen er `#939393`.

![303-01](https://user-images.githubusercontent.com/7606007/29268952-631af8e4-80ef-11e7-9310-dccee09950ef.PNG)

**Comment by olemp** [comment]
_På små skjermer bryter navigeringsknappene ut av beholderen_

Knekker på ca 1460 px.

**Comment by tarjeieo** [comment]
Liker fargen Ole. Jeg har noen tanker om litt tweaks på designet på den siden for å få den til å skalere litt bedre. Jeg kan godt se litt på det Ole.

**Comment by olemp** [comment]
`6. Risiko: Sorter på risikofaktor` fikses sammen med https://github.com/Puzzlepart/prosjektportalen/issues/296.

**Comment by olemp** [comment]
`Navigeringen viser ikke hvilket element som er valgt`

Dette ble støttet tidligere, @ThomasGranheim? Vet du hva som mangler?

**Comment by olemp** [comment]
`3. Historikkfiler: Start filnavn med dato`

Enig @tarjeieo?

**Comment by tarjeieo** [comment]
Ja, enig med 3.

**Comment by olemp** [comment]
-1. Navigeringen på siden burde ha en farge som ikke går igjen i status (e.g. blå, grå), også den grønne toppmenyen kunne hatt en mer nøytral farge-
-2. På små skjermer bryter navigeringsknappene ut av beholderen-
-3. Historikkfiler: Start filnavn med dato-
-4. Noe mindre skrift og luft på øverste seksjon-
5. Navigeringen viser ikke hvilket element som er valgt 
6. Risiko: Sorter på risikofaktor

**Comment by ThomasGranheim** [comment]
I think you need to have some CSS for the activeClass="active" on the Link react component.
