### ISSUE TITLE
Got errors in search for project statuses etc on 2013 onPrem - made a fix and it seems good

### ISSUE THREAD

**Issue by trillian74** [Puzzlepart/prosjektportalen#305]
#### Category

[*] Enhancement

[*] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[* ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Project search on portalpage returned errors on rest call

I change this in the .\src\js\WebParts\DynamicPortfolio\Configuration\index.ts file and copied the pp.main over and it worked  ref: [rest-api-get-by-author-differences-by-platform](https://sharepoint.stackexchange.com/questions/137294/rest-api-get-by-author-differences-by-platform )

**It seems to me that it works on 2013 and Online (haven't tested it on 2016)**

` lists.getByTitle("DynamicPortfolioViews")
                .items
                .filter(`((GtDpPersonalView eq 0) or (GtDpPersonalView eq 1 and Author/Id eq ${_spPageContextInfo.userId}))`)
                .expand("GtDpFieldsLookup", "GtDpRefinersLookup", "Author")
                .select("ID", "GtDpDisplayName", "GtDpSearchQuery", "GtDpIcon", "GtDpDefault", "GtDpFieldsLookup/GtDpDisplayName,Author/Id", "GtDpRefinersLookup/GtDpDisplayName")
                .orderBy("GtDpOrder")
                .get(),`

#### Version

Please specify what version you are using: [2.0.3 ]

#### Expected / Desired Behavior / Question
Search for projects portefolio (Portfolio.aspx) working correctly

#### Observed Behavior
Console returned error because using Author in rest call failed

#### Steps to Reproduce
Test it on 2013 onprem

**Comment by tarjeieo** [comment]
Hi @trillian74,

Thanks for the notification and resolution - much appreciated! I created a branch for the fix and merged it into the dev-branch now. 

Feel free to submit a PR to the dev branch next time, might be even easier for both you and us :)
