### ISSUE TITLE
Installing Prosjektportalen to SharePoint 2013 fails with the error "zoneid method not found"

### ISSUE THREAD

**Issue by wobba** [Puzzlepart/prosjektportalen#320]
#### Category
[x] Bug
[x] Question

#### Environment

[x] SharePoint 2013

#### Summary

I get an issue installing PP2.0 with an error zoneid method not found. I believe this is related to https://github.com/SharePoint/PnP-Sites-Core/issues/866. Is there a specific PnP Posh version which will work without this error?

**Comment by pettersh** [comment]
@wobba Did you install with the pnp modules bundled with PP or did you use the -SkipLoadingBundle switch and loaded your own installed modules?

**Comment by wobba** [comment]
I used the switch which download the PP bundle, which would be the most obvious choice for quick install.

**Comment by wobba** [comment]
@pettersh @okms @tarjeieo  Noen ideer på denne når jeg skal teste å re-installere på fredag?

**Comment by pettersh** [comment]
@wobba I have only installed to SPO, and then using the `-SkipLoadingBundle` switch to use my local version instead of the bundled one. I used the following version. I know this info doesn't help you much

(get-module -Name SharePointPnPPowerShellOnline).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
2      16     1706   1

**Comment by tarjeieo** [comment]
Er patching av miljøet ikke mulig @wobba? Eller er poenget at en får samme feil uansett pga. PnP-sites-core bugen?

**Comment by wobba** [comment]
Miljøet skal patches, så da finner vi ut om det virker, og får patchlevel version + pnp som man vet funker eller ikke. Tester på fredag :)

**Comment by tarjeieo** [comment]
Ok bra, keep us posted :)

**Comment by tarjeieo** [comment]
I've documented how to work around this issue here: https://github.com/Puzzlepart/prosjektportalen/wiki/Installation-troubleshooting

cc @wobba

**Comment by tarjeieo** [comment]
This is confirmed solved by August 2017 CU for SP2013. If an upgrade is impossible, a workaround is explained here: https://github.com/Puzzlepart/prosjektportalen/wiki/Installation-troubleshooting.

We recommend to upgrade the environment.
