### ISSUE TITLE
Support rendering "custom components" in the project status page.

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#322]
Custom components would be components that we develop, e.g. like the "Gevinstoversikt" we used to have. Another component could be "Milestones", which visualized the milestones list. 

An approach to this could be to have a dropdown-field we control with "Status-components", and a status section content type in the status section list for "Status components".

What do you think @olemp?

**Comment by olemp** [comment]
I don't like the complications of rendering a component by name, we would need to hold a register of components with Name => Component.

Milestones list can be visualized using `List Section`.

... but we could discuss this in further details..

**Comment by tarjeieo** [comment]
We would, indeed.... But I don't mind that too much. Is it a big problem?

Yeah, but I'm hoping to something visually pleasing on the eye, like a timeline ;-)

**Comment by olemp** [comment]
We could be able to do something smart with `C:\code\prosjektportalen\src\js\WebParts\index.tsx` which now holds `wp_map`

```typescript
const wp_map: IWebPartMapping = {
    "pp-projectlist": <ProjectList />,
    "pp-projectinfo": <ProjectInfo filterField="GtPcFrontpage" />,
    "pp-projectphases": <ProjectPhases />,
    "pp-newprojectlink": <NewProjectLink />,
    "pp-announcements": <Announcements />,
    "pp-latestprojects": (
        <LatestProjects
            itemsCount={8}
            reloadInterval={360} />
    ),
    "pp-quicklinks": <QuickLinks />,
    "pp-dynamicportfolio": <DynamicPortfolio />,
    "pp-benefitsoverview": <BenefitsOverview />,
    "pp-benefitsoverview-search": (
        <BenefitsOverview
            dataSource={DataSource.Search}
            groupByOptions={[{
                name: __("String_Project"),
                key: "SiteTitle",
            }]} />
    ),
    "pp-projectstatus": <ProjectStatus />,
    "pp-experiencelog": <ExperienceLog />,
};
```

**Comment by tarjeieo** [comment]
Is something like this out of the question? https://stackoverflow.com/a/33835395

**Comment by olemp** [comment]
No, that's approx technical solution I was thinking of.

Instead of `wp_map` being `IWebPartMapping` it should contain an array of `IWebPartComponent` (or something similiar) which has properties `name`, `containerid` and the actual `component`. 

`wp_map` should also be exported so it can be used in our ProjectStatus component.

Name should be "friendly display name" and matches the options for our sp choice field `CustomComoponent`.

**Comment by olemp** [comment]
Included in https://github.com/Puzzlepart/prosjektportalen/releases/tag/v2.1.0
