### ISSUE TITLE
ProjectStatus: Navigation doesn't render properly in IE 11

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#328]
#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[x] SharePoint 2013

[x] SharePoint 2016

#### Summary

Please summarize the issue.

#### Version

Please specify what version you are using: [2.1.0]

**Comment by olemp** [comment]
Screenshot:

![328-01](https://user-images.githubusercontent.com/7606007/29463197-2849dd2a-8432-11e7-8e54-789af4657dc4.PNG)

**Comment by olemp** [comment]
Will you have a look at this soon @tarjeieo?

**Comment by tarjeieo** [comment]
Probably won't have time this week. It's most likely just a quickfix of adding -ms-flex rules in additon to the normal flex-rules. Feel free to ggrab it if you have time.

**Comment by olemp** [comment]
https://css-tricks.com/using-flexbox/

**Comment by olemp** [comment]
A few issues with flexbox and IE. We should perhaps look another solution @tarjeieo?

![328-02](https://user-images.githubusercontent.com/7606007/30324705-478b6bc4-97c2-11e7-903e-a9d033cc6534.PNG)

**Comment by olemp** [comment]
Looks like https://github.com/Puzzlepart/prosjektportalen/commit/1dc882faa0e72d0f6d0e7cd95bcc693c49b1b2b2 solved it.

**Comment by tarjeieo** [comment]
Nice fix!
