### ISSUE TITLE
Office ui fabric styling breaks after the page is loaded

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#333]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment

[X ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

This is especially easy to see on the project status page. The page loads fine, and then after ~1 sec the office ui fabric styling breaks. After investigating this, it looks to be breaking after the SPO script https://spoprod-a.akamaihd.net/files/odsp-next-prod_ship-2017-08-11-sts_20170818.001/listviewdataprefetch-784d3572.js is loaded.

#### Version

Please specify what version you are using: [2.1.0 ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
Only 3 results on Google for `listviewdataprefetch.` 

One of them: http://spjsblog.com/forums/topic/sharepoint-online-require-js/

**Comment by olemp** [comment]
It might be related to `MISMATCHED ANONYMOUS DEFINE() MODULES`

http://requirejs.org/docs/errors.html

**Comment by olemp** [comment]
Someone created a issue for this https://github.com/OfficeDev/office-ui-fabric-react/issues/2562

**Comment by olemp** [comment]
Also looks like `pnp-js-core` is having some similiar issues

https://github.com/SharePoint/PnP-JS-Core/issues/470

**Comment by olemp** [comment]
Probably relevant aswell: https://dev.office.com/blogs/RequireJS-On-First-Release-Tenants

**Comment by olemp** [comment]
This would be a quickfix:

```javascript
let css = "";
let styles = document.querySelectorAll("style");

window.setTimeout(() => {
    styles.forEach(style => css += style.innerText);
    let styleSheet = document.createElement("style");
    styleSheet.innerText = css;
    document.body.appendChild(styleSheet);
}, 1000);
```

It stores the injected `<style>` tags before they're removed by `require.js` or `listviewdataprefetch`, and appends them to a separate `<style>` tag in document.body.

**Comment by olemp** [comment]
Tried the following without any success:

```typescript
export const Render = () => {
    SP.SOD.executeFunc("require.js", null, () => {
        WebPartComponents.forEach(wpc => wpc.renderOnPage());
    });
};
```

**Comment by olemp** [comment]
Looks like it's solved in https://github.com/OfficeDev/office-ui-fabric-react/issues/2562#issuecomment-325910036
