### ISSUE TITLE
Task list in "Minutes of Meeting"

### ISSUE THREAD

**Issue by PrinsMild** [Puzzlepart/prosjektportalen#334]
#### Category

[ ] Enhancement

[ ] Bug

[x] Question

#### Environment

[x] SharePoint Online

[x] SharePoint 2013

[x] SharePoint 2016

#### Summary

What's the purpose of using the the task list under "Minutes of Meeting" (SitePages/Mom.aspx)? I thought this was a bug in earlier versions, but is still in the 2.0 release.

#### Version

Please specify what version you are using: [2.1.0]

**Comment by tarjeieo** [comment]
Yeah, we didn't change that. It's still there from the v1 specification. I think the point is that the output from the MoM is two-fold: concerns, decisions and changes (log list) and action points (task list).

That said, we are open to good ideas here - this feature is in need of some love!
