### ISSUE TITLE
Allow sorting in project status list fields

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#336]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X ] Enhancement

[ ] Bug

[ ] Question

####

As a user I want to be able to sort the lists in the project status. The most important fields are single line of text, date, number, currency, calculated and choice (single select).

**Comment by olemp** [comment]
Not possible to sort date fields as of now because of localized date format from fieldValuesAsHtml.

https://www.npmjs.com/package/array-sort

This format could work

```
var arraySort = require('array-sort');
 
var posts = [
  { path: 'c.md', locals: { date: '2014-01-09' } },
  { path: 'a.md', locals: { date: '2014-01-02' } },
  { path: 'b.md', locals: { date: '2013-05-06' } },
];
 
// sort by `locals.date` 
console.log(arraySort(posts, 'locals.date'));
 
// sort by `path` 
console.log(arraySort(posts, 'path'));
```
