### ISSUE TITLE
Sort fields of list content types after adding lookup fields

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#34]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ X] Enhancement

[ ] Bug

[ ] Question

#### Explanation

It would be great if we could sort the list columns after adding the "Endring" lookup (Gevinstanalyse-list) and the "Gevinst" lookup (Gevinstoppfølging-list) so that these respective columns can be ordered as the first or second fields in the forms.

**Comment by olemp** [comment]
Currently no support for this in `sp-pnp-js` @tarjeieo

**Comment by olemp** [comment]
Here's the REST endpoint, but I can't figured out how the parameter `internalNames` are set.

https://msdn.microsoft.com/en-us/library/office/jj838539.aspx

cc @tarjeieo

**Comment by olemp** [comment]
Tried a POST against the following URL `/_api/web/lists/getByTitle('Endringsanalyse')/contenttypes('0x01004D8897A0212F9A40A4C2209D89E5AD4C0073ABBAEC4B9D0D4495E9C7790DED2A27')/fieldlinks/reorder?internalNames=['GtChallengeDescription','Title','GtProcess']`. It yields 400 success, but nothing changes.

**Comment by tarjeieo** [comment]
Guess you've also tried without brackets?
`/_api/web/lists/getByTitle('Endringsanalyse')/contenttypes('0x01004D8897A0212F9A40A4C2209D89E5AD4C0073ABBAEC4B9D0D4495E9C7790DED2A27')/fieldlinks/reorder?internalNames='GtChallengeDescription','Title','GtProcess'`

**Comment by olemp** [comment]
Update: Can't find a working syntax for changing fieldlinks order.

**Comment by tarjeieo** [comment]
Closing this as a "can't be fixed" because of technical limitations
