### ISSUE TITLE
Integration of the Project Portal with Project Online

### ISSUE THREAD

**Issue by PaulBorisov** [Puzzlepart/prosjektportalen#340]
Hi Tarjei,

We discussed your excellent Project Portal on the previous week. As you remember, I had questions about failures in its provisioning into a tenant of Project Online (i.e. "Private Site Collection with Project Web App", shortly PWA).

I have made some research on this week and managed to do the complete provisioning of Project Portal into a PWA of Project Online. I share the results with you for the case you would want to include this nice tiny integration option in the deployment instructions or in the setup.

So here we go.

Failures of "Prosjektportalen" deployments inside a PWA site collection of Project Online are related to certain assumptions in the PnP-based provisioning logic.

Assumption 1. A target site should contain the "Associated Visitors Group" defined. This is not true in the case of PWA. 

As a result, the provisioning logic fails with the exception: Object reference not set to an instance of an object on server. The object is associated with property AssociatedVisitorGroup.

Resolution: I have opened <PWA>/_layouts/15/permsetup.aspx, and manually added the corresponding setting. The issue was eliminated.

Assumption 2. Root site of a site collection should contain document libraries "Site Pages" and "Site Assets". This is not true in the case of PWA; it does not have these libraries by default.

As a result, the provisioning fails with the exception: The object specified does not belong to a list.
As I found in my research, in the case of missing libraries the provisioning logic mistakenly creates two regular site folders .../SiteAssets and .../SitePages instead of corresponding document libraries and after that tries adding new custom site pages (and asset files). 

Certainly, it fails because regular site folders do not support content types required for updating field values (and thus throw NullReferenceException).

Resolution: I have deleted two site folders /SiteAssets and /SitePages in PWA - I used CSOM, there's no simpler way for it - activated its web-scoped feature "Site Pages" and added a new doclib "SiteAssets" of type "Asset Library".

After that, the provisioning to PWA has succeeded completely.

And as I found in tests, Project Online (POL) works quite well together with Project Portal.
- For example, the sites created by the Project Portal can be easily connected to Projects of POL.
- The standard Project Center of POL can display items from Issues and Risks in its dashboard, various built-in reports, portfolio, etc.

Kind regards,
Paul Borisov

**Comment by tarjeieo** [comment]
Awesome findings Paul! Do you mind sharing a couple of screenshots here for how POL can look together with PP?

As for the technical findings, I think we should be able to resolve them in the release package. Will create tasks for them.

**Comment by PaulBorisov** [comment]
OK, sure. Obviously, I could not make screenshots from the Production. It's under NDA.
Anyway, several screenshots from the development tenant of POL ...

![1_linked_site_of_project_portal_in_project_online](https://user-images.githubusercontent.com/22859478/29842108-82163e66-8d10-11e7-86b5-3fbeb5c744cb.png)
![2_issues_and_risks_on_linked_site_of_project_portal_in_project_online](https://user-images.githubusercontent.com/22859478/29842120-8e8b7846-8d10-11e7-8c36-38c9cfd028a7.png)
![3_issues_and_risks_on_project_portal_site_visible_in_reports_of_project_online](https://user-images.githubusercontent.com/22859478/29842129-94726788-8d10-11e7-8749-25c01645ea7b.png)
