### ISSUE TITLE
One of the risk elements are not showing "etter tiltak". Where has it gone?

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#342]
![image](https://user-images.githubusercontent.com/1837390/29825684-6dc67e48-8cd5-11e7-9a66-ead3e0a1311d.png)

Repro URL (internal): https://pzlcloud.sharepoint.com/sites/ppdemo_v2/nytt-okonomi-ostvest/SitePages/ProjectStatus.aspx

**Comment by olemp** [comment]
Two of them actually, `4` and `3`.

**Comment by olemp** [comment]
Here's the error:

```
Warning: flattenChildren(...): Encountered two children with the same key, `0`. Child keys must be unique; when two children share a key, only the first child will be used.
```

**Comment by olemp** [comment]
Solved the isssue
