### ISSUE TITLE
Ensure that associated visitors, members and owners groups exists before installing root tempalte

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#343]
This will make it easier to install to "unplanned" sites, like e.g. Project Online PWA sites. 

See Integration of the Project Portal with Project Online #340.

**Comment by olemp** [comment]
Added function `Get-HasAssociatedGroups` which `Install.ps1` checks before installing:

```powershell
function Get-HasAssociatedGroups() {
    $ascMemberGroup = Get-PnPGroup -AssociatedMemberGroup -ErrorAction SilentlyContinue
    $ascVisitorGroup = Get-PnPGroup -AssociatedVisitorGroup -ErrorAction SilentlyContinue
    $ascOwnerGroup = Get-PnPGroup -AssociatedOwnerGroup -ErrorAction SilentlyContinue
    return (($ascMemberGroup -ne $null) -and ($ascVisitorGroup -ne $null) -and ($ascOwnerGroup -ne $null))
}
```

**Comment by tarjeieo** [comment]
We need to ensure that the groups exists, not just check it. If they don't exist, they should be created.

**Comment by olemp** [comment]
![image](https://user-images.githubusercontent.com/7606007/31119045-f2d1c2da-a82f-11e7-9c7e-bff9a3b7a26b.png)

**Comment by tarjeieo** [comment]
Like it!
