### ISSUE TITLE
Ensure that SiteAssets and SitePages libraries exists in the target site when applying the root template

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#344]
Should be as simple as ensuring that the two features that provision these two libraries have been activated. We already have a pnp features objects file.

See also Integration of the Project Portal with Project Online #340

**Comment by olemp** [comment]
This is the preffered way to add missing Site Assets library: https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.splistcollection.ensuresiteassetslibrary.aspx

**Comment by tarjeieo** [comment]
That's right, forgot about that one. Will use that in the script (we should do that anyway).
