### ISSUE TITLE
Create a script to sync projects (start and end date) to a top-level task list

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#345]
This will allow using the timeline to visualize

**Comment by olemp** [comment]
I suggest creating a task list at root level, hiding some of the fields, some renaming, and add a JavaScript sync button. Or did you think .ps script?

![345-01](https://user-images.githubusercontent.com/7606007/29869266-9708ce70-8d82-11e7-83b2-309885498e4c.PNG)

**Comment by tarjeieo** [comment]
Thinking .ps1 script. This is for a particular customer. Writing this as we speak.

**Comment by tarjeieo** [comment]
But I doubt it's possible to add them to the timeline automatically!

**Comment by olemp** [comment]
It's quite advanced!

http://www.c-sharpcorner.com/forums/add-new-task-item-to-timeline-using-programmatically-c-sharp

**Comment by tarjeieo** [comment]
Yeah, totally not worth it #spaghetti

**Comment by olemp** [comment]
So this is not something we want in the std. package?

**Comment by tarjeieo** [comment]
![prosjektportalen-prosjektdatoer](https://user-images.githubusercontent.com/1837390/29871027-9242c38e-8d8a-11e7-8105-6ac33408d370.png)
