### ISSUE TITLE
Change default view of gevinstoppfølging-list to group by Gevinst

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#35]
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Summary

Default view should be grouped by gevinst and sorted by log date after that. Also create another available view that can be used for quick edit. This view can be called "Flat visning" and ordered by gevinst, then by date.

**Comment by olemp** [comment]
Issue should be solved in this commit https://github.com/Puzzlepart/pnp-js-provisioning/commit/57729756c3e95b047cd6b1a851a53e345f837d0d
