### ISSUE TITLE
Ikke alle standarddokumenter blir kopiert

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#350]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[X ] SharePoint 2016

#### Summary

Ved opprettelse av et nytt prosjekt blir ikke alle dokumenter kopiert. Hos meg er det konsekvent 1 dokument som mangler. Har 64 dokumenter i en del mapper i standarddokumenter-biblioteket.

#### Version

Please specify what version you are using: [2.1.0]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Forventer at alle dokumentene blir kopiert. 

#### Observed Behavior
Alle utenom ett dokument blir kopiert.

#### Steps to Reproduce
Bruk nokså mange standarddokumenter, og bruk mappestruktur med flere nivåer. Lag et nytt prosjekt og se om alle dokumentene blir kopiert.

**Comment by olemp** [comment]
Should work now
