### ISSUE TITLE
Project calendar doesn't work in IE11 (because of pp.main.js script?)

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#352]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ X] Bug

[ ] Question

#### Environment

[X ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

The calendar page doesn't work in IE11. Navigation, adding events etc., nothing happens. Javascript error in console, see image:
![image](https://user-images.githubusercontent.com/1837390/29919107-4fcc3e36-8e48-11e7-8a21-c8a67796d06d.png)

#### Version

Please specify what version you are using: [ 2.1.0]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
1. Go to the list page /Lists/Mtekalender/calendar.aspx
2. Click the "Møtekalender" link in the left nav again
3. Observe that navigation between months, adding events and more doesn't work,.
4. Obser javascript errror in console: "Objektet støtter ikke egenskapen eller metoden calendar"

**Comment by olemp** [comment]
Can you check if it works now @tarjeieo?

**Comment by tarjeieo** [comment]
Funker nå! Nice 💃
