### ISSUE TITLE
Add color or colored traffic light next to the statuses of risk, budget, time, gevinst and quality in dynamic portfolio

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#36]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

Would be cool if the could add a traffic light with red, yellow or green color next to the statuses in dynamic portfolio. They can always be visible in the dynamic portfolio for these status fields.

**Comment by tarjeieo** [comment]
@olemp - what is supported here in office ui fabric listview? can we render fields like explained?

**Comment by olemp** [comment]
Traffic light is kinda old school, @tarjeieo? I was thinking just colored circles (red, yellow, green) or colored office ui fabric icons.

**Comment by olemp** [comment]
Need your input @tarjeieo

**Comment by tarjeieo** [comment]
Yes, for sure use some nice Office UI icons, as long as we use a nice color scheme I'm not to worried about exactly how it looks. Let's try with the simple 'CircleFill' logo?

Another option could be to use the three emojis, but I think they might convey more that necessary (and perhaps be too 'informal').
