### ISSUE TITLE
Add ribbon button to gevinst-lists for "Next steps", same as the webpart below the list. Will also be available in modern experience

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#37]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Enhancement

[ ] Bug

[ ] Question

### Summary
Since this now looks to be supported, it would be cool if we could add buttons that links to the "next list" in the gevinst-work. This way, users can finish their "endring" work, then move on to "gevinstanalyse" and finally "gevinstoppfølging".

NB: If this isn't solvable in 4 hours, we move it to a later milestone.

**Comment by olemp** [comment]
Moved to milestone 1.1.0

**Comment by olemp** [comment]
Dependent on https://github.com/Puzzlepart/pnp-js-provisioning/issues/3

**Comment by tarjeieo** [comment]
Closed due to complexity and not being requested by customers
