### ISSUE TITLE
Support permission level checking instead of associated groups

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#372]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X ] Enhancement

[ ] Bug

[ ] Question

#### Environment

[ X] SharePoint Online

[ X] SharePoint 2013

[ X] SharePoint 2016

#### Summary
Please summarize the issue.

It's not uncommon to modify the groups in a site, or to add extra groups or add users with direct permissions to the site. The check we use on e.g. the frontpage on wether to show the edit properties link or not should check if the user has full control permissions rather than check exactly which group he is in.

E.g. something like https://social.technet.microsoft.com/Forums/ie/en-US/d7dac39a-1b8c-4f3f-a10d-d6a083a31a94/check-user-permission-level-using-jqueryjavascript?forum=sharepointgeneral

#### Version

Please specify what version you are using: [2.1.0 ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
I've been down that road, and ended up checking groups. We should try to avoid using more JSOM aswell, since it's not supported in the modern experience.

**Comment by tarjeieo** [comment]
If JSOM is the only way, I agree this is no-go.
