### ISSUE TITLE
Siteassets reference 

### ISSUE THREAD

**Issue by IngarMa** [Puzzlepart/prosjektportalen#376]
#### Category

[ ] Enhancement

[X] Bug

[X] Question

#### Environment

[ ] SharePoint Online

[X] SharePoint 2013

[ ] SharePoint 2016

#### Summary

When deploying the new portal to on-prem 2013 environtment, my asset-files seems to get a //siteassets url reference.

#### Version
2.0.3

#### Observed Behavior

![prosjektportal](https://user-images.githubusercontent.com/32195694/30742216-6bb3380a-9f98-11e7-838d-e79bf963e43e.JPG)

#### Steps to Reproduce
Deployment to 2013 environment.

**Comment by olemp** [comment]
Hi there @IngarMa,

Thanks for reporting this.

What parameters were you using when installing? Did you install to the root site collection?

**Comment by IngarMa** [comment]
Hi @olemp,

installed several times, using different parameters, but mostly these two
- Environment SharePointPnPPowerShell2013
- URL 

also, as the former version of prosjektportalen was installed, I tried to use:
-skiptaxonomy
-skipdefaultconfig
-skipassets

Neither one gave me different result, unfortunately.

Installed on a hnsc, and on the root yes.
I've installed on several root-sites, with same result.

Deploying a test in O365 worked as it should though :-)

**Comment by olemp** [comment]
Thanks @IngarMa,

I guess the CSS etc won't load then? I guess we haven't thought of installation to the root site collection. We'll have a look!

**Comment by olemp** [comment]
Hold on @IngarMa. Could you try again with the latest release? The issue should've been solved.

**Comment by IngarMa** [comment]
Hi @olemp 
Downloaded newest version, got this 
- File assets.pnp not found in directory.

Copied this file from a previous installation, but then it stops at 
- taxonomy-1044.pnp missing

Is there any steps i'm missing in the deployment ?

Thanks.

**Comment by olemp** [comment]
@IngarMa Did you download 2.1.3 from here https://github.com/Puzzlepart/prosjektportalen/releases/tag/v2.1.3?

**Comment by IngarMa** [comment]
@olemp With that release, we have lift-off. Everything deployed as it should. Thanks for the help 👍

**Comment by olemp** [comment]
Glad it works @IngarMa 👍
