### ISSUE TITLE
Status column values and their respective colors (green, yellow, red) should be configurable

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#377]
#### Summary

Please summarize the issue.

What about a central list for this as well? You could define field, choicevalue and color.

Not super-important, but something we need to consider to allow people to customize status fields.

**Comment by olemp** [comment]
We should rather use the generic list ProjectConfig. We have a content type with just key and value.

**Comment by olemp** [comment]
The settings at top level using the property bag will be pretty unmanageable with too many settings. So if we want this, it should be some kind of configuration list.

**Comment by tarjeieo** [comment]
I agree @olemp - persisting in prop bag will be messy and hard to extend in this case. 

In any case it will be a little hard to represent this in configuration - because there are a lot of different options, ways to match field with value and again color.

What about solving this super-easy? Just bring the configuration from our ts code into a statusfields.json configuration file that can be overwritten? It's going to be quite seldom the status fields will be configured anyway.
