### ISSUE TITLE
StickyNav is registering active nav item erroneously - wrong item is marked active

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#382]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[ X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Try using the project status nav here: https://pzlcloud.sharepoint.com/sites/ppdemo_v2/nytt-okonomi-ostvest/SitePages/ProjectStatus.aspx

#### Version

Please specify what version you are using: [2.1.0]

**Comment by olemp** [comment]
I can not reproduce this @tarjeieo. Do you have some screenshots?

**Comment by tarjeieo** [comment]
Can't reproduce anymore...
