### ISSUE TITLE
Portalen klarer ikke å opprette øyeblikksbilde fra statusrapport

### ISSUE THREAD

**Issue by lajlal** [Puzzlepart/prosjektportalen#387]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

- Hvilken browser er dette?  Internet Explorer/Google 
- Hva slags loggmeldinger får du i browseren? Ikke satt opp logging på browser
- Skjer det hver gang? Ja
- Kan vi få tilgang for å hjelpe? Ja

#### Version

2.1.1#77c2fbd0

**Comment by olemp** [comment]
Hei @lajlal!

Hvilken versjon av prosjektportalen har dere installert? Det skal du finne nede i venstre hjørnet.

**Comment by lajlal** [comment]
Hei
Jeg sitter hjemme derfor svarer jeg direkte i eposten: 2.1.1#77c2fbd0

Mvh
Lajla

Fra: Ole Martin Pettersen [mailto:notifications@github.com]
Sendt: 28. september 2017 15:17
Til: Puzzlepart/prosjektportalen <prosjektportalen@noreply.github.com>
Kopi: Lajla Irene Lyseggen <LajlaL@skedsmo.kommune.no>; Mention <mention@noreply.github.com>
Emne: Re: [Puzzlepart/prosjektportalen] Portalen klarer ikke å opprette øyeblikksbilde fra statusrapport (#387)


Hei @lajlal<https://hes32-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2flajlal&umid=72353b65-7a11-4ff2-98fc-82da6122648a&auth=5057dc0f09e57df731e81b0c27cac3a3cad720af-078b0c5a71ec08663f2cc2d301326990080ba8ce>!

Hvilken versjon av prosjektportalen har dere installert? Det skal du finne nede i venstre hjørnet.

**Comment by olemp** [comment]
Hei @lajlal, 

Send meg gjerne informasjonen jeg trenger for å få tilgang på epost.

olemp@puzzlepart.com

**Comment by olemp** [comment]
@lajlal  Jeg har nå prøvd på en installasjon med samme versjon som deres, og får ikke reprodusert problemet. 

Jeg fikk tilgang til deres området, og testet på prosjektet du har laget, men jeg har ikke tilstrekkelig tilgang på området (kun besøkende), så jeg får ikke testet. 

Jeg ser det var ett øyeblikksbilde fra 20.09 der. Det har altså fungert tidligere?

**Comment by lajlal** [comment]
Hei

Ja, det går fungert tidligere.

Lajla



Sendt fra min Samsung Galaxy-smarttelefon.


-------- Opprinnelig melding --------
Fra: Ole Martin Pettersen <notifications@github.com>
Dato: 28.09.2017 16:33 (GMT+01:00)
Til: Puzzlepart/prosjektportalen <prosjektportalen@noreply.github.com>
Ko: Lajla Irene Lyseggen <LajlaL@skedsmo.kommune.no>, Mention <mention@noreply.github.com>
Emne: Re: [Puzzlepart/prosjektportalen] Portalen klarer ikke å opprette øyeblikksbilde fra statusrapport (#387)


@lajlal<https://hes32-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2flajlal&umid=6351e8f8-bcc2-4ba6-bc15-c4194bb57d6c&auth=5057dc0f09e57df731e81b0c27cac3a3cad720af-6e6e2a4dc0d24a78c3fa909a1e0acc4656941244> Jeg har nå prøvd på en installasjon med samme versjon som deres, og får ikke reprodusert problemet.

Jeg fikk tilgang til deres området, og testet på prosjektet du har laget, men jeg har ikke tilstrekkelig tilgang på området (kun besøkende), så jeg får ikke testet.

Jeg ser det var ett øyeblikksbilde fra 20.09 der. Det har altså fungert tidligere?

**Comment by lajlal** [comment]
Hei igjen
Jeg har opprettet et nytt prosjekt og for det prosjektet så fungerer øyeblikksbildet så det må være noe med aktuelle prosjektet.

Mvh
Lajla


Fra: Ole Martin Pettersen [mailto:notifications@github.com]
Sendt: torsdag 28. september 2017 16:33
Til: Puzzlepart/prosjektportalen <prosjektportalen@noreply.github.com>
Kopi: Lajla Irene Lyseggen <LajlaL@skedsmo.kommune.no>; Mention <mention@noreply.github.com>
Emne: Re: [Puzzlepart/prosjektportalen] Portalen klarer ikke å opprette øyeblikksbilde fra statusrapport (#387)


@lajlal<https://hes32-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2flajlal&umid=6351e8f8-bcc2-4ba6-bc15-c4194bb57d6c&auth=5057dc0f09e57df731e81b0c27cac3a3cad720af-6e6e2a4dc0d24a78c3fa909a1e0acc4656941244> Jeg har nå prøvd på en installasjon med samme versjon som deres, og får ikke reprodusert problemet.

Jeg fikk tilgang til deres området, og testet på prosjektet du har laget, men jeg har ikke tilstrekkelig tilgang på området (kun besøkende), så jeg får ikke testet.

Jeg ser det var ett øyeblikksbilde fra 20.09 der. Det har altså fungert tidligere?

**Comment by tarjeieo** [comment]
Skulle nesten tro rapport-biblioteket der bildet lagres har fått nytt navn eller er sletta... Men om det fungerer på nye prosjekter så lukker vi saken. Evt. kan vi se kjapt på det i møtet på onsdag.

Kjempesupert at du registrerte issue her på Github Lajla! :)

**Comment by lajlal** [comment]
Hei igjen

Jeg vil gjerne at vi ser på en gang til for ellers må jeg slette prosjektet og lage alt på nytt. Jeg må ha funksjonaliteten .


________________________________
Fra: Tarjei E. Ormestøyl <notifications@github.com>
Sendt: 2. oktober 2017 11:48:37
Til: Puzzlepart/prosjektportalen
Kopi: Lajla Irene Lyseggen; Mention
Emne: Re: [Puzzlepart/prosjektportalen] Portalen klarer ikke å opprette øyeblikksbilde fra statusrapport (#387)


Skulle nesten tro rapport-biblioteket der bildet lagres har fått nytt navn eller er sletta... Men om det fungerer på nye prosjekter så lukker vi saken. Evt. kan vi se kjapt på det i møtet på onsdag.

Kjempesupert at du registrerte issue her på Github Lajla! :)
