### ISSUE TITLE
Gevinstanalyse og gevinstrealiseringsplan 

### ISSUE THREAD

**Issue by PrinsMild** [Puzzlepart/prosjektportalen#391]
#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[X] SharePoint 2016

#### Summary

"Neste steg" på "Gevinstanalyse og gevinstrealiseringsplan" havner i søkeboksen på OnPrem 2016. I Office 365 legges den under listen. 

Stilen #pp-next-step ligger inne i .searchInputBox i OnPrem 2016.

#### Version

Please specify what version you are using: [2.1.3]

Gjelder også i versjon 2.1.0 og 2.1.1.

#### Steps to Reproduce
/Lists/Gevinstanalyse%20og%20gevinstrealiseringsplan/AllItems.aspx

**Comment by olemp** [comment]
Hei @PrinsMild!

Takk for input! Markerer denne som en bug, så ser vi på hvordan dette kan løses på en bedre måte.
