### ISSUE TITLE
Add top-level setting to switch between PDF and PNG export of project status.

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#394]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ X] Enhancement

[ ] Bug

[ ] Question

#### Summary

Please summarize the issue: We have a branch now with PDF-support and PNG-support. Only thing missing is to allow admins to select which format to use for export. This should be controlled at the portfolio level, and should be persisted in the property bag like the other settings. This means that we can set a default value for this as well, which should be PNG-export.

**Comment by olemp** [comment]
Like this?

![image](https://user-images.githubusercontent.com/7606007/31164680-67970040-a8e8-11e7-9dfb-260860d305d9.png)

**Comment by olemp** [comment]
Done
