### ISSUE TITLE
Updated standard elements from prosjektveiviseren.no

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#4]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[x] Enhancement

[ ] Bug

[ ] Question

Update standard elements from prosjektveiviseren.no.

**Comment by tarjeieo** [comment]
Jeg setter denne til milestone 1.1.0 da vi bør involvere Geir mer i dette arbeidet.

**Comment by olemp** [comment]
Tenker vi kan gjenåpne denne når det blir relevant.
