### ISSUE TITLE
Search on the frontpage is case sensitive

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#403]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment

[X ] SharePoint Online

[ X] SharePoint 2013

[X ] SharePoint 2016

#### Summary

When using the live-search on the frontpage, the search is case sensitive. It should ignore casing and match on all lowercase.

#### Version

Please specify what version you are using: [2.1.8]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

**Comment by olemp** [comment]
Good stuff.
