### ISSUE TITLE
Handle duplicate settings options after upgrade

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#409]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ X] Bug

[ ] Question

#### Environment

[X ] SharePoint Online

[X ] SharePoint 2013

[X ] SharePoint 2016

#### Summary

After the latest upgrade, settings are duplicate. This happens because we don't use internalnames for the settings links. We need to change this, but then we also need to handle an upgrade action/script that can clean all the existing settings links...

![image](https://user-images.githubusercontent.com/1837390/31430322-d5039250-ae70-11e7-9f5e-a4058adb53f2.png)

#### Version

Please specify what version you are using: [ 2.1.9]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
We haven't had many downloads of the version before the custom action fix. We should reopen if the issue keeps on coming.

**Comment by tarjeieo** [comment]
Ser denne på hver kunde, må fikses

**Comment by olemp** [comment]
Ok, we could clear web custom actions in the upgrade script, but that would also clear _custom_ custom actions added by the customer.

**Comment by tarjeieo** [comment]
Yep, we need to remember to add a notice in the release notes. Doubt it's gonna be a problem anywhere though.

**Comment by olemp** [comment]
@tarjeieo Proposed solution in https://github.com/Puzzlepart/prosjektportalen/commit/2a0b40029b52e6328d6ad3c2a4434be69c31dee3.

Added `switch` parameter `SkipCustomActionRemoval` to support skipping removal.

Added these lines before upgrade execution:
````powershell
    if (-not $SkipCustomActionRemoval.IsPresent) {
        try {
            Write-Host "Removing existing custom actions.. " -ForegroundColor Green -NoNewLine
            Connect-SharePoint $Url       
            Get-PnPCustomAction -Scope Site | ForEach-Object { Remove-PnPCustomAction -Identity $_.Id -Scope Site -Force }
            Get-PnPCustomAction -Scope Web | ForEach-Object { Remove-PnPCustomAction -Identity $_.Id -Scope Web -Force }
            Write-Host "DONE" -ForegroundColor Green
            Disconnect-PnPOnline
        }
        catch {
            Write-Host
            Write-Host "Error removing existing custom actions from $Url" -ForegroundColor Red 
            Write-Host $error[0] -ForegroundColor Red
            exit 1 
        }
    }
```
