### ISSUE TITLE
SitePages webparts and Navigation is always installed with english language in my env.

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#41]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Environment
[X] SharePoint Online
[ ] SharePoint 2013

#### Summary

Navigation and web parts (and perhaps more) is always installed with english language. 

#### Version

Please specify what version ou are using: [0.9.8 - latest]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Expect norwegian language as the site is in Norwegian (1044)

#### Observed Behavior
Navigation and SitePages/webparts are installed in english

#### Steps to Reproduce
* Uninstall all previous modules
* Run the installation script with the bundled scripts
* Observe that Navigation and SitePages are in english. However, data, fields, content types etc. are in norwegian.

Critical bug as I cannot dev, test or anything in my env.

Let's look at this monday @olemp

**Comment by olemp** [comment]
Can't seem to reproduce @tarjeieo

**Comment by tarjeieo** [comment]
Reason for error: I had no language set in O365, so it chose english language. We need to handle this in a more consistent way if possible. Discussing this a bit and will come back on what to do.

**Comment by olemp** [comment]
@tarjeieo Update the installation documentation.

**Comment by tarjeieo** [comment]
Will either
1. ) Update documentation, or
2. ) Handle this differently based on feedback from peers and PnP-guys.

**Comment by tarjeieo** [comment]
Weird, Erwin says it's supposed to work like we want. If the web language is 1044 it should pick 1044.....

**Comment by olemp** [comment]
Something wrong with your tenant @tarjeieo?

**Comment by olemp** [comment]
I guess we can't do anything before 1.0.0 @tarjeieo?

**Comment by tarjeieo** [comment]
Current solution is to ignore english resx file... Don't need to solve this until the first version with english support
