### ISSUE TITLE
Open risk elements from the risk matrix and risk list in the status report in modal dialog

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#42]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ X] Enhancement

[ ] Bug

[ ] Question

#### Environment
[ ] SharePoint Online
[ ] SharePoint 2013

#### Summary
If this is hard or conveluted, we push this to a later version.

**Comment by olemp** [comment]
Done!

Reference: https://www.codeproject.com/Tips/1109352/SharePoint-Modal-Dialog-Position-and-Scrolling-Iss
