### ISSUE TITLE
Announcement on project level?

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#426]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ ] Bug

[X ] Question

#### Environment

[ X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Announcement not visible on Project level.

#### Version

Please specify what version you are using: [v2.1.13.ea1c1958 ]

#### Expected / Desired Behavior / Question
It would be nice to have the announcement available also on the projects.
(The subsites)

**Comment by olemp** [comment]
@jahali Have you tried adding the webpart `Kunngjøringer` from web part gallery?

See attached screenshot:

![image](https://user-images.githubusercontent.com/7606007/32042017-8ca45090-ba36-11e7-868e-eeef3eee7352.png)

**Comment by jahali** [comment]
Thx :-)

adding the webpart solved it.

Do you have available an overview of the different webparts?
and perhaps even on the different configuration elements like the one 
"ShowOnFrontpage" that is available on the phasedefinition in Termstore?

**Comment by olemp** [comment]
We don't have documentation for this at the moment, but you can see them in the screenshot above.

**Comment by jahali** [comment]
OK, thanks
