### ISSUE TITLE
Additional list to be created during creating of project

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#427]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ ] Bug

[X ] Question

#### Environment

[ X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary
Possibility to define a new list (total different) and include this in the creation of the project?

#### Version

Please specify what version you are using: [v2.1.13.ea1c1958 ]

#### Expected / Desired Behavior / Question
The functionality to include different items into already defined lists like "Phase checklist", "task", "Stakeholders" is working fine.
But what about other custom made lists?
Is it possible to define a total different list and include this in the creation of the project?

**Comment by olemp** [comment]
Under `Site Settings` you'll find `Prosjektportalen - Utvidelser`. A library where you can upload .txt files.

A sample extension for a new list would be e.g.:

```json
{
    "Lists": [
        {
            "Title": "Project Team",
            "Description": "",
            "Template": 105,
            "Views": [
                {
                    "Title": "All contacts",
                    "ViewFields": [
                        "LinkTitle",
                        "FirstName",
                        "CellPhone",
                        "Company",
                        "Email"
                    ],
                    "AdditionalSettings": {
                        "RowLimit": 30,
                        "Paged": true,
                        "ViewQuery": "<GroupBy Collapse=\"TRUE\" GroupLimit=\"30\"><FieldRef Name=\"Company\" /></GroupBy><OrderBy><FieldRef Name=\"Title\" /><FieldRef Name=\"FirstName\" /></OrderBy>"
                    }
                }
            ]
        }
    ]
}
```

This would create a new contacts list `Project Team`.

**Comment by jahali** [comment]
Hi,

Thats great :-)
 
How can we control the settings for each column in this new list?

**Comment by olemp** [comment]
Use a content type through `ContentTypeBindings`.

E.g. (if your content type's ID is 0x0100B384774BA4EBB842A5E402EBF4707367)

```json
{
  "Lists": [
    {
      "Title": "Project Team",
      "Description": "",
      "Template": 105,
      "ContentTypeBindings": [
        {
          "ContentTypeID": "0x0100B384774BA4EBB842A5E402EBF4707367"
        }
      ],
      "Views": [
        {
          "Title": "All contacts",
          "ViewFields": [
            "LinkTitle",
            "FirstName",
            "CellPhone",
            "Company",
            "Email"
          ],
          "AdditionalSettings": {
            "RowLimit": 30,
            "Paged": true,
            "ViewQuery": "<GroupBy Collapse=\"TRUE\" GroupLimit=\"30\"><FieldRef Name=\"Company\" /></GroupBy><OrderBy><FieldRef Name=\"Title\" /><FieldRef Name=\"FirstName\" /></OrderBy>"
          }
        }
      ]
    }
  ]
}
````

**Comment by jahali** [comment]
Hi again,

Is it possible to add an entry in the navigation menu for these new items as well?
