### ISSUE TITLE
Add custom site pages

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#428]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ ] Bug

[X ] Question

#### Environment

[X ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Project Portal pages designed for different "knowledge areas"

#### Version

Please specify what version you are using: [v2.1.13.ea1c1958 ]

#### Expected / Desired Behavior / Question
Is it possible to include extra sites pages designed as "work pages" for different knowledge areas in the solution?
Thinking about pages for:
- Risk, where we have different elements like "top10 risk", "risk grouped by responsible", "risk matrix"
- Planning, with elements like "stakeholders", communication plan", "planing documents" an so on.

**Comment by olemp** [comment]
Project or portfolio level, @jahali?

**Comment by jahali** [comment]
Project level

**Comment by olemp** [comment]
Yes, you can using extension files like in https://github.com/Puzzlepart/prosjektportalen/issues/427.

This is the project frontpage: https://github.com/Puzzlepart/prosjektportalen/blob/master/src/js/Provision/Template/Objects/Files/ProjectHome.ts

The format must be JSON, and file extension .txt like in https://github.com/Puzzlepart/prosjektportalen/issues/427.

**Comment by jahali** [comment]
Hi,

With just a copy of the original Project Home and the Navigation .txt files, changed minimal, the import failes.
In the Log the following is listed:
![2017-11-05 16_29_44-log - all items](https://user-images.githubusercontent.com/33092566/32416238-9a1f08ce-c246-11e7-91af-adcfecf8025f.png)

**Comment by jahali** [comment]
Hi,
I need to reopen this case and get some more background info regarding creation of completely new pages.
Not just updates of existing pages
