### ISSUE TITLE
Prosjektstatus page not working correctly after upgrade

### ISSUE THREAD

**Issue by marlowandre** [Puzzlepart/prosjektportalen#429]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Upgraded from version 2.0.3 to  2.1.13. After the upgrade the "prosjektstatus"-page isn't showing status information, only a message saying "Det er ikke fyllt ut verdier for noen av statusfeltene". I checked the status properties of the project, and they are filled in.

While upgrading I noticed the script (Upgrade.ps1) wasn't able to get the CurrentVersion, it was just blank.

Noticed from the upgrade log that the upgrade created some new content types.
I did another upgrade from version 2.1.8 to 2.1.13. Here the Project-status page works as intended. In this upgrade it looks like no additional content types were created, so I'm thinking the issue has something to do with this.

#### Version

Please specify what version you are using: [ 2.0.3 -> 2.1.13 ]

#### Expected / Desired Behavior / Question

Expect the Projectstatus-page to show a status summary

#### Observed Behavior

No status summary showing in the Projectstatus-page, only a message saying "Det er ikke fyllt ut verdier for noen av statusfeltene"

#### Steps to Reproduce

Have some projects created with filled in statuses in version 2.0.3 and then do an upgrade to 2.1.13.

**Comment by olemp** [comment]
@marlowandre thank you for reporting this. Will do a fresh install of `2.0.3` and attempt an upgrade.

**Comment by olemp** [comment]
@marlowandre I can reproduce the version parsing issue. This was resolved in https://github.com/Puzzlepart/prosjektportalen/commit/268fa84f9011a6437413b9a5a0312c35c805fa29.

I think that because the Upgrade script wasn't able to paerse the version the upgrade package `StatusSections-1044.pnp` in `@upgrade\2.0_2.1\1044` was skipped.

Could you try to manually apply this template?

**Comment by olemp** [comment]
I updated the 2.1.13 release https://github.com/Puzzlepart/prosjektportalen/releases/tag/v2.1.13

**Comment by marlowandre** [comment]
Ran the StatusSections-1044.pnp template manually. It's now working as expected.

Thanks!
