### ISSUE TITLE
Code extension

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#431]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ ] Bug

[X ] Question

#### Environment

[X ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

How to plug in extension to the existing code

#### Version

Please specify what version you are using: [v2.1.13.ea1c1958 ]

#### Expected / Desired Behavior / Question

We would like to make an extension to ProjectPortal where we make additional code for the Phase webpart.
As we understand this can be "referenced" and by this way included in our solution if we just extend the correct file.
Could you please give us directions to which file this is an maybe an example of how we code this.

We would make both a "webpart" and code to this.

**Comment by tarjeieo** [comment]
Closing this after discussing this off-github. Also, this is not really Project portal specific (how to run additional javascript code).
