### ISSUE TITLE
Typo in a list in the project: Gevinstsoppfølging

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#437]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

##### Summary

Det er en typo i listen og venstremenyen for "Gevinstsoppfølging". Dette burde rettes. Her må vi huske på at dette ikke vil endres for eksisterende prosjektlister. Vi må derfor støtte både listenavn med typo og med typo fikset.

**Comment by tarjeieo** [comment]
Det er greit å fikse dette kun i venstremenyen - siden det har store komplikasjoner å endre listenavnet.

**Comment by olemp** [comment]
Resource `Lists_BenefitsFollowup_Title` is used in both Navigation and Lists handlers, so not really what to do here.

Almost leaning towards a "clean-up" script..

**Comment by olemp** [comment]
Fixed the typo in navigation. Closing.
