### ISSUE TITLE
Change permission needed to show the new project webpart

### ISSUE THREAD

**Issue by arstad** [Puzzlepart/prosjektportalen#438]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Is it possible to change the permission required for the new project webpart to be visible to manageSubwebs instead of manageWeb? We want to enable project creation for multiple users and do not want to give every one full control of the main site.

#### Version

Please specify what version you are using: [ 2.1.13.ea1c1958 ]

#### Expected / Desired Behavior / Question
Create a new webpart or change to the following in this file INewProjectLinkProps.ts:
export const NewProjectLinkDefaultProps: Partial<INewProjectLinkProps> = {
    linkText: RESOURCE_MANAGER.getResource("NewProjectForm_Header"),
    iconProps: { iconName: "CirclePlus" },
    permissionKind: PermissionKind.manageSubwebs,
    dlgHeaderText: RESOURCE_MANAGER.getResource("NewProjectForm_Title"),
    dlgSubHeaderText: RESOURCE_MANAGER.getResource("NewProjectForm_SubText"),
    creationModalTitle: RESOURCE_MANAGER.getResource("CreationModal_Title"),
};

**Comment by olemp** [comment]
Hei @arstad,

Du kan endre på innholdet på script-webdelen.

Standard skal det være:

```html
<div id='pp-newprojectlink'></div>
```

Om du endrer til 
```html
<div id='pp-newprojectlink' data-props='{"permissionKind":24}'></div>
```

Dette skal fungee 🌮

**Comment by arstad** [comment]
Takk for kjapt svar, det fungerte som ønsket å legge inn den kodesnutten :hamburger:
