### ISSUE TITLE
Add expand/collapse button for project metadata that persists in localstorage for a given project

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#44]
#### Category
[X] Enhancement

[ ] Bug

[ ] Question

If project metadata is collapsed, it should be collapsed in that project in the future as well. Persist with localstorage or similar.

**Comment by olemp** [comment]
The best solution here is to have ChromeTile `None` for the webpart, and let the component take care of rendering the Chrome.

**Comment by olemp** [comment]
Done!
