### ISSUE TITLE
Error on "porteføljeoversikt"

### ISSUE THREAD

**Issue by pzlespen** [Puzzlepart/prosjektportalen#441]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x ] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[x ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

When navigating to "Porteføljeoversikt", you get the error: 
Error making HttpClient request in queryable: [400] Bad request. 

See attachments.
![image](https://user-images.githubusercontent.com/24522890/33007723-579566c0-cdd0-11e7-9999-59195699aedf.png)
![image](https://user-images.githubusercontent.com/24522890/33007731-60553d08-cdd0-11e7-8ba2-13cf3ad8c478.png)

#### Version

Please specify what version you are using: [2.1.17]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by tarjeieo** [comment]
Feltet "Grupper etter" aka. GtDpGroupByLookup  ligger ikke på lista - det burde ha blitt lagt til ved en upgrade. Litt usikker på hvorfor dette har skjedd....

**Comment by pzlespen** [comment]
Løste seg med oppgradering til 2.1.18
