### ISSUE TITLE
Allow different project types in the new project selector

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#448]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ X] Enhancement

[ ] Bug

[ ] Question

#### Summary

The project portal architecture yields various site collection per "project type" - to allow different project fields, standard data, configs etc.  - We will continue with this approach. A request often surfacing when creating various templates is "How do we create different types of projects?". Today, the answer is to go to the root of each project portal site collection.

We should allow a configuration list in the project portal where users can specify project portals as different project types (Title and URL). IF such project protals are specified, the user can choose among those types from a dropdown. We will use the default options for "standard date" for the first phase (unless it's easy to retrieve the standard data configuration options after changing the type?). If no project type element is added, the experience should be just like today.

**Comment by olemp** [comment]
Might require changes to `sp-pnp-provisioning` due to token replacing, which is not a good thing...

**Comment by tarjeieo** [comment]
What's the status here @olemp ?

**Comment by olemp** [comment]
Closed due to the complexity of the change 🍔
