### ISSUE TITLE
Feil i risikokart

### ISSUE THREAD

**Issue by joachimgje** [Puzzlepart/prosjektportalen#452]
#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[X] SharePoint 2013

[ ] SharePoint 2016

#### Summary
Som du ser på skjermbilde under burde vel f. eks skulle vært ID 9 vært vist som gjennomsiktig i ruten med «høy» og «alvorlig»? 

https://k3.kristiansand.kommune.no/programledelsen/SitePages/ProjectStatus.aspx

Dette er reprodusert på https://pzlcloud.sharepoint.com/sites/ppdemo_v2/test-krk/SitePages/ProjectStatus.aspx i tilfelle dere vil gjøre noe testing.

![image](https://user-images.githubusercontent.com/22074910/33427400-721fc1e6-d5c5-11e7-81f6-3f2d37d36052.png)

#### Version

Please specify what version you are using: [2.1.19]

**Comment by olemp** [comment]
@joachimgje Får ikke eprodusert på https://pzlcloud.sharepoint.com/sites/ppdemo_v2/test-krk/SitePages/ProjectStatus.aspx. Ser ut som det fungerer her?

![image](https://user-images.githubusercontent.com/7606007/33433555-4db56b50-d5dc-11e7-9a90-cd94dfe5662f.png)

**Comment by olemp** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen/commit/5d4743c29561500a9527ab5ab157a16df9ee96a2 og blir med i `2.2.0`.
