### ISSUE TITLE
Repeating phases

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#457]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ ] Bug

[ X] Question

#### Environment

[X ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Repeating phases

#### Version

Please specify what version you are using: [2.1.20 ]

#### Expected / Desired Behavior / Question

How to configure repeating phases

#### Observed Behavior
Can't find the place where this is configured

**Comment by olemp** [comment]
Will add here: https://github.com/Puzzlepart/prosjektportalen/wiki/How-to-configure-the-phase-term-set

You set the property `IsIncremental` to `true`.

**Comment by olemp** [comment]
Guide updated: https://github.com/Puzzlepart/prosjektportalen/wiki/How-to-configure-the-phase-term-set
