### ISSUE TITLE
Lessons Log on Portfolio level

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#458]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment

[ X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ X] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Lessons log contains items from "all over the place"

#### Version

Please specify what version you are using: [ 2.1.20 ]

#### Expected / Desired Behavior / Question

We want the Lessons Log on Portfolio Level to only contain items from the Prosjektportalen Site Collection. 
After upgrading to 2.1.20 we assumed that this should be fixed?

#### Observed Behavior
In our previous version we found that the Lessons Log on Portfolio level contains items from outside the Prosjektportalen site collection. This is also the reality after the upgrade to 2.1.20.

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by tarjeieo** [comment]
Sorry, should have made it to 2.1.20. Fixed now, will be part of next release.
