### ISSUE TITLE
Copying default documents not working during creation of new project

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#459]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Please summarize the issue.

During provisioning, no documents are being copied. 100 folders are successfully being copied, but documents are not. Shouldn't be any customizations here (AFAIK). See link and creds in internal slack.

#### Version

Please specify what version you are using: [2.1.20]

**Comment by olemp** [comment]
Solved by setting top to 500. Will include in `2.1.21`.
