### ISSUE TITLE
Inkluder fase for mapper i "Standarddokumenter"

### ISSUE THREAD

**Issue by oleostlid** [Puzzlepart/prosjektportalen#462]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[x] Enhancement

[ ] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[x ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Fase i mappestruktur fra "Standarddokumenter" mangler når man oppretter nytt prosjekt.

#### Version

Please specify what version you are using: [2.1.21]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question

Når man oppretter nytt prosjekt så blir mappestrukturen i "Standarddokumenter" opprettet med faser som etablert i "Områdeinnhold" i "Porteføljeområdet".

#### Observed Behavior

Nå blir mappestrukturen etablert uten definerte faser. Da blir mapper og dokumenter (også dokumenter med relevant fase) skjult i Prosjektområdets forside. Man må da bruke "dokumenter" i menyen til venstre for å finne frem mappestrukturen.

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by tarjeieo** [comment]
Thanks for reporting! It's possible to set phase for document folders when in list quick edit at root level. The requested feature is that the metadata phase for folders is persisted when copying standarddocuments to a new project.

This is currently not supported, and will have to be implemented. This is not a critical feature, and we have problems with prioritizing this feature now. Will leave this for a little while and see if more people request this functionality.

**Comment by olemp** [comment]
Metadata will only be included for office documents, not folders and PDFs (or other document types).
