### ISSUE TITLE
Quick Links webpart on the front page should be more customizable

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#463]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X ] Enhancement

[ ] Bug

[ ] Question

#### Summary

The quick links web part on the front page is currently showing maximum 5 elements. Preferably this web part should be more configurable. As a minimum increase to 10 items. Consider rewrite to list web part with jslink. Requested by customer.

#### Version

Please specify what version you are using: [All]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

**Comment by olemp** [comment]
No, let's not consider a rewrite to jslink 💇‍♂️
