### ISSUE TITLE
What is the intended use og CustomProperty "PhaseLevel"?

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#464]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ X] Question

#### Environment

[X ] SharePoint Online

#### Browser

[X ] Chrome

#### Summary

What is the CustomProperty "PheseLevel" for?

#### Version

Please specify what version you are using: [ 2.1.20]

#### Expected / Desired Behavior / Question
In the Wiki documentation for configuring phases, the CustomProperty "PhaseLevel" is indicated to be used (or at least added). But what is this for?
It seems to have the Options [Project] and [Portfolio]

#### Steps to Reproduce
![image](https://user-images.githubusercontent.com/33092566/33925106-108146e4-dfd9-11e7-8474-2f174055ffca.png)

**Comment by tarjeieo** [comment]
Hi,

Thanks for asking. At the moment, this property is only used for "branding" of the phase web part. Level=Project will make it green with a double line. Level=Portfolio will have single line and blue. Might use this for additional functionality at a later point in time.

-Tarjei
