### ISSUE TITLE
Issues with permission checking on-prem. Checking for permission level creates login prompt for (some) non-owners 

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#465]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[X ] SharePoint 2016

#### Browser

[X ] Chrome

[X ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

On the front page and (for some reason) on the portfolio page, some non-owners are getting new login prompts. This is caused by the "New project" web part. 

In the network tab, the request to /_api/web/getUserEffectivePermissions is the request that triggers the login prompt. 

From the code, I see we are using sp-pnp-js's way to handle permission checking, and this again uses the REST API. I think we should attempt to use Jsom here as well to avoid this issue.

A complication with this issue is that we cannot reproduce with a user we have access to that has the exact same permissions as another user that gets the login prompt every time.

#### Version

Please specify what version you are using: [2.1.18 ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
Merged to dev.
