### ISSUE TITLE
Status field configuration file not found when using assets

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#466]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ X] Bug

[ ] Question

#### Environment

[ X] SharePoint Online

[X ] SharePoint 2013

[ X] SharePoint 2016

#### Browser

[ ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

The code for grabbing the configuration file for status-fields colors does not seem to take into account the use of a central repository for these types of files.

From file \src\js\Util\index.ts. Looks to be always siteServerRelativeUrl. Is there an easy way to get cdn url @olemp ?

```
/**
 * Loads JSON configuration
 *
 * @param {string} name Config name
 */
export async function loadJsonConfiguration<T>(name: string): Promise<T> {
    const fileServerRelativeUrl = `${_spPageContextInfo.siteServerRelativeUrl}/SiteAssets/pp/config/${name}.txt`;
    try {
        const json = await pnp.sp.site.rootWeb.getFileByServerRelativeUrl(fileServerRelativeUrl).usingCaching().getJSON();
        return json;
    } catch (err) {
        Logger.write(`[loadJsonConfiguration] Failed to load JSON from ${fileServerRelativeUrl}`, LogLevel.Error);
        return null;
    }
}
```
#### Version

Please specify what version you are using: [2.1.21++ ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
Get assets site url from web property bag @tarjeieo

**Comment by tarjeieo** [comment]
My bad. This issue is not fixed.

**Comment by tarjeieo** [comment]
Nevermind.
