### ISSUE TITLE
Create a settings option for inheriting permissions instead of unique permissions per project

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#470]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X ] Enhancement

[ ] Bug

[ ] Question

#### Summary

In some cases one would like to have the same permissions in all projects, instead of using unique permissions. Can we have a project portal site collection setting that can toggle this option?

If this setting is set, all new projects should automatically inherit permissions from top level.

**Comment by olemp** [comment]
Created setting `PROJECT_INHERIT_PERMISSIONS` with choices `On` and `Off`.
