### ISSUE TITLE
Minor color-change in the risk matrix

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#472]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[X] Bug

[ ] Question

#### Summary

Fargen i den ruta som har elementene 6, 16, 19 og 20 skal være oransje, ikke rød. 

![riskmatrixcolors](https://user-images.githubusercontent.com/1837390/34762289-8d867974-f5e7-11e7-8339-ef4412ef789d.png)

**Comment by olemp** [comment]
@tarjeieo Hvilke verdier har 6, 16, 19 og 20 satt for Konsekvens og Sannsynlighet?

**Comment by tarjeieo** [comment]
Se bildet. Moderat og Middels.

**Comment by olemp** [comment]
Tenkte tallverdiene. Fant ut av det. 🌮

**Comment by olemp** [comment]
Dette er da riktig, @tarjeieo?

![image](https://user-images.githubusercontent.com/7606007/34769031-e32ef4b8-f5fc-11e7-8910-8542043bf5fb.png)

**Comment by tarjeieo** [comment]
Utsøkt! 👍
