### ISSUE TITLE
In DynamicPortfolio, indicate expand/collapse functionality with arrows

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#474]
#### Category

[x] Enhancement

[ ] Bug

[ ] Question

**Comment by olemp** [comment]
Proposed solution:

![image](https://user-images.githubusercontent.com/7606007/34877691-5b814a64-f7a7-11e7-9274-71c7ae1f1821.png)
![image](https://user-images.githubusercontent.com/7606007/34877702-663a22d2-f7a7-11e7-84cf-0dc1c8f78c73.png)

**Comment by olemp** [comment]
PR: https://github.com/Puzzlepart/prosjektportalen/pull/475

**Comment by tarjeieo** [comment]
This is nice! Go ahead and merge @olemp 👍
