### ISSUE TITLE
Projects disappearing from Portfolio

### ISSUE THREAD

**Issue by marlowandre** [Puzzlepart/prosjektportalen#476]
#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Some projects disappear from the portfolio. Unclear why this happens.

#### Version

Please specify what version you are using: [2.1.3 ]
This also happened in 2.0.3. We did an upgrade to the latest version then (2.1.3) to see if that fixed the issue.

#### Expected / Desired Behavior / Question

Expect the projects to remain on the portfolio page

#### Observed Behavior
A total of 3 projects have disappeared from the portfolio page. For some reason they are no longer included in the "Prosjektområde"-search result type. Also tested this using built-in search web parts with the same result. 

#### Steps to Reproduce
Not sure how to reproduce it. Seems to happen after the project metadata have been edited (by clicking "Edit preferences" on the project home page).

We can bring the project back into the result type by changing the content type for ProjectHome.aspx to something else, and then back to "Prosjektforside". When this is done the project "pops" back into the result type.

**Comment by olemp** [comment]
@marlowandre Not really sure what might be causing this.. Have you checked the version history for changes in content type? It should be visible on the frontpage as long as the content type for the welcome page is "Prosjektforside".

**Comment by marlowandre** [comment]
@olemp Yes, checked the version history, but could not really find anything happening to the content type. I'll add an attachment of the version history of one of the projects that disapeared.
![versionhistory](https://user-images.githubusercontent.com/29536394/35036445-ab9d3d52-fb74-11e7-936f-541e1967da7c.png)

I was notified that this project was missing January 14th. Version 13 and 14 is me changing the content type to "Områdeside" and back to "Prosjektforside" to fix the issue for this project.

**Comment by tarjeieo** [comment]
Any updates here @marlowandre? Do you still have the issue?

**Comment by marlowandre** [comment]
Still an issue. Has happened at least once that I know of since I added this issue. The fix was still to change the content type to "Områdeside" and back to "Prosjektforside"

**Comment by tarjeieo** [comment]
This is related to the search index in SharePoint, and is the same issue as #498. The fix is to trigger a new crawl of the "missing" site. If that doesn't help, the next step is a service request to microsoft support. 

Closing this as a non-related Prosjektportalen issue. If I'm wrong I owe you a beer. ;-)
