### ISSUE TITLE
Translate Dice-functionality to norwegian

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#478]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

The dice-functionality (baked into PP and exposed via Puzzlepart/prosjektportalen-dice) is in english. We should create a norwegian translation for norwegian versions of PP. In other words, we should use resource-files for the terms.

# Translations provided by customer

English | Norsk
-- | --
Duration | Varighet mellom beslutningspunkter
Team Performance Integrity | Prosjektgruppens integritet og ytelse
Commitment – senior mng | Støtte fra prosjekteier
Commitment – local | Støtte fra gevinsteier
Effort | Behov for ekstrainnsats

## Oversettelse commitment – senior mng

English | Norsk
-- | --
Cleary, strong communicate need | Champion
Seem to want success | Synes å ønske suksess
Neutral | Nøytral
Relucant | Motvillig

## Oversettelse commitment – local

English | Norsk
-- | --
Eager | Ivrig
Willing | Positiv
Reluctant | Motvillig
Strongly reluctant | Sterkt motvillig

## Oversettelse effort

English | Norsk
-- | --
< X % additional | < X % ekstrainnsats

**Comment by olemp** [comment]
Missing norwegian translation for _Reasonably communicate need_ @tarjeieo

**Comment by tarjeieo** [comment]
@olemp Something wrong with the table. Removed the option. See also https://en.wikipedia.org/wiki/DICE_framework
