### ISSUE TITLE
Ability to include more metadata for Standard Tasks when creating a new project

### ISSUE THREAD

**Issue by marlowandre** [Puzzlepart/prosjektportalen#480]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[x] Enhancement

[ ] Bug

[ ] Question

#### Summary

When creating a new project, only certain metadata for Standard Tasks (Standardoppgaver) is copied. This might be by design, but the request is to be able to include more metadata, for example Previous tasks, Start Date, End date.

#### Version

Please specify what version you are using: [2.1.22]

**Comment by olemp** [comment]
You can configure that yourself.

Go to Site Settings and find `Prosjektportalen - Listeinnhold` (or the english translation if you're using the english version).

In this list you'll find an element with title `Inkluder standardoppgaver`. Click edit and you find the field called `Felter`. This is a comma-separated list of field internal names. Add whatever you like there 🌮 

Hope that helps!

**Comment by marlowandre** [comment]
This is exactly what I'm looking for :)

It doesn't seem to work however. Added the columns I wanted and did a couple of tests. Only `Oppgavenavn` and `Fase` seems to be copied still.

This is how the `Felter` for `Inkluder standardoppgaver` looks like:
![image](https://user-images.githubusercontent.com/29536394/35153141-8cc71724-fd25-11e7-9670-3814a84e2905.png)

**Comment by olemp** [comment]
What is the `Assign` field?

**Comment by marlowandre** [comment]
Sorry, the field didn't show all the content, it is AssignedTo

Here's another snip of the entire configuration for `Inkluder standardoppgaver`
![image](https://user-images.githubusercontent.com/29536394/35153495-093cc244-fd27-11e7-816a-9f0c3ff5737f.png)

**Comment by olemp** [comment]
Ahh, not sure all field types are currently supported. Will have to check the code when I have time 🔨

**Comment by olemp** [comment]
Added support for the following field types:

Text":
Note":
Choice":
* MultiChoice
* Number
* User
* UserMulti
* Boolean
* Currency
* TaxonomyFieldType
* TaxonomyFieldTypeMulti
* URL
* DateTime

Will be included in the next release.
