### ISSUE TITLE
Lesson log content is wrong

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#481]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ X] Bug

#### Environment

[X ] SharePoint Online

#### Browser

[X ] Chrome

#### Summary

Lessons log on portofolio site shows items from outside of Prosjektportalen.

#### Version

Please specify what version you are using: [ 2.1.20]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
The list should only contain items from subsites, not items from outside the Prosjektportalen

**Comment by tarjeieo** [comment]
This should be resolved in the (shortly) upcoming release
