### ISSUE TITLE
Saving project snapshot doesn't work after the recent upgrade

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#489]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[x] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Taking a project snapshot doesn't work after the recent upgrade. (png-mode)
![image](https://user-images.githubusercontent.com/1837390/35735067-9b7f3ec8-0823-11e8-8944-8bec29722642.png)

#### Version

Please specify what version you are using: [2.1.24 ]

**Comment by olemp** [comment]
It failed due to a major change in `html2canvas`.

`html2canvas` now returns a ES6 Promise.
