### ISSUE TITLE
Support full template overrides of project sites

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#490]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

In some cases we want to create project sites with completely different content. This can be lighter templates, templates with a different function etc... It would be nice to still be able to use the "PP framework" for portfolio, metadata, tagging, default data etc., while being able to create a completely different template.

This is somewhat achievable with extensions files, but the provisioning can take really long time, especially in SharePoint online, since the default template contains a lot of data. 

We suggest to create a new library for templates, where we will provision the default template and a lighter one. One of the templates needs to be marked active.

With this solution, enabling people to pick a template on provisioning should also be easily achieved, if this is where we want to go.

The list should have the following fields
- Name
- Title
- Active (if we want to support template-picking) (boolean)
- Default (boolean)

**Comment by olemp** [comment]
Implemented
