### ISSUE TITLE
The column 'Til prosjektstyre'/'To project meeting(?)' is not available in new projects

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#496]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

The column is not visible in the form (classic). It's not added to the list 'Project log'. 

From the code, I can't see that it's being added to the list anywhere? Internal name: GtProjectLogEventLookup

#### Version

Please specify what version you are using: [ 2.1.50]

**Comment by olemp** [comment]
What list?

**Comment by tarjeieo** [comment]
Project log

**Comment by olemp** [comment]
I think this was due to issue with GtProjectEventDateAndTitle that was never resolved due to calculcated column issue. We can re-add the field with ShowField 'Title'.

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen/issues/191

**Comment by tarjeieo** [comment]
Aha! So we probably removed it because of that and never took it back... 

Can we have this feature in the 1044 version (that should work) but use just title field for the 1033 version? Guess we need to use resource files then...

**Comment by olemp** [comment]
The issue is when we add the calculated field `GtProjectEventDateAndTitle` to the meeting calendar. Conditionally adding the field based on language is not so nice... 👎

**Comment by olemp** [comment]
@tarjeieo Anything we should do here? Close?

**Comment by tarjeieo** [comment]
Just an idea; What about using a resx label for the ShowField-property? Then we can use ShowField="Title" for 1033 and ShowField="GtProjectEventDateAndTitle" for 1044.

**Comment by tarjeieo** [comment]
I see. Well, not much more to do here then. Think we've put in enough effort...
