### ISSUE TITLE
Project tiles not showing on new projects after upgrade

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#498]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ X] Bug

#### Environment

[X ] SharePoint Online

#### Browser

[X ] Chrome

#### Summary

Project tiles of new projects not showing on "Portfolio Site" level

#### Version

Please specify what version you are using: [ v2.1.60.4dea91b3]

#### Expected / Desired Behavior / Question
New projects should appear on Portfolio Site after they are created

#### Observed Behavior
The projects are not showing as tiles, but they appear in the recent list on the right side of the screen,

#### Steps to Reproduce
Happens on every project creation, in both our installations

**Comment by tarjeieo** [comment]
Extremely weird, and it's not just delay related to search indexing? Need to have a closer look in the environment to debug.

**Comment by jahali** [comment]
Hi,
We checked a little bit around the search indexing, and found that this was halting.
Microsoft helped us to get this back up, and the problem is now solved.

The case can be closed.

**Comment by tarjeieo** [comment]
Good to hear 👍
