### ISSUE TITLE
New extension fails to finish during project creation 

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#499]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ X] Question

#### Environment

[ X] SharePoint Online

#### Browser

[X ] Chrome

#### Summary

We have made a custom Content Type, and tries to add a new list as extension based this content type.
The project creator loops on this exact extension, and never finish.

#### Version

Please specify what version you are using: [ v2.1.60.4dea91b3]

#### Expected / Desired Behavior / Question
Expected this list to be created. Based on the Content Type and Extension

Print screen of Content Type is attached.
The Extension file is also attached.
[Control Plan - Copy.txt](https://github.com/Puzzlepart/prosjektportalen/files/1748080/Control.Plan.-.Copy.txt)
![image](https://user-images.githubusercontent.com/33092566/36541804-61bdd50c-17df-11e8-9dd3-78e810e1e323.png)

#### Observed Behavior
Project creator loops on this extension.

#### Steps to Reproduce
Happens on every project created with this extension enabled

**Comment by tarjeieo** [comment]
I've compared the file with a working one, and I can't see any errors. My guess without looking in your environment is that the internal names of the fields are wrong. But I guess you've double checked this?

**Comment by jahali** [comment]
This have been checked twice or even more,

but still there was a slightly different typing in my script.


After I localized and repaired one upper/lower case issue the project was generated as planned.


This issue is OK




Best regards,
Jan Lindset
Head of IT Applications
_______________________________________________
Goodtech AS
Visiting address: Innspurten 15 0663 Oslo
Postal address: P.O. Box 6578 Etterstad, NO-0607 Oslo
Phone: +47 926 06 428
E-mail: jan.lindset@goodtech.no<mailto:jan.lindset@goodtech.no>
www.goodtech.no<http://www.goodtech.no>

[https://i.xink.io/Images/Get/L341/i]

the preferred choice for industrial efficiency



________________________________

**Comment by tarjeieo** [comment]
PEBMAC ;-)
