### ISSUE TITLE
Add an extra content type to Project Deliveries

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#500]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X ] Question

#### Environment

[X ] SharePoint Online

#### Browser

[X ] Chrome

#### Summary

I want to extend the list "Project Deliveries" with an extra content type.
Is this possible to do by adding an extension ?

#### Version

Please specify what version you are using: [v2.1.60.4dea91b3 ]

#### Expected / Desired Behavior / Question
We want to have the possibility to select one out of to different content types in the "Project Deliveries" list.

**Comment by olemp** [comment]
Yes, that's supported using `ContentTypeBindings` @jahali.

```json
 {
            "Title": "Programleveranser",
            "Description": "",
            "Template": 100,
            "ContentTypesEnabled": true,
            "RemoveExistingContentTypes": true,
            "ContentTypeBindings": [
                {
                    "ContentTypeID": "0x010088578E7470CC4AA68D5663464831070205"
                }
            ]
}
```

**Comment by jahali** [comment]
But this will replace the existing one?
I would like to add so that I at the end have 2 different content types for that one list

**Comment by olemp** [comment]
Then set `RemoveExistingContentTypes` to `false` @jahali.
