### ISSUE TITLE
Check PnP version / Document typical issues with PnP version

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#502]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ ] Bug

[X] Question

#### Environment

[X] SharePoint Online

[X] SharePoint 2013

[X] SharePoint 2016

#### Summary

Some installations fail because PnP is installaed with an old version (and bundled version is not used). Figure out a way to handle this, by checking the PnP version or AT LEAST document typical errors related to this.

#### Version

Please specify what version you are using: [ ALL]

**Comment by olemp** [comment]
Any progress here @tarjeieo?

**Comment by tarjeieo** [comment]
No 🤦‍♂️

**Comment by olemp** [comment]
🛠

**Comment by olemp** [comment]
What are you planning to do here @tarjeieo?

**Comment by tarjeieo** [comment]
Add a warning as soon as the installation script is running if PnP is on an older version than latest. Will still allow the script to continue of course.

**Comment by olemp** [comment]
Milestone 2.3.0 perhaps? Or would you like to add it before we're going live with 2.2.0?

**Comment by tarjeieo** [comment]
It can wait

**Comment by tarjeieo** [comment]
Printing PnP Source and Version during installation. Will suffice. Too ambitious to keep track of "valid" pnp versions.
