### ISSUE TITLE
Disable CEIP WsaUpload.aspx

### ISSUE THREAD

**Issue by pzlespen** [Puzzlepart/prosjektportalen#508]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[x] Enhancement

[ ] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

CEIP WsaUpload.aspx on SharePoint Onlie, since this is taking up to 1 second on each page to load, see:

https://michielvanerp.wordpress.com/2015/10/20/sahrepoint-online-ceip-wsaupload-aspx/

#### Version

Please specify what version you are using: [ ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by tarjeieo** [comment]
Won't implement this, as this is stepping too much on SharePoint's shoes. Doubt this will make a difference anyway (I don't believe MS will allow a page that has no value slow down each page load with one second).
