### ISSUE TITLE
Move/PR sp-pnp-provisioning to official repository at PnP

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#51]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Enhancement

[ ] Bug

[ ] Question

**Comment by olemp** [comment]
https://github.com/SharePoint/pnp-js-provisioning/pull/13

**Comment by olemp** [comment]
https://github.com/SharePoint/pnp-js-provisioning/pull/13 is merged.

**Comment by olemp** [comment]
Added https://github.com/SharePoint/pnp-js-provisioning/pull/14
