### ISSUE TITLE
Checkpoint for the First phase is not indicated

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#510]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X ] Bug

#### Environment

[ X] SharePoint Online

#### Browser

[X ] Chrome

#### Summary

Checkpoints not indicated for the first phase

#### Version

Please specify what version you are using: [v2.1.60.4dea91b3 ]
_

#### Expected / Desired Behavior / Question
Expected the first phase to be shown as the remaining phases are shown

#### Observed Behavior
All categories (closed, not relevant, open) is shown with zero '0' items in the window when you hover your mouse over the first phase.
All other phases indicates correctly
When clicking 'Go to phase checklist' the checklist is filtered correctly and the items are shown as they should

#### Steps to Reproduce

![image](https://user-images.githubusercontent.com/33092566/37412938-38321bcc-27a6-11e8-9e12-0ad93defb5e6.png)

**Comment by olemp** [comment]
Have not experience this issue. We'll need access to your environment to research this. Shoot us an email.
