### ISSUE TITLE
Weird UX glitch in new project form in Internet Explorer

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#511]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[X ] SharePoint 2016

#### Browser

[ ] Chrome

[X ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Happens only in IE. Looks fine in Edge, Chrome. Not a critical bug, to say the least.

![image](https://user-images.githubusercontent.com/1837390/37508355-fdd8cf4a-28f2-11e8-97b8-06c0ab3009dc.png)

#### Version

Please specify what version you are using: [2.1.66 ]

**Comment by olemp** [comment]
Får ikke reprodusert i IE `v11.309.16299.0`.

**Comment by tarjeieo** [comment]
Looks good in latest version. Suspecting a minor issue with a version of UI fabric. Closing.
