### ISSUE TITLE
Use of different currency in projects

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#516]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ X] Question

#### Environment

[ X] SharePoint Online

#### Browser

[ ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

We would like to use different currency in different projects.

#### Version

Please specify what version you are using: [v2.1.60.4dea91b3 ]

#### Expected / Desired Behavior / Question
How can I change the currency in one project?

**Comment by jahali** [comment]
What field should I change?

**Comment by olemp** [comment]
@jahali The fields you want to change the currency for. E.g. _Total budget_ and _Project prognosis_.

**Comment by jahali** [comment]
Could you please send me a printscreen from where I can change this?
I havent been able to locate the correct place to do this change yet...

**Comment by tarjeieo** [comment]
Gå til prosjektet du skal endre for --> Innstillinger for nettsted --> Områdebiblioteker og -lister --> Tilpass "Områdesider" --> Velg felt, f.eks. "Totalbudsjett for prosjektet". Der har du ulike valg. Vil da gjelde for enkeltprosjektet.

NB: Jeg har ikke testet hva som skjer dersom du oppgraderer PP senere. Det er ikke umulig at valutainnstillingen blir satt tilbake.

![image](https://user-images.githubusercontent.com/1837390/39290728-e151c7c4-4930-11e8-999b-85f724d97330.png)
