### ISSUE TITLE
Project snap shot failing in IE (and console log in chrome)

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#519]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[X] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Snap shoting is failing in IE (and the same error is logged in chrome).

Error: -2147352573 Member not found

Can be relevant: https://stackoverflow.com/questions/13647631/microsoft-jscript-runtime-error-member-not-found

Can also be relevant to prevent default form submittal when exporting.

#### Version

Please specify what version you are using: [2.1.68 ]

**Comment by olemp** [comment]
PNG, PDF or both @tarjeieo?

**Comment by tarjeieo** [comment]
PNG issue.... The same issue as https://github.com/niklasvh/html2canvas/issues/1502. Not sure if these log messages are actually causing any errors. The PNG looks to be generated anyway. 

Looks like the changes in the 4f43d71 commit fixed this.
