### ISSUE TITLE
Install error - Apply-PnPProvisioningTemplate : File not found

### ISSUE THREAD

**Issue by taknes** [Puzzlepart/prosjektportalen#521]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ ] Bug

[X] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

#### Summary

Running the following command from a powershell commandl line 
`.\Install.ps1 -url "https://tenantname.sharepoint.com/sites/prosjektportalen" -useweblogin`

and are getting a the following error:

`Installing taxonomy (term sets and initial terms)...Apply-PnPProvisioningTemplate : File not found
At C:\Users\takoyv\test\prosjektportalen\build\SharedFunctions.ps1:107 char:9
         Apply-PnPProvisioningTemplate ".\templates\$($Template).pnp"  ...
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], FileNotFoundException
     FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate`


#### Steps to Reproduce
git clone repo
start powershell from a windows 10 pc
running the above command

**Comment by tarjeieo** [comment]
Hei,

Dette er ikke måten å installere på - du har lastet ned kildekoden og ikke release-pakken. Se installasjonsveiledningen under https://github.com/Puzzlepart/prosjektportalen/wiki.

Mvh. Tarjei
