### ISSUE TITLE
Access denied when installing

### ISSUE THREAD

**Issue by taknes** [Puzzlepart/prosjektportalen#523]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ ] Bug

[X] Question

#### Environment

[X] SharePoint Online

#### Browser

[X] Chrome

#### Summary

Får feilmelding under installasjon

`Installing taxonomy (term sets and initial terms)...Apply-PnPProvisioningTemplate : Ingen tilgang. Du har ikke tillatelse til å utføre denne handlingen eller bruke denne ressursen.
At C:\Users\takoyv\Downloads\prosjektportalen-2.1.68.9dab142a\SharedFunctions.ps1:107 char:9
         Apply-PnPProvisioningTemplate ".\templates\$($Template).pnp"  ...
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
    FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate`


#### Steps to Reproduce
Opprettet ny områdesamling som gruppenettsted som beskrevet i install dok.
Bruker min egen login som er områdeadmin.

Kjører følgende installasjonskommando (vi bruker MFA)
`.\Install.ps1 -Url "https://iktorkide.sharepoint.com/sites/prosjektportal" -UseWebLogin`

**Comment by tarjeieo** [comment]
Er du term store admin som det står i "Before you install"?

> The script creates a global taxonomy group "Prosjektportalen" in the Managed Metadata Service with a few terms sets and terms. Hence, the user that is used during installation needs to be a term store administrator.

**Comment by taknes** [comment]
Tusen takk.
Det løste det. 

Brukerfeil
