### ISSUE TITLE
Changing the project info 

### ISSUE THREAD

**Issue by IngarMa** [Puzzlepart/prosjektportalen#527]
#### Category
[X] Question

#### Environment

[X] SharePoint Online
#### Browser
[X ] Chrome
[X ] Edge
#### Summary

Is there a way to: 

1. change the fields within the project information? / add other columns? Without adding them manually? 

2. change the order of the fields

3. can we change the display names of existing fields in project info, or will this have a inpact? :-)

#### Version

v2.1.68.9dab142a

#### Expected / Desired Behavior / Question

Want to be able to add more columns/fields to the project information, and have this automaticly added when creating new projects.

**Comment by olemp** [comment]
Yes, you can change the content type _Prosjektforside_, but any changes to default fields/columns will be overriden in the next upgrade. You can add new fields and they won't be removed in an upgrade.

**Comment by tarjeieo** [comment]
Some developers prefer to create a PnP provisioning template, specific for the customer, that overrides the default field names and content type settings/fields. This package then has to be applied after each upgrade.
