### ISSUE TITLE
Hide projects from Home / Portfolio

### ISSUE THREAD

**Issue by marlowandre** [Puzzlepart/prosjektportalen#529]
#### Category

[x] Enhancement

[ ] Bug

[x] Question

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Wondering if there is a feature to hide projects from the Home / Portfolio-page, for example when a project has concluded?

#### Version

Please specify what version you are using: [ 2.1.75 ]

**Comment by olemp** [comment]
Nothing custom, but you have `/_layouts/15/srchvis.aspx` out of the box.

`Tilgjengelighet ved søk og arbeid frakoblet` => `Vil du tillate at dette området vises i søkeresultater?`
