### ISSUE TITLE
Upgrade react sticky to 6.0.1 and enable sticky navigation on project status page again

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#53]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Enhancement

[ ] Bug

[ ] Question

Some issues with this, need to look into if the syntax has changed.

**Comment by tarjeieo** [comment]
I've disabled sticky for the time being. Not a critical feature.

**Comment by olemp** [comment]
What issues @tarjeieo? Status on this one?

**Comment by olemp** [comment]
@tarjeieo 6.0.1 is the latest version.

**Comment by tarjeieo** [comment]
Seems like the changed the syntax in the new major version, and I was unable to make it work again. Feel free to give it a shot.

**Comment by olemp** [comment]
Can we just use the working version?

**Comment by ThomasGranheim** [comment]
@tarjeieo any progress here?

**Comment by olemp** [comment]
What's the issue here?

**Comment by tarjeieo** [comment]
See my previous comment. Nothing special to note other than that "it doesnt work" after upgrade :)

**Comment by olemp** [comment]
So could we revert back to the working version, or was there some issues there aswell?

**Comment by tarjeieo** [comment]
https://github.com/captivationsoftware/react-sticky
