### ISSUE TITLE
Portfolio filter choices: Sort alphabetically

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#530]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

List of refiner choices should be listed alphabetically, not by number of results.

**Comment by olemp** [comment]
Done 🔨
