### ISSUE TITLE
Itemlimit on Standarddocuments?

### ISSUE THREAD

**Issue by KimAreJakobsen** [Puzzlepart/prosjektportalen#535]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ ] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[x ] Chrome

[x ] Internet Explorer

[x ] Edge

[ ] Safari

[ ] Other

#### Summary

When creating new project it dosen't add all folders and files from the template library into the new project. In the template library we have mix of folders and files. When creating a new project it only adds 100 of our folders and none of the documents. Template library consist of 100 files and 185 folders. Seems like there might be a limit for 100 elements?

#### Version

Please specify what version you are using: [2.1.19 ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

**Comment by olemp** [comment]
Solved by upgrading to the latest version.
