### ISSUE TITLE
Feedback/requested functionality wrt. statistics module

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#538]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ X] Enhancement

[ ] Bug

[ ] Question

#### Summary

* Allow to sort graph data by title or other stats/data columns
* Make it possible to filter/exclude single projects/data from chart?
* Allow chart overrides with config files - is it possible? ("custom chart types")

**Comment by olemp** [comment]
1. We can look into that.
2. Already possible
3. Very advanced. Not in 1.0 in my opinion.

**Comment by tarjeieo** [comment]
1. Cool - propose to use a lookup field to statsfields list to "order by"
2. With the search query you mean? Is there was a way to say, select one visual data and the "remove from data series"?
3. Yup, a bit advanced. Let's see what happens with the other project you're working on ;)
