### ISSUE TITLE
Create overview component and page for Project Deliveries

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#540]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X ] Enhancement

[ ] Bug

[ ] Question

#### Summary

Use Gevinstoversikt/Erfaringslogg as starting point. Show project deliveries across projects, using search. Allow group by project and allow export to excel. Should be part of standard PP.

**Comment by tarjeieo** [comment]
Blir ferdig med denne til milestone 2.2.0

**Comment by olemp** [comment]
![image](https://user-images.githubusercontent.com/7606007/42089313-db34640c-7b9c-11e8-89cf-ca58d4766f02.png)

**Comment by olemp** [comment]
Is this ready for 2.2.0 @tarjeieo?

**Comment by tarjeieo** [comment]
95%! Just need to add a couple of more fields to the list view. Will do today!

**Comment by olemp** [comment]
Do this today @tarjeieo.

**Comment by tarjeieo** [comment]
This should be complete now. Still want to implement group by project, but will have to wait (will create separate issue)
