### ISSUE TITLE
Upgrade all PnP PowerShell binaries to June 2018 version

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#543]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[X] SharePoint 2013

[X] SharePoint 2016

#### Summary

We need a fix in PnP PowerShell June 2018 for setting ContentType with DataRows. Need to update all binaries.

Necessary for 2.2.0

**Comment by tarjeieo** [comment]
June version of these needs to be installed. https://github.com/SharePoint/PnP-PowerShell/releases

See build/bundle in our project.

**Comment by tarjeieo** [comment]
Is this done @Remi749 ?

**Comment by Remi749** [comment]
Hi, the binaries are updated, the pull request was approved by @olemp. Prosjektportalen was installed on a new Sharepoint site and tested successfully, and no errors during project build. I will remember to tag the ticket number in the commit next time.
