### ISSUE TITLE
Create upgrade package for #534 to add search data list items as datarows

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#544]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

For anyone upgrading to 2.2.0 from earlier versions, we need to add the configuration list items as datarows.

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen/pull/553 merged
