### ISSUE TITLE
Issue with opening /ProjectStatus.aspx

### ISSUE THREAD

**Issue by IngarMa** [Puzzlepart/prosjektportalen#546]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment

[X] SharePoint Online

#### Browser

[X ] Chrome

[X] Edge

#### Summary

When attempting to go to projectstatussite, the screen becomes white. Nothing is displayed.

#### Version

2.1.78.

#### Expected / Desired Behavior / Question
Dashboard

#### Observed Behavior
Site keeps on loading / is white. In F12, we can see this

![image](https://user-images.githubusercontent.com/32195694/41414557-af7ced00-6fe6-11e8-888a-dab031d8af55.png)

Anyone seen this before?
Have other installs that does not have this issue

#### Steps to Reproduce
Just go into page, and it "stops"

**Comment by tarjeieo** [comment]
Hei,

Fiksen er å gå til "Prosjektportalen - Statusseksjoner". Velg "Risiko" og endre innholdstype til "Risikoseksjon"/"Risk section". Det skal være nok for å få det til fungere igjen.

Dette var en feil pga. en endring i PnP-rammeverket som vi bruker til å installere. Dette er bli løst i juni-versjonen av PnP, og denne feilen blir dermed rettet i den neste offisielle releasen av Prosjektportalen.

Verifiserer du OK?

-Tarjei

**Comment by IngarMa** [comment]
Da fungerte det, Takk for rask bistand

**Comment by tarjeieo** [comment]
Takk for kjapp tilbakemelding 👍
