### ISSUE TITLE
Project status page title fields does not display correctly when taking snapshot with IE/Edge

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen#547]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ ] Chrome

[X] Internet Explorer

[X] Edge

[ ] Safari

[ ] Other

#### Summary

When taking a snapshot of a project status page when using either IE or Edge, the title field for both Risk and progress, maybe more, are messed up if the title is long enough to have some of it hidden by the overflow. This does not occur for earning achievement. Solution would be to introduce a word-wrap property. See screenshot below.

![screenshot_1](https://user-images.githubusercontent.com/28678468/41468297-cd03de74-70a9-11e8-948d-df2814e00edd.png)

#### Version

Please specify what version you are using: [2.1.78.7]

**Comment by olemp** [comment]
Nice find!

We're using the DetailsList from office-ui-fabric-react (https://developer.microsoft.com/en-us/fabric#/components/detailslist).

You can check if there's a setting on the IColumn @Remi749.
