### ISSUE TITLE
Only selected risk elements should be aggregated to the risk matrix overview

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#554]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ X] Enhancement

[ ] Bug

[ ] Question

#### Summary

GtRiskOverviewSelected

**Comment by olemp** [comment]
Used this field for AK:

`xml
    <Field Type="Boolean" DisplayName="Vis i portefølje" EnforceUniqueValues="FALSE" Indexed="FALSE" Group="Prosjektportalenkolonner" ID="{6bd17911-c48a-4900-be61-54ae26207d78}" SourceID="{c3d05514-694b-41fa-b82e-338f149a5231}" StaticName="GtShowInPortfolio" Name="GtShowInPortfolio" CustomFormatter="" Required="FALSE">
        <Default>0</Default>
    </Field>
`

**Comment by olemp** [comment]
InternalName GtShowInPortfolio

**Comment by tarjeieo** [comment]
Nice - updating to the same in PP

**Comment by olemp** [comment]
Remember to update the upgrade packages aswell.

build\@upgrade\2.1_2.2
