### ISSUE TITLE
Default settings is overriding the chosen settings in a site collection on upgrade

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#557]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ X] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[X ] SharePoint 2016

#### Summary

Customer had chosen "PDF" as export format for project status. After the upgrade it's reverted to "PNG". The same thing happened across 10 sitecols.

#### Version

Please specify what version you are using: [2.1.78 ]

**Comment by olemp** [comment]
Was done on purpose, because I didn't think of it as a big issue, but for customers with several installations it could cause quite a bit of work. Looks like we need to look into a solution using PnP PowerShell instead of just using the root template.

**Comment by tarjeieo** [comment]
What about: When saving from the settings page, we create a new property pp_chosensettings, and add the chosen settings there? Then our "service" that retrieves settings first has to look for pp_chosensettings and next pp_defaultsettings if no chosen settings has been set. Then we will never override the chosen settings.

**Comment by olemp** [comment]
Great input @tarjeieo 

So, I did some changes.

`WebPropertyBagEditor` component will save to `pp_chosensettings`.

When we retrieve settings in our helper `Settings\index.ts`, it will first look for `pp_chosensettings`, if it doesn't exist it will pick `pp_settings`. After that it will loop through  `pp_settings` and add those keys that are missing in  `pp_chosensettings`.
