### ISSUE TITLE
SPListItem taxonomy field error

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#567]
#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Sometimes it fails, and when it goes through, phase is not set for e.g. phase checklist items.

![image](https://user-images.githubusercontent.com/7606007/42209881-16be568e-7eb0-11e8-8041-c0aa11bf97eb.png)

#### Version
v2.1.91.ec1f5c4e

**Comment by olemp** [comment]
Did a test with 5 project creations.

Looks like 2 of them failed.

![image](https://user-images.githubusercontent.com/7606007/42210358-2a9e2d9a-7eb1-11e8-9376-3b3620081f07.png)

Log doesn't give much details

![image](https://user-images.githubusercontent.com/7606007/42210383-3a484de8-7eb1-11e8-88df-e0b9e71da355.png)

**Comment by olemp** [comment]
New test case. Worked 5/5, but phase is not set for any items.

**Comment by olemp** [comment]
Sometimes fails with message _The SPListItem being updated was not retrieved with all taxonomy fields_.

**Comment by olemp** [comment]
No issues in pzlcloud. Might be just my tenant having some issues...

**Comment by olemp** [comment]
Can't reproduce in another tenant. Will re-open if this causes issues again.

**Comment by olemp** [comment]
Reproduced in prosjektportalen.sharepoint.com tenant.

![image](https://user-images.githubusercontent.com/7606007/42278260-788f1fb6-7f9a-11e8-9704-80de07a5cbe2.png)

**Comment by olemp** [comment]
https://blog.bugrapostaci.com/2015/07/03/the-splistitem-being-updated-was-not-retrieved-with-all-taxonomy-fields/

**Comment by tarjeieo** [comment]
Hmm, such strange. No changes to taxonomy or taxonomy fields literally ever. Can't believe it's anything with lookup column restrictions.

**Comment by olemp** [comment]
http://spmoshpit.de/2017/12/kaputte-managed-metadata-felder-in-sharepoint-wieder-fixen/

**Comment by olemp** [comment]
We might have to set `WebId` and `List` attributes.

**Comment by olemp** [comment]
Did a test case after setting WebId for all taxonomy fields. 5/5 OK

**Comment by olemp** [comment]
Building 2.1.96 for testing.
