### ISSUE TITLE
Default query values have wrong encoding

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#570]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Summary

The default value of the search query field in new data sources and portfolio views have the following default value (looks to be URL-encoded - edit this post for details): "ContentTypeId&#58;0x010109010058561f86d956412b9dd7957bbcd67aae0100* Path&#58;&#123;Site.URL&#125;". This is not interpreted by SP.

Suspect a change in PnP Core have caused this. Need to investigate.

#### Version

2.1.78 and later

**Comment by olemp** [comment]
What's wrong? Can't see any issues.. Is the `Path:{Site.URL}` not working?

**Comment by olemp** [comment]
Ahh, this is what you mean!

![image](https://user-images.githubusercontent.com/7606007/42267091-643546ca-7f78-11e8-8c90-52ef6174a00a.png)

**Comment by tarjeieo** [comment]
Yup exactly

**Comment by olemp** [comment]
Testet å lage en kolonne i GUI. Da fungerer det:

![image](https://user-images.githubusercontent.com/7606007/42268194-316958e6-7f7b-11e8-8720-1f4c988b207d.png)


Tar en sjekk på forskjellen på field xml.

**Comment by olemp** [comment]
```xml
<Field Type="Note" DisplayName="Søkespørring" Description="" ID="{31e405e0-2890-439d-9c9f-42354154feda}" StaticName="GtDpSearchQuery" Name="GtDpSearchQuery" Group="Prosjektportalenkolonner" SourceID="{e266a38d-dd9f-4e99-a715-0ab1c0de6d90}" AllowDeletion="TRUE" Version="55" ColName="ntext2" RowOrdinal="0"><Default>ContentTypeId&amp;#58;0x010109010058561f86d956412b9dd7957bbcd67aae0100* Path&amp;#58;&amp;#123;Site.URL&amp;#125;</Default></Field>
```

```xml
<Field Type="Text" DisplayName="TestIssue570" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" MaxLength="255" ID="{412971be-843a-4a55-8263-a0d9e863222e}" SourceID="{37cffbec-8a74-4b84-b66d-a88cf99bbab4}" StaticName="TestIssue570" Name="TestIssue570" ColName="nvarchar4" RowOrdinal="0"><Default>ContentTypeId:0x010109010058561f86d956412b9dd7957bbcd67aae0100* Path:{Site.URL}</Default></Field>
```

**Comment by olemp** [comment]
Looks like this is something that's done in PnP-Sites-Core, and I don't think we can prevent it. 

I suggest with go for no default value, @tarjeieo.

**Comment by tarjeieo** [comment]
It sucks a little bit, since it's yielding creating portfolio views more or less useful for users... but I guess it's the only option for now. 

/remind us in 3 months 👯‍♂️

**Comment by olemp** [comment]
Not really useless.. They can look at the other data sources. 👍

**Comment by tarjeieo** [comment]
Yup, competent users will find a way 👍

**Comment by olemp** [comment]
You'll need a level of competence to create your own search queries anyways, so I don't think this makes a `huge` difference 🍔
