### ISSUE TITLE
Add field to control order of links on the front page

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#572]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X ] Enhancement

[ ] Bug

[ ] Question

#### Summary

From customer: Can we add sort order field to links and use this when rendering the front page links?

**Comment by olemp** [comment]
Customer wish fulfilled 🙌
