### ISSUE TITLE
Problem creating projects in Projectportal

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen#575]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary
When creating a project approximatly 2/5 times, it fails to create a project. Giving me the following error message:
![image](https://user-images.githubusercontent.com/28678468/42380011-c474abe2-812c-11e8-992b-6d0ebdb923e6.png)

With the last 20 lines in log file showing:
![image](https://user-images.githubusercontent.com/28678468/42380065-f2ab8a44-812c-11e8-9639-763f8959019f.png)

**This has been happening throughout development of the template for lskog and testing on lskog's PP sites. This is a cricital problem as we are about to create dousins of projects next weeks for lskog.**
#### Version

Please specify what version you are using: [2.1.78.7c0e4326]

#### Steps to Reproduce
Creating a project in any projectportal site that's using a template should probably reproduce the same message, if it creates a project successfully, one should try again to see it continues to successfully create projects.

#### Other information:
This could probably ble linked to issue: #567, as they are similar, but on two different tenants.

**Comment by tarjeieo** [comment]
Most likely due to customer-specific configuration. Closing.
