### ISSUE TITLE
Project resources

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#578]
#### Category

[x] Enhancement

[ ] Bug

[ ] Question

**Comment by olemp** [comment]
English | Norsk
-- | --
|Prosjekteier
|Prosjektleder/BH
|Planlegger
|Innleid prosjektleder
|Ass. Prosjektleder
|Controller
|Kvalitetsleder
|Ansvarlig Bestiller
|Brukerkoordinator
|Prosjektgruppe
|SHA koordinator (KP/KU)
|BH-ombud/ BH kontrollør/BL
|PGL/rådgivningsgruppe
|Hovedentreprenør
|Seksjon for drift og forvaltning
|Kundeservice/marked
|Eiendomskontoret

**Comment by olemp** [comment]
We should probably use `RefinableString` for `Navn` and `Rolle`. The format of the auto properties for taxonomy and user fields is not the prettiest.

![image](https://user-images.githubusercontent.com/7606007/42630865-ae464a14-85d8-11e8-867a-e521d2ae6906.png)


Guess we have to update `manual-conf` then.

We can probably use `RefinableString59` and `RefinableString60`.

**Comment by tarjeieo** [comment]
Agreed. Smart. I would start with RefinableString70 as RefinableString5* and 6* has often been taken by customers.... E.g.

RefinableString70: Gevinstansvarlig (this one is also missing)
RefinableString71: Ressursnavn
RefinableString72: Rolle

**Comment by olemp** [comment]
Ok, cool! Will use those 👍

**Comment by olemp** [comment]
![image](https://user-images.githubusercontent.com/7606007/42631251-e98b8bba-85d9-11e8-94b7-33776d81c20d.png)

**Comment by olemp** [comment]
How did we generate a new `SearchConfiguration_tenant.xml` @tarjeieo?

**Comment by tarjeieo** [comment]
@olemp Generating a new SearchConfiguration has to be done on a new tenant by
1. Importing the old schema
2. Configuring additional properties and mappings
3. Export search scema

Of course to do (2) PP already has to be installed and crawled somewhere in the tenant.

**Comment by olemp** [comment]
Initial implementation done.
