### ISSUE TITLE
The order of fields in the portfolio view is not easily persisted

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#585]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[X] Internet Explorer

[X] Edge

[X] Safari

[X] Other

#### Summary

When configuring the portoflio view list, the order of portfolio fields selected in the fields column is no longer persisted. This is only applicable in modern experience. See the following reported question/bug: 
https://github.com/SharePoint/sp-dev-docs/issues/2272

What we can do is revert to the order-value of the portfolio fields, and always render all fields in an explicit order again (like we did earlier).

#### Version

Please specify what version you are using: [All]

**Comment by tarjeieo** [comment]
....which means that it's the sorting index that will prevail again, right? I think that's fair, since Microsoft have changed the logic here and there's apparently nothing else we can do....

**Comment by olemp** [comment]
@tarjeieo Yes, sorry for lack of comment. Will need to sort by order of the fields.
