### ISSUE TITLE
Resource allocation

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#586]

**Comment by olemp** [comment]
Initial implementation done.

**Comment by tarjeieo** [comment]
We need the following implemented/handled before release

1. Configurable search query: We need to use the data sources list like all the other top level pages.
2. Upgrade actions: We need to handle search schema changes, new term set, new data source list item. We should also handle adding the resource list to existing projects (perhaps as a separate script?)
3. Add support for creating users from the availability list without any entries in projects (adding a user in the top-level list should still be listed on the resource allocation page, even if he's not added to any project)
4. Resource allocation color opacity based on allocation percentage per project (working on it)

**Comment by tarjeieo** [comment]
Couple of more minor things

* Round down percentages to 0 decimals
* In the default query: filter out resource allocations that has end date more than 3 months from now

**Comment by tarjeieo** [comment]
In the default query: filter out resource allocations that has end date more than 3 months from now

This requires mapping start and end date fields to Refinable dates.... TODO later

**Comment by tarjeieo** [comment]
Will add upgrade actions on Monday 12th of November and merge to dev.

**Comment by olemp** [comment]
* Round down percentages to 0 decimals
* In the default query: filter out resource allocations that has end date more than 3 months from now
* Configurable search query: We need to use the data sources list like all the other top level pages.
* Upgrade actions: 
* * We need to handle search schema changes, new term set, new data source list item. *We should also handle adding the resource list to existing projects (perhaps as a separate script?)
* * Add support for creating users from the availability list without any entries in projects (adding a user in the top-level list should still be listed on the resource allocation page, even if he's not added to any project)
* Resource allocation color opacity based on allocation percentage per project (working on it)

**Comment by tarjeieo** [comment]
I think we should include 'Configurable search query: We need to use the data sources list like all the other top level pages.' in 2.3 because that's our upgrade-window (upgrading from 2.x to 2.3).

**Comment by olemp** [comment]
* Round down percentages to 0 decimals ✅ 
* ~~In the default query: filter out resource allocations that has end date more than 3 months from now~~
* Configurable search query: We need to use the data sources list like all the other top level pages. ✅ 
* Upgrade actions: 
  * Handle search schema changes, new term set, new data source list item. 
  * Handle adding the resource list to existing projects (perhaps as a separate script?)
* Support for creating users from the availability list without any entries in projects ✅ 
* Resource allocation color opacity based on allocation percentage per project ✅

**Comment by tarjeieo** [comment]
Only thing missing is defining the upgrade templates/actions, right @olemp ?

**Comment by olemp** [comment]
Yes, would you mind implementing this? Or we can implement it together later this week.

**Comment by tarjeieo** [comment]
Going to look into this Wed or Thu.

**Comment by tarjeieo** [comment]
Testing in real environment, just a few minor adjustments needed
* Comment-field to optionally give more information about the allocation/absence (could use title-field)

**Comment by tarjeieo** [comment]
⛱
