### ISSUE TITLE
Consider reverting the installation bundle to an earlier PnP-PowerShell release

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#591]
Reference: https://github.com/SharePoint/PnP-PowerShell/issues/1678

**Comment by tarjeieo** [comment]
We cannot because of this dependency: https://github.com/Puzzlepart/prosjektportalen/issues/533

We need to wait for a fix by the PnP team

**Comment by olemp** [comment]
Thanks for the clarifications.
