### ISSUE TITLE
Editable project properties for the projectcards on the site landing page

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen#593]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

DocumentCardActivity should be editable in some way, maybe like a .txt file in the Resources list in Projectportal. Where it would be possible to change project property of the DocumentCardActivity -> people that shows on the landing page of a site where all the projectcards are shown.

![image](https://user-images.githubusercontent.com/28678468/44515125-0571a400-a6c2-11e8-9fc8-f8ef9bc9d1cd.png)

The properties marked here should be somehow editable:
![image](https://user-images.githubusercontent.com/28678468/44515163-1cb09180-a6c2-11e8-9f39-b733a8192457.png)

Solution could be what I described above, by using a .txt file for customization, like we do with .txt files the "Resources" folder or "Extensions" if possible.

**Comment by tarjeieo** [comment]
This is still relevant and should not have been closed

**Comment by olemp** [comment]
I don't agree. I don't think we should support this level of customizations. The more customizations we open for, the more can go wrong.

**Comment by tarjeieo** [comment]
Just fields on the card, don't see how this breaks the ice water glass drop? One customer really wants it...

**Comment by olemp** [comment]
Too complicated with the current approach

**Comment by olemp** [comment]
![image](https://user-images.githubusercontent.com/7606007/50218620-d677f000-038c-11e9-874a-5a50bb7fc74b.png)

This how it's done now.

**Comment by olemp** [comment]
And we're using this model:

![image](https://user-images.githubusercontent.com/7606007/50218643-e68fcf80-038c-11e9-9a06-6430a30bad65.png)
