### ISSUE TITLE
In the Project information dialog, show link to project and project status both in the top and bottom of the dialog

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#595]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X ] Enhancement

[ ] Bug

[ ] Question

#### Summary

Quick access to project, wants to avoid scrolling. Also, the buttons doesn't have to be dialog-wide, normal size is good.

**Comment by tarjeieo** [comment]
![image](https://user-images.githubusercontent.com/1837390/44585807-ce78bc80-a7ad-11e8-9462-f1ca33ae96fc.png)

**Comment by olemp** [comment]
I don't think we should implement this.

**Comment by havardd** [comment]
I think it would be practical if the buttons was on topp. Agree that top and bottom is a bad idea.

Med vennlig hilsen
Vestfold fylkeskommune
v/Håvard Dahle
47393011



Fra: Ole Martin Pettersen
Sendt: tirsdag 28. august, 15:56
Emne: Re: [Puzzlepart/prosjektportalen] In the Project information dialog, show link to project and project status both in the top and bottom of the dialog (#595)
Til: Puzzlepart/prosjektportalen
Kopi: Subscribed


I don't think we should implement this.

**Comment by olemp** [comment]
@havardd Agreed. Will be included in next release.
