### ISSUE TITLE
Changing phase does not work (fails with console error)

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#600]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Changing phase fails for all portfolios in pzlcloud. Haven't heard from customers yet.

Global outages? But changing other metadata fields still work.

Change of how working with terms works in jsom in first release tenants? Weird, but possible....

Other tenant changes possible?

![image](https://user-images.githubusercontent.com/1837390/44847823-f73cfe00-ac54-11e8-8af3-3d5dba14617b.png)

#### Version

Please specify what version you are using: [2.2.0 and 2.1.66]

**Comment by olemp** [comment]
Not able to reproduce here: https://pzlcloud.sharepoint.com/sites/ppdemo_v2/migrering-av-intra/SitePages/ProjectHome.aspx

What project did you get this on @tarjeieo?

**Comment by tarjeieo** [comment]
https://pzlcloud.sharepoint.com/sites/ppdemo_v2/migrering-av-intra and https://pzlcloud.sharepoint.com/sites/pp-program/ny-kommune-2020

Still getting the error on both
