### ISSUE TITLE
Phase check list filters does not work in IE/Edge with special characters in modern experience (e.g. Gjennomføre)

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#603]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ ] Chrome

[X] Internet Explorer

[X] Edge

[ ] Safari

[ ] Other

#### Summary

The link from the phase web part to filtered phase check list items does not work with phase "Gjennomføre". Nothing is shown. For some reason the modern experience is interpreting the encoding wrong.

See also ASSIST-1989.

#### Version

Please specify what version you are using: [2.1.78]

**Comment by olemp** [comment]
See attempted fix in #605. I don't like it, but it seems to solve the issue 🍔

**Comment by tarjeieo** [comment]
Including this in 2.3.0 and cross fingers
