### ISSUE TITLE
Feil med datofelter i prosjektegenskaper - Index was outside the bounds of this array

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#604]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[X] Internet Explorer

[X] Edge

[X] Safari

[X] Other

#### Summary

Unable to save project properties because of this error. This is a pretty recent one (Sept 18). reported by 2 customers.

#### Version

Please specify what version you are using: [2.2.0 and v2.1.60.4dea91b3 ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

![pp-dato-index-feil](https://user-images.githubusercontent.com/1837390/45866304-9fd80c80-bd80-11e8-93d2-cbb83f155c42.png)

**Comment by olemp** [comment]
Hei @Lysakers. Nei, ingen fremgang. Det er ikke så mye vi får gjort med en global SP feil.

**Comment by Lysakers** [comment]
@olemp I følge Microsoft så skal denne feilen være fikset på søndag.
Derfor usikker på om det i vår tenant fortsatt er en SP feil eller om det er noe i Prosjektportalen som må korrigeres.

**Comment by olemp** [comment]
Hei @Lysakers. Vi oppretter bare standard SharePoint datofelter, så det er dessverre ikke så mye vi får gjort med Prosjektportalen. La oss håpe det løser seg snarlig. Mulig feilrettingen ikke er propagert til alle tenants.

**Comment by olemp** [comment]
Flere har meldt om feilen også utenfor Prosjektportalen, så jeg vet dessverre ikke hva vi får gjort med dette.

**Comment by Lysakers** [comment]
Flott, da gir jeg det en dag eller to og så følger jeg opp direkte Microsoft.

**Comment by tarjeieo** [comment]
Dette er bekreftet fikset av minst 3 kunder. 💛

**Comment by olemp** [comment]
🎧
