### ISSUE TITLE
Unable to create SharePoint 2010 Approval Workflow on PP site collection

### ISSUE THREAD

**Issue by martinfy** [Puzzlepart/prosjektportalen#606]
#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[x] SharePoint 2016

#### Browser

[x] Chrome

[x] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary
Unable to create a new SharePoint 2010 Approval Workflow on site collection where "Prosjektportalen" is installed. 

#### Version

Please specify what version you are using: [v2.2.6]

#### Expected / Desired Behavior / Question
Workflow gets created and configured correctly.

#### Observed Behavior
Unable to save workflow. Error message in console: Object doesn't support property or method 'OnFocus' .
When custom action pp.main.js (site scope) is removed, things work again.

#### Steps to Reproduce
Enable site collection feature "Workflows (aggregated set of out-of-box workflow features provided by SharePoint)".
Go to a random list or library, e.g. "Documents", create a new SharePoint 2010 Approval Workflow. Choose approvers and try to save the workflow.

**Comment by olemp** [comment]
pp.main.js custom action is referencing our .js bundle, so removing this will cause a lot of issues.

**Comment by olemp** [comment]
I must say we haven't thought much about SP 2010 Workflow support when we've been developing Prosjektportalen 2.0, but we should look into if there's something we can do in the JS to avoid this.

**Comment by martinfy** [comment]
@olemp: removing the custom action was just to be sure this was causing the issue (on a test site collection). I agree it's a terrible idea to remove the bundle on a general basis ;)

**Comment by olemp** [comment]
@martinfy Yes, I know. Just answering here while being in a completely different context. Haha.

I'm not sure when I have time to look into this. What about you @tarjeieo?

**Comment by tarjeieo** [comment]
👨‍🌾

**Comment by olemp** [comment]
@tarjeieo Might be some polyfill messing up for SP 2010 Workflows.

**Comment by tarjeieo** [comment]
Looks like this is related to a leak in the MrRio/JsPdf solution. Looks like the global object "Button" is being overwritten. Doesn't look like an easy fix, but will investigate a bit more.

**Comment by tarjeieo** [comment]
I've registered an issue with jspdf and will await their follow-up: https://github.com/MrRio/jsPDF/issues/1989

**Comment by okms** [comment]
Could jspdf be lazy loaded with a require statement, thus only be evaluated when you actually need to make a pdf?

**Comment by tarjeieo** [comment]
Yes, feasible! Will accept a PR! (I don't believe in myself enough to implement that) 😆

**Comment by olemp** [comment]
beliiieb in yoself @tarjeieo :godmode:

**Comment by tarjeieo** [comment]
This has been fixed https://github.com/MrRio/jsPDF/issues/1989 - awaiting new release from jsPDF and then it should work in PP as well 👍 

cc @pzlespen @martinfy

**Comment by tarjeieo** [comment]
Looks like jsPDF har built a new release. Will update package.json at our side. Will be fixed in the next PP release.
