### ISSUE TITLE
Error installing root-package to Specified method is not supported. on a ms demo tenant with norwegian sitecollection and termstore

### ISSUE THREAD

**Issue by trillian74** [Puzzlepart/prosjektportalen#609]
#### Category
[*] Question

#### Environment

[ *] SharePoint Online

#### Browser

[ *] Chrome

#### Summary
Trying to install the portal on a ms demo tenant using demos.microsoft.com but it fails with 
Error installing root-package to https://m365xnnnnn.sharepoint.com/sites/prosjekter
Specified method is not supported.
Please summarize the issue.

SharePointPnPPowerShellOnline 3.2.1810.0
SharePointPnPPowerShellOnline 3.0.1808.1

#### Version

Please specify what version you are using: [ latest]

**Comment by tarjeieo** [comment]
Got any more information? Can you pass along the pp-logfile located in the install dir?

**Comment by trillian74** [comment]
@tarjeieo Hi there just wanted to update you that it did'nt work in the microsoft demo tenants. log issuing these messages (version pp: latest, pnp: latest, site collection lcid norwegian, defautl termstore language : norwegian)
`powershell.exe Information: 0 : 2018-10-15 16:17:40.4864	[List instances]	[10]	[Debug]	Creating list {resource:Lists_PhaseChecklist_Title}	8370ms	ed7bbcc1-322a-44c9-b53a-a14e204fa647
powershell.exe Information: 0 : 2018-10-15 16:17:41.0843	[List instances]	[10]	[Debug]	Creating list {resource:Lists_PhaseChecklist_Title} failed: Specified method is not supported. :    ved Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   ved Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   ved Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__4.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   ved OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateList(Web web, ListInstance templateList, TokenParser parser, PnPMonitoredScope scope, Boolean isNoScriptSite)
   ved OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)	8968ms	ed7bbcc1-322a-44c9-b53a-a14e204fa647
powershell.exe Information: 0 : 2018-10-15 16:17:41.0853	[List instances]	[10]	[Debug]	Code execution scope ended	8968ms	ed7bbcc1-322a-44c9-b53a-a14e204fa647
powershell.exe Information: 0 : 2018-10-15 16:17:41.0853	[Provisioning]	[10]	[Debug]	Code execution scope ended	511010ms	ed7bbcc1-322a-44c9-b53a-a14e204fa647
`

**Comment by tarjeieo** [comment]
Hei @trillian74,

Vi ser dette i noen få tenants men klarer ikke finne en regel for når det skjer. Er tenanten din på targeted release eller standard?

-Tarjei

**Comment by tarjeieo** [comment]
Running theory is that this issue is related to a change in MaxVersionLimit. https://cann0nf0dder.wordpress.com/2018/09/26/pnp-document-library-provisioning-failed-specified-method-is-not-supported/

Attempting a fix now

**Comment by tarjeieo** [comment]
Issue confirmed! https://github.com/SharePoint/PnP-Sites-Core/issues/1932

Fix underway in a new release!
