### ISSUE TITLE
Portfolio insights not working in SP2013

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#612]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[X] SharePoint 2013

[ ] SharePoint 2016

#### Summary

On the portfolio insights page we're getting BatchParseException. See https://github.com/SharePoint/PnP-JS-Core/issues/492.

Looks like batching is not supported in SP2013.

#### Version

Please specify what version you are using: [2.2.6]

#### Console error message
`Message: (ProjectStats) componentDidMount: Failed to fetch data. Data: {"description":"Invalid response, line 0","name":"BatchParseException","stack":"BatchParseException: Invalid response, line 0\n   at Anonymous function (https://testprosjektplassen.kartverket.no/siteassets/pp/js/pp.main.js?v=2.2.6.f8bd9e20:21:159113)\n   at k (https://testprosjektplassen.kartverket.no/siteassets/pp/js/pp.main.js?v=2.2.6.f8bd9e20:118:325180)\n   at e.ParseResponse (https://testprosjektplassen.kartverket.no/siteassets/pp/js/pp.main.js?v=2.2.6.f8bd9e20:21:158833)\n   at Anonymous function (https://testprosjektplassen.kartverket.no/siteassets/pp/js/pp.main.js?v=2.2.6.f8bd9e20:118:324101)\n   at Anonymous function (https://testprosjektplassen.kartverket.no/siteassets/pp/js/pp.main.js?v=2.2.6.f8bd9e20:118:323971)\n   at c (https://testprosjektplassen.kartverket.no/siteassets/pp/js/pp.main.js?v=2.2.6.f8bd9e20:118:327247)"}
`

**Comment by olemp** [comment]
Please have a look at https://github.com/Puzzlepart/prosjektportalen/pull/618.

Should we go for it?

**Comment by tarjeieo** [comment]
Do it! 💃
