### ISSUE TITLE
Small adjustments to project status sections, field value width

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#613]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

Can we make small adjustments to the width of the fields? E.g. text fields could be wider than number fields, and so forth.

This issue is to experiment a bit with this.

![image](https://user-images.githubusercontent.com/1837390/47205279-bb393600-d385-11e8-8815-fe88befdf0fe.png)

**Comment by olemp** [comment]
Tough one! 🔨

**Comment by tarjeieo** [comment]
Proposed fix for this in the upcoming release
