### ISSUE TITLE
Define PnP Schema DataRows UpdateBehaviour and KeyColumns for avoiding overwrites with default data and configuration

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#621]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

See https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2018-07.md#datarow. If we define UpdateBehaviour and KeyColumns we can avoid some of the duplication of data that can easily happen today by non-expert installation personell.

**Comment by olemp** [comment]
non-expert installation personell 🤣

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen/pull/631

Please test before we merge this.
