### ISSUE TITLE
Project search and crawled properties not consistent

### ISSUE THREAD

**Issue by trillian74** [Puzzlepart/prosjektportalen#622]
#### Category

[x] Bug

[x] Question

#### Environment

[x] SharePoint Online
#### Browser

[x] Chrome

#### Summary

It takes time until something appears on the items or anything at all

![image](https://user-images.githubusercontent.com/1140066/48407503-3dbfd600-e737-11e8-93a9-a5d9ee3d2dda.png)

When i add site logo they appear...
#### Version

Please specify what version you are using: [v2.2.10.db6b496c ]

#### Expected / Desired Behavior / Question
I'm expecting them to appear after some crawl time?
#### Observed Behavior

Some properties get set others don't, but when i add a project image (site logo) then everything appears

What are the requirements for site properties to actually get picked up by the crawl consistently? I have uploaded the search config and they are created, the site collection is norwegian,

**Comment by trillian74** [comment]
My main confusion is that search picks something up and others not... But when i added a site logo everything appeared:) ?

**Comment by trillian74** [comment]
I’ve ended up with an azure runbook automation updating the vti searchversion prop in the propertybag on the portal in a predefined interval. It works for now. Looking 4ward for a fix:)

**Comment by tarjeieo** [comment]
This has become much more stable recently. Seen any improvements on your side @trillian74 ?

**Comment by marlowandre** [comment]
I'm having the same type of issue, especially in one tenant. Updating project statuses for instance in a project doesn't update in the Portfolio. Manually reindexing the site makes the Portfolio update.

**Comment by tarjeieo** [comment]
We're going to look into a rewrite shortly

**Comment by tarjeieo** [comment]
We've rewritten this in #642 which will be the next minor release "2.4.0". We're testing this a bit more than usual, because this has impact on all existing project after an upgrade. If you'd like to test at your side before we do an "official" release, that's appreciated. Feel free to follow #642.
