### ISSUE TITLE
Search in all available project fields in the dynamic portfolio search as you type search bar

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#623]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

I dynamisk portefølje... se DynamicPortfolio/index.tsx linje 419... Om jeg skjønner riktig er det "search as you type" funksjonaliteten. Men den søker bare i Title-feltet.
let items = this.state.filteredItems ? this.state.filteredItems.filter(item => item[this.props.searchProperty].toString().toLowerCase().indexOf(this.state.searchTerm) !== -1) : [];

Er det mulig å la den søke i alle feltene som brukes i den aktuelle visningen?

**Comment by olemp** [comment]
Since you're already in the code, please implement this @tarjeieo 

😸
