### ISSUE TITLE
Support URL-fields in portfolio view and project info card

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#625]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

In some cases it's relevant to use URL-fields in project properties. It would be very useful to see these links formatted correctly in the project portfolio view and in the project information popup.

**Comment by olemp** [comment]
Such multitasking 🍔
