### ISSUE TITLE
Add search schema tenant-settings using PnP in case of SharePoint online

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#626]
We can avoid a manual step by using PnP now.

Set-PnPSearchConfiguration -Scope Subscription -Path .\manual-conf\SearchConfiguration_tenant.xml

Consider adding a switch for this in the install script

**Comment by olemp** [comment]
Does this work for both onprem and cloud @tarjeieo?

**Comment by tarjeieo** [comment]
SPO only

**Comment by tarjeieo** [comment]
This requires SPO Admin permissions and the current installation does not. Doesn't yield enough benefit for it to have merits and further complicate installation/permissions. Closing.
