### ISSUE TITLE
Entries in Lessons Log

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#629]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ ] Bug

[ X] Question

#### Environment

[ X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ X] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Is it possible to get lessons collected into Lessons Log on Portfolio level from other lists than the Project Log?

#### Version

Please specify what version you are using: [ 2.1.60]

#### Expected / Desired Behavior / Question
For example by adding the Log element content type in other lists?
Or is the collection filter by this list?

**Comment by tarjeieo** [comment]
Well, the fields would have to be exactly the same (reused). In theory, you can save the lessons log list as template, and recreate it somewhere in the site collection, and items should be picked up.
