### ISSUE TITLE
Use resource files for remaining choice field values

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#63]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ X] Enhancement

[ ] Bug

[ ] Question

See root/Objects/SiteFields.xml

**Comment by olemp** [comment]
- GtGainsType
- GtMeasurementUnit
- GtFeedbackStatus
- GtFeedbackCriticality
- GtProductStatus
