### ISSUE TITLE
Issues with "field not found" when upgrading project portal

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#634]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[X] SharePoint Online

[X] SharePoint 2013

[X] SharePoint 2016

#### Summary

Looks to be related fieldrefs. Seems like in some cases, just referencing the content type is insufficient. Needs to also reference the fields.

#### Version

Please specify what version you are using: [2.3.1]

**Comment by olemp** [comment]
Have you checked the related list? Sometimes it seems like PnP removes all content types from a list which is why we end up with a list with only Title etc. **DO NOT ADD FIELD REFS TO ALL LISTS**.

**Comment by olemp** [comment]
I repeat: **DO NOT ADD FIELD REFS TO ALL LISTS.**

**Comment by olemp** [comment]
I repeat again: **DO NOT ADD FIELD REFS TO ALL LISTS.**

**Comment by marlowandre** [comment]
Just wanted to add that I got this issue as well when installing a new portal (not upgrading). Got the issue with 2.3.1 and 2.3.0. 2.2.10 installed successfully.

**Comment by tarjeieo** [comment]
Yeah, I'm going to push a change that adds field refs to lists at root level (which is where this is failing). Want to do some more testing first.

**Comment by tarjeieo** [comment]
Should be fixed with upcoming release
