### ISSUE TITLE
Filtrering på fase i oppgavelisten for Prosjektrom fungerer ikke. 

### ISSUE THREAD

**Issue by havardd** [Puzzlepart/prosjektportalen#635]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Environment

[ ] SharePoint Online

[X] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[X] Internet Explorer

[X] Edge

[ ] Safari

[ ] Other

#### Summary

Filtrering på fase i oppgavelisten for Prosjektrom fungerer ikke. Selv om mange oppgaver har tag på f.eks Konsept vises ingen oppgaver dersom filteret benyttes.

#### Version

Please specify what version you are using: [2.1.8 og 2.3.1 ]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Kun oppgaver som er tagget med gjeldende fase vises

#### Observed Behavior
Dersom filter på Konsept aktiveres vises ingen oppgaver

#### Steps to Reproduce
Opprett ny oppgave i oppgavelisten for prosjektrommet
Tagg oppgaven med fase, f.eks Konsept
Trykk lagre
![filterkonsept](https://user-images.githubusercontent.com/10496174/50278140-88bfbe00-0446-11e9-84a3-44fdd0b2664a.png)

Aktiver filter "Fase" ved å velge Konsept i listen

**Comment by tarjeieo** [comment]
Hei - takk for rapportering av issue. Dessverre er dette en gjenganger, og er en SharePoint-bug såvidt jeg vet. Se https://github.com/Puzzlepart/prosjektportalen/issues/471.
