### ISSUE TITLE
Filters "locked / empty" after upgrade to 2.3.1

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#636]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X ] Bug

#### Environment

[ X] SharePoint Online

#### Browser

[ X] Chrome

#### Summary

After upgrade to 2.3.1 the filtyering in Phase Checklist is not working properly.

#### Version

Please specify what version you are using: [2.3.1 ]

#### Expected / Desired Behavior / Question
Filters should be working properly.
  
#### Observed Behavior
When you go to Phase checklist from Phases webpart on Project Start Page, the phase checklist is filtered based on the phase you where coming from.
It is not possible to change this filter by cliking on the column header.
By selecting a differnet view on the list and go back to the original view the filtering is working as expected.

#### Steps to Reproduce
From Project Start Page:
- hover over a phase
- select "go to phase checklist"
- when in checklist try to change filtering of either "phase" or "status" column, by selecting the small black arrow by the column name.
- the dropdown shows nothing in our instance (See attached picture)

![image](https://user-images.githubusercontent.com/33092566/50336092-8e340b80-050d-11e9-8374-52e604b4348b.png)

**Comment by tarjeieo** [comment]
Looks like this issue is only relevant for classic view. Change to modern view and filter options are available.

This change was introduced related to #603. Looks like the change that was made works best in modern view, and we get this bug in classic. I think I will make the call that we can live with this bug in classic, and close this as a "wont fix".
