### ISSUE TITLE
Missing URL-parameters of portfolio insight

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#638]
**Is your feature request related to a problem? Please describe.**
When using the portfolio insights, I often select a project selection from the dropdown. However, there is no way to link back to my selection. 

**Describe the solution you'd like**
I need the feature that is used on the portfolio overview, where I can link to viewId=x. I.e. the selected portfolio data source needs to be persisted in the URL.

**Where in the Project Portal is this relevant?**
Portfolio insights

**Comment by olemp** [comment]
Now supporting both `?viewId=` and `#viewId=` exactly like `DynamicPortfolio`.

https://github.com/Puzzlepart/prosjektportalen/commit/ce142bcfbb29c328fc29797212d043ee6fdb0b06
