### ISSUE TITLE
Opacity of resource allocation makes the whole element transparent

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#639]
We need to modify this to only change background-opactity. Something like https://css-tricks.com/rgba-browser-support/ to make RGBA work.

https://pzlcloud.sharepoint.com/sites/ppdemo_v2/SitePages/ResourceAllocation.aspx

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen/commit/7b177c54b08f633536efff15431bb9ba3e96e369
