### ISSUE TITLE
Problem with filters, resource allocation

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#640]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[ X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Version

Please specify what version you are using: [2.3.1]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Summary

Two issues
* Filtering on project doesn't work, page turns white
* Filtering on role doesn't remove "blank" users. Shows a lot of empty rows.

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen/commit/7b177c54b08f633536efff15431bb9ba3e96e369
