### ISSUE TITLE
Add link to resource allocation list at root level

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#641]
**Is your feature request related to a problem? Please describe.**
We have a list at root level that allows cross-project allocations. This list is a bit hidden now. We should add a link from /SitePages/ResourceAllocation.aspx.

**Describe the solution you'd like**
A link from /SitePages/ResourceAllocation.aspx, above the allocation table, to /Lists/ResourceAllocation/AllItems.aspx. The format can be info-message (ui fabric), and the text can read:
* To add allocations or absence not related to a single project, add them to the [central resource allocation list](/Lists/ResourceAllocation/AllItems.aspx). These items will appear with different colors in the table below.
* For å legge til ressursallokering eller fravær som gjelder på tvers av prosjekter, legg de til i den [sentrale ressursallokeringslisten](/Lists/ResourceAllocation/AllItems.aspx). Disse oppføringene vil vises med annen farge i tabellen under.

**Where in the Project Portal is this relevant?**
Resource allocation

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen/commit/7b177c54b08f633536efff15431bb9ba3e96e369
