### ISSUE TITLE
Assuming element id may cause unexpected behavior 

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen#645]
#### Summary
We have som instances of referencing elements by assumption, i.e. assuming an element with an id exists. This code will stop working in the case of a user deleting this list element and not restoring it from the recycle bin. I.e. the only out form this scenario is to create a new project and migrate content to the new web. Note that the only scenario where the id assumption will break is if users tamper with the default setup of a project web

### Details

One instance is when referencing /Lists/Properties, where we assume an element with the id 1 exists. A more robust approach is to get all elements from this list and pick one. 
https://github.com/Puzzlepart/prosjektportalen/blob/17240cfd2b0741bdd1e1e8d74febd95d53e49090/src/js/Project/ProjectProperties.ts#L24

Another instance is when we try to fetch the welcome page for our web, and we assume the welcome page has id=3. 
https://github.com/Puzzlepart/prosjektportalen/blob/05533ba861eceed14594e410ed3c081e61ac9d40/src/js/Project/WelcomePage.ts#L23

A more robust, but more complicated, approach would be to get the welcomepage and find the id. This does however require at least two server requests.

Example
https://pzlcloud.sharepoint.com/sites/ppdemo_v2/adopsjon-o365/_api/web/rootfolder/welcomepage
returns 
SitePages/ProjectHome.aspx

We would then have to do the following request to get the id
https://pzlcloud.sharepoint.com/sites/ppdemo_v2/adopsjon-o365/_api/web/GetFileByServerrelativeUrl('/sites/ppdemo_v2/adopsjon-o365/SitePages/ProjectHome.aspx')/ListItemAllFields/Id

**Comment by olemp** [comment]
_This code will stop working in the case of a user deleting this list element and not restoring it from the recycle bin._

I see your point, but it's hard to handle all these special cases.

We are now changing to a project properties list with a single item, and not welcome page, due to search issues. As you're suggesting a more robust approach is to get all elements from this list and pick one, but I think it's a bit of a edge case handling user deleting the item.

**Comment by olemp** [comment]
We've assumed ID for welcome page since day 1 without any issues, but if the effort for a more robust approach is low, then why not?

**Comment by okms** [comment]
better safe than sorry.

**Comment by olemp** [comment]
This should do it @okms?

https://github.com/Puzzlepart/prosjektportalen/commit/8fc4eaea205ec7ec4e8a4afdcc5a16de8c529538

**Comment by olemp** [comment]
Fix merged to dev.
