### ISSUE TITLE
Properties list missing in new projects

### ISSUE THREAD

**Issue by marlowandre** [Puzzlepart/prosjektportalen#648]
#### Environment

[x] SharePoint Online

#### Version

Please specify what version you are using: [ 2.4.0 ]

#### Summary

Doing some testing with upgrading to 2.4.0. Upgraded from 2.2.6. Existing projects seem to work fine. New projects however are having some issues. What I noticed is that new projects are missing the Properties list. Same issue happened in two different tenants.

![image](https://user-images.githubusercontent.com/29536394/53636072-47564680-3c1f-11e9-8cc4-db5ab29e297f.png)

**Comment by olemp** [comment]
Are you using a custom template @marlowandre?

**Comment by marlowandre** [comment]
Thought I checked this, but I guess not good enough :confused:
One of the two tenants I tested with has a custom template. The one with a standard template has the Properties list. I'll update the custom template. Thanks!
