### ISSUE TITLE
Problem installing prosjektportalen

### ISSUE THREAD

**Issue by bjornbf** [Puzzlepart/prosjektportalen#654]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[x] Other

#### Version

Please specify what version you are using: [ Latest]

#### Summary

We have tried installing prosjektportalen many times and it always stops at

Error installing root-package to https://hioa365.sharepoint.com/sites/Prosjektportalen
Object reference not set to an instance of an object.

Attached pplog says

powershell.exe Error: 0 : 2019-03-14 10:49:42.2245	[OfficeDevPnP.Core]	[0]	[Error]	File ICO-Site-Global-13.png not found in directory /sites/Prosjektportalen/siteassets/pp/img. Exception = Unable to find the specified file.	0ms	

[pplog-20190314_103032.txt](https://github.com/Puzzlepart/prosjektportalen/files/2970428/pplog-20190314_103032.txt)

**Comment by tarjeieo** [comment]
This is a weird one. We're unable to reproduce, but I have a theory that it's validating that the img-file needs to be in place before if can set the SiteLogo address. This is not an issue with the bundled version or the latest version of PnP however, so I don't really understand why it's behaving like this here. 

Can you check which version of PnP PowerShell that is loaded for you by going to PowerShell and typing Get-commmand connect-pnponline? E.g. 
![image](https://user-images.githubusercontent.com/1837390/54435508-f111f900-4730-11e9-9510-7e4c8982bd03.png)

**Comment by bjornbf** [comment]
PS C:\Users\Administrator\Downloads\prosjektportalen-2.4.0.e96c5831\prosjektportalen-2.4.0.e96c5831> Get-Command Connect-PnPOnline

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Connect-PnPOnline                                  3.7.1903.0 SharePointPnPPowerShellOnline

**Comment by tarjeieo** [comment]
Very strange that it's working with the same setup here.

In any case, can you try this release? We've tried to change the order of installation elements in order to provision sitelogo before it's being referenced. https://github.com/Puzzlepart/prosjektportalen/releases/tag/v2.4.1

**Comment by bjornbf** [comment]
[pplog-20190319_141652.txt](https://github.com/Puzzlepart/prosjektportalen/files/2983651/pplog-20190319_141652.txt)
We still have the same problem.

**Comment by tarjeieo** [comment]
Shoot me an email at tarjeieo@puzzlepart.com and we'll figure something out

**Comment by tarjeieo** [comment]
@bjornbf,

I was able to reproduce at another customer, where he had created the site collection using a modern team site. That is currently not supported. Could this be case here as well? See https://github.com/Puzzlepart/prosjektportalen/wiki/Read-before-installing.
