### ISSUE TITLE
Double risk-list section in projectstatus 

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#678]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[X ] SharePoint Online

[ ] SharePoint 2013

[ X] SharePoint 2016

#### Browser

[X ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Version

Please specify what version you are using: [ 2.5.4]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

**Comment by olemp** [comment]
`<RiskMatrix />` renders the list aswell as the matrix, and an additional list was rendered if `listTitle` was specified. Fixed. Creating new patch version.
