### ISSUE TITLE
Parameter DataSourceSiteUrl is not replaced properly

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#680]
#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

All

#### Version

2.5.5

![image](https://user-images.githubusercontent.com/7606007/57858302-14b8f480-77f1-11e9-9651-7f01e37842d6.png)

**Comment by tarjeieo** [comment]
PnP issue: https://github.com/SharePoint/PnP-Sites-Core/issues/2259

**Comment by tarjeieo** [comment]
Fixed with the latest PnP (june). Can you upgrade all bundled versions @olemp ?

**Comment by olemp** [comment]
Bundle updated to 3.10.1906.0.
