### ISSUE TITLE
Problem with sticky header Porteføljeoversikten 

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen#685]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Version

Version: [2.5.10]

#### Summary

If a user has a low enough resolution, and is viewing the "Porteføljeoversikten" page, they will get an outer scrollbar, which is the case for some laptop users. 

When this occurs there will be issues with the sticky header not showing when the user scrolls first the outer scrollbar, and then the actual content. 

As shown in the gif below, we first scroll the outer scrollbar, and then the inner, as well as showing the correct view with sticky header.
![sticky-header](https://user-images.githubusercontent.com/28678468/60015310-73d91700-9683-11e9-9390-03ba889b06c9.gif)

Related issue: #650 

#### Expected / Desired Behavior / Question

The sticky header is expected to be sticky on lower resolutions.

#### Steps to Reproduce

See above...

**Comment by Remi749** [comment]
Solution with CSS:

```css
form[action*='Portfolio.aspx'] {
    #s4-workspace {
        overflow-y: hidden;
    }
}
```

**Comment by olemp** [comment]
This was a tough nut. Ended up with setting height: auto for #s4-workspace and bottom: 25px for the scrollable pane container (to show the horizontal scrollbar). See commits for more details.
