### ISSUE TITLE
ProjectStatus page shows a blank Project under Risk section

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen#694]
### Environment

[X] SharePoint Online

#### Browser

[X] Chrome

#### Version

[2.5.14]

#### Summary

Under the Risk section on the Project Status page there is a blank project in the dropdown menu. It shows All Projects and then a blank one underneath, see image below.

<img width="698" alt="Screenshot_32" src="https://user-images.githubusercontent.com/28678468/64526250-15771880-d303-11e9-9274-e49b6658222a.png">

This is probably a Projectportal bug as it happens on other Projectportal instances as well.

#### Steps to Reproduce

Add a Risk element for the dropdown menu to show

**Comment by olemp** [comment]
This bug was introduced in https://github.com/Puzzlepart/prosjektportalen/issues/616. Reopening that issue, and closing this.
