### ISSUE TITLE
Project site images gone from the frontpage

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#700]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[X ] SharePoint 2016

#### Browser

[X ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Version

Please specify what version you are using: [2.6.1 and 2.5.14 (ASSIST-2542)]

#### Summary

Only the symbol for "old projects" is shown:
![image](https://user-images.githubusercontent.com/1837390/67490538-ae73b000-f673-11e9-894c-1e249ff72bb5.png)

**Comment by tarjeieo** [comment]
Fixed some edge cases where this bug occured, but we need to introduce batching on the frontpage or else this will be an issue when you have more than 500 projects (yes really 😱 ). Something for @Remi749 to give a go @olemp ?

**Comment by olemp** [comment]
Give @Remi749 a go! 🤩

**Comment by tarjeieo** [comment]
Should be resolved with support for more than 500 items #696 #704
