### ISSUE TITLE
On porteføljeoversikt search persists when changing views

### ISSUE THREAD

**Issue by pzlespen** [Puzzlepart/prosjektportalen#703]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Version

Please specify what version you are using: [2.6.1]

#### Summary

On Porteføljeoversikt, search for a project, and then change view. The seachbox is then empty, but it still uses what you entered in the search box in the previous view.

#### Expected / Desired Behavior / Question

When changing view the seach string should not be persisted (or if it does, the search string should be visible in the search box)

**Comment by Remi749** [comment]
Branch: https://github.com/Puzzlepart/prosjektportalen/tree/issues/703

Made the search value persist on view change, but still a little todo.

Todo: Make the search value stay when use clicks the search bar after view change, right now it dissapears.

@olemp: any tips to make the value stay when user clicks the search field?

Check gif for issue:

![searchfieldissue](https://user-images.githubusercontent.com/28678468/72623013-9fd02880-3944-11ea-8cec-8ed2038369d2.gif)

**Comment by olemp** [comment]
Create a draft PR and it's easier for me to see the changes done in the branch.

![image](https://user-images.githubusercontent.com/7606007/72623792-0a359880-3946-11ea-9add-e20d203e94c4.png)
