### ISSUE TITLE
Support selectable content for selected projecttype

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen#707]
Would like to support selectable content for selected project type

## Technical Solution
Add ListContent and Extension menus to the "New project" dialog when a projecttype is selected. This will get the ListContent and Extensions for the projecttype and display them like in the image below which can be ticked off or on before creating the project.

![image](https://user-images.githubusercontent.com/28678468/70430193-86e97300-1a7a-11ea-9b5d-97ad18ac9add.png)

### Additional features
- [ ] Also add an if check whether the projecttype list exists or not
- [ ] Maybe also add a "active" column for the projecttype so that it doesn't need to be deleted to deactivate.

**Comment by Remi749** [comment]
https://github.com/Puzzlepart/prosjektportalen/tree/issues/707

**Comment by Remi749** [comment]
PR: https://github.com/Puzzlepart/prosjektportalen/pull/709

**Comment by olemp** [comment]
Is the additional features in description implemented @Remi749?

**Comment by Remi749** [comment]
I completely forgot about the additional features. I can create a new branch for these if that is OK.

**Comment by olemp** [comment]
First one is the most important. What happens if there’s no project types list?

**Comment by olemp** [comment]
PR merged and this is OK.
