### ISSUE TITLE
Error on installing 2.6.5.40609503

### ISSUE THREAD

**Issue by AudunWangen** [Puzzlepart/prosjektportalen#719]
#### Environment

[X] SharePoint Online

#### Version

Please specify what version you are using: [2.6.5.40609503]

#### Summary

Got this error message when installing fro release 2.6.5.40609503:

At C:\Users\hikt116\Downloads\prosjektportalen-2.6.5.40609503\Install.ps1:190 char:66                                   + ...  $Language = Get-WebLanguage -ctx (Get-PnPContext -Connection $Connec ...                                         +                                                       ~~~~~~~~~~~                                                         + CategoryInfo          : InvalidArgument: (:) [Get-PnPContext], ParameterBindingException                              + FullyQualifiedErrorId : NamedParameterNotFound,SharePointPnP.PowerShell.Commands.Base.GetSPOContext   

Tried 2.6.4.8ccc7ec4, and that one seemed to work.

#### Steps to Reproduce

Clean install on newly created site collection.

**Comment by tarjeieo** [comment]
Hi, yes, we noticed an issue with the script on clean installs. It's already fixed, and we will build a new release very shortly.
