### ISSUE TITLE
View dropdown in portfolio overview disappears too quickly

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#726]
## Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ ] Chrome

[x] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Version

Please specify what version you are using: [2.6.7]

#### Summary

When selecting the view dropdown on the portfolio page in IE, the view disappears too quickly. When you move the cursor over the dropdown it disappears before you can select anything.

![image](https://user-images.githubusercontent.com/1837390/74526525-d721fd00-4f23-11ea-87e0-b0ed9696b58a.png)

#### Expected Behavior

You should be able to select an option in the dropdown.

**Comment by olemp** [comment]
This is related to the `ContextualMenuItem` component in `office-ui-fabric-react`. Not something we can hack-fix I think. Might have been fixed in a newer version of `office-ui-fabric-react`.

**Comment by olemp** [comment]
Not an issue anymore.
