### ISSUE TITLE
Date fields have 1 day offset in the portfolio overview

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#732]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[X ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Version

Please specify what version you are using: [2.6.8]

#### Summary

Date fields have one day offset, probably because of timezone. Can be reproduced in our own ppdemo_v2.

#### Expected / Desired Behavior / Question

Dates should be the same in both portfolio overview and in project properties.

#### Observed Behavior

Date fields are one day off.

#### Steps to Reproduce

Add values to date fields, e.g. start and end date. Observe the offset in the portfolio overview.

**Comment by olemp** [comment]
We can probably fix this using `moment-timezone.`

**Comment by olemp** [comment]
The date fields are probably saved with time 00:00 since they’re date-only. Search will pick it up as UTC time and therefore subtract one hour. The date will then be 1 day earlier. @tarjeieo

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen/commit/d1e6581669057493022537c9bd57272f057bfa24

**Comment by tarjeieo** [comment]
Holy shit, nice job!
