### ISSUE TITLE
Truncate note fields in portfolio overview

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#737]
**Is your feature request related to a problem? Please describe.**
Note fields in the portfolio overview can take quite a bit of space, and make the overview a bit messy. On the other hand, it might be important information that should be shown.

**Describe the solution you'd like**
Ability to truncate text in note fields. Propose the following solution:
- Add a setting to the settings page called "Truncate Portfolio Note Fields Characters" with a default value of 256. If the value is 0, do not truncate.
- In the portfolio overview page,truncate note fields corresponding to the number of chars in the setting. Add "..." at the end. The tooltip when hovering over the value should show the full note field text (similar to status fields).

**Where in the Project Portal is this relevant?**
Portfolio overview

**Comment by tarjeieo** [comment]
Inspo: https://justmarkup.com/articles/2017-01-12-truncating-and-revealing-text-the-show-more-and-read-more-patterns/

**Comment by Petterandre** [comment]
PR: https://github.com/Puzzlepart/prosjektportalen/pull/738
