### ISSUE TITLE
Support breaking inheritance of lists and libaries in the template

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#74]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X ] Enhancement

[ ] Bug

[ ] Question

#### Summary

Want the possibilility to break inheritance of lists and libraries, and give associated visitors, members or owners unique permissions on the objects. Is this supported by pnp-js yet?

**Comment by olemp** [comment]
Added initial support https://github.com/Puzzlepart/pnp-js-provisioning/commit/f636ef66dcdab252eff9c112b9b06595221229a3

We need to support tokens (or similiar) for associated visitors, members or owners groups.

**Comment by tarjeieo** [comment]
Let's support a format similar to PnP schema..

```
<pnp:Security>
            <pnp:BreakRoleInheritance CopyRoleAssignments="false" ClearSubscopes="true">
                <pnp:RoleAssignment Principal="{associatedmembergroup}" RoleDefinition="Contribute"/>
                <pnp:RoleAssignment Principal="{associatedownergroup}" RoleDefinition="Full Control"/>
            </pnp:BreakRoleInheritance>
        </pnp:Security>
```

**Comment by olemp** [comment]
@tarjeieo Groups needs to be created before we can do this, so I suggest the groups are created during the provisioning instead of using `permsetup.aspx`. `office-ui-fabric-react` have a People Picker component we can use.

**Comment by olemp** [comment]
Status @tarjeieo?

**Comment by olemp** [comment]
If we're solving this, I really think we should create the groups beforehand, to avoid making this very hacky, or totally turning around on the provisioning mechanism.

Example:

![74-01](https://user-images.githubusercontent.com/7606007/27626416-4822e05a-5be8-11e7-84d0-b1928d5b82d7.PNG)


cc @tarjeieo

**Comment by tarjeieo** [comment]
The problem with this approach is that we should/would also need to support the other features of the group creation process, e.g. "use existing group" and add people to the groups.

**Comment by olemp** [comment]
True, that comes at a technical price.

**Comment by tarjeieo** [comment]
This is a quite complex issue not easily solved, and not very often requested. The estimate is at least 5 days, considering we need to do modifications to PP core, sp-pnp-js-provisioning as well as the UX. This will also need to be implemented as an optional setting (via pp settings page). Will close this until someone is willing to finance this functionality.
