### ISSUE TITLE
Forward slash in project name hinders Project Status snapshot saving

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen#743]
#### Environment

[X] SharePoint Online
#### Browser

[X] Chrome

#### Version

[any version]

#### Summary

Forward slash in project name hinders Project Status snapshot saving.
Probable solution: Remove forwarslashes in filename if a Project has forwardslashes in its name.

Extra info: A customer has over 20+ projects with forward slashes.

#### Observed Behavior

When pressing the snapshot button in the Projecstatus page, in a project that has one or more forward slashes, it won't save.

#### Steps to Reproduce

Have Project with forward slash in name, go to Projectstatus and make a snapshot.

**Comment by Remi749** [comment]
@olemp, how is the snapshot handled in PP365? If it's the same or similar, then the problem might persist there as well.

**Comment by olemp** [comment]
> @olemp, how is the snapshot handled in PP365? If it's the same or similar, then the problem might persist there as well.

In https://github.com/Puzzlepart/prosjektportalen365 we have a list item for each "snapshot". You don't update the project properties, you create a new status report item.

**Comment by Remi749** [comment]
Are project properties updated in PP2 when creating a snaphot? If I'm not mistaken, aren't PP2 also handled the same as PP365 (adding a item to a list/library) and therefore the problem would also apply to PP365?

**Comment by Remi749** [comment]
Bug only applies to PP2.

**Comment by Petterandre** [comment]
Closed as PR is merged.
