### ISSUE TITLE
Show risk matrix before/after tiltak/actions is not working in IE

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#75]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

Nothing happens when button is clicked. No error message or console log either.

**Comment by olemp** [comment]
Something weird with the `Toggle` component on this page. Changed to vanilla input+label.
