### ISSUE TITLE
English version?

### ISSUE THREAD

**Issue by THVitec** [Puzzlepart/prosjektportalen#758]
#### Category

[ ] Enhancement

[ ] Bug

[X] Question

#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[X] Chrome

[X] Internet Explorer

[X] Edge

[X] Safari

[X] Other

#### Summary

Please summarize the issue.

#### Expected / Desired Behavior / Question

Hi!
Is there a current english version of PP available? Any possibilities of seeing an english version in the near future? 
Ofcourse one could always translate the src but then you won't be able to apply future updates I reckon?
Thanks in advance!

**Comment by Remi749** [comment]
Hi THVitec,

as stated in the wiki: "...the Project Portal can be installed in english and is built to support other languages as well."

This version of the projectportal is availbale in english.

Projectportal365 on the other hand is not avaiable as mentioned in your other issue: https://github.com/Puzzlepart/prosjektportalen365/issues/291
