### ISSUE TITLE
Bug: Gevinsoversikt crashes if two gevinstmålinger has been added to the same date

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#76]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

**Comment by olemp** [comment]
Do you have more details @tarjeieo? Can't reproduce.

**Comment by olemp** [comment]
Was able to reproduce now!

**Comment by olemp** [comment]
I was able to reproduce that the component doesn't load, but it doesn't seem like it's related to two measurements on the same date.

**Comment by olemp** [comment]
So what to we do here @tarjeieo?

**Comment by olemp** [comment]
20-30 reloads and everything loads OK
