### ISSUE TITLE
Portfolio Overview does not work with fullscreen view.

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen#762]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs, please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[ x ] SharePoint 2016

#### Browser

[ x ] Chrome

[ x ] Internet Explorer

[ x ] Edge

[ ] Safari

[ ] Other

#### Summary

Please summarize the issue.

#### Expected / Desired Behavior / Question

Activating fullscreen in any overview should stretch the view. 
![image](https://user-images.githubusercontent.com/10527497/90126517-1b237c80-dd64-11ea-88b8-c323e5be5b1f.png)

Example from DeliveriesOverview.aspx

#### Observed Behavior
The Project.aspx site (Portfolio Overview) does not stretch the portfolio view, it maintains a margin to the right.

![image](https://user-images.githubusercontent.com/10527497/90126458-01823500-dd64-11ea-9d9b-50399671ee8c.png)

#### Steps to Reproduce

In any portfolio overview, hit the Full screen button.

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen/pull/763
