### ISSUE TITLE
SPWebUrl shows URL from wrong zone in some cases

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#766]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs, please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[ ] SharePoint Online

[ ] SharePoint 2013

[X] SharePoint 2016

#### Browser

[ ] Chrome

[ ] Internet Explorer

[X] Edge

[ ] Safari

[ ] Other

#### Version

Please specify what version you are using: [2.6.10]

#### Summary

In the project info popup, the URL used is from SPWebUrl managed property. For some reson this yields the wrong URL (from wrong zone). Look into this more into detail.

Ref mail 11.09.2020.

**Comment by tarjeieo** [comment]
Solved by stopping usage of SpWebUrl (because it's wonky onprem), moving to path.split(Lists)[0] which looks uglier, but works better

**Comment by olemp** [comment]
> Solved by stopping usage of SpWebUrl (because it's wonky onprem), moving to path.split(Lists)[0] which looks uglier, but works better

Fix seems ok, we need to live with a workaround like this in such cases
