### ISSUE TITLE
Bug: Prosjektleveranser får ikke alle felter

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#78]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

Dette skjer her: https://pzlcloud.sharepoint.com/sites/ppdemo_v2/anskaffelse-av-ny-printerloesning/Lists/Prosjektleveranser/AllItems.aspx

Kan være en miljøissue? Har ikke testa andre steder i det siste.

**Comment by tarjeieo** [comment]
Det samme skjer for usikkerhetslista! :(

**Comment by olemp** [comment]
Er nok ShowInNewForm="FALSE"

**Comment by olemp** [comment]
Vi har tidligere hatt ShowInNewForm="FALSE" for disse feltene på denne siten, men det er nå endret. Ved en fresh install vil dette løse seg.

**Comment by olemp** [comment]
Dette skal nå være løst for demositen ved å hacke opp en SiteFields.xml.
