### ISSUE TITLE
Deleted projects still appear in the Project Portfolio-view 

### ISSUE THREAD

**Issue by torbjoernm** [Puzzlepart/prosjektportalen#780]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs, please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ ] Bug

[X ] Question

#### Environment

[ X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ X] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

Hi guys. When deleting a project, it still appears in the portfolio. The link to the project is gone as the site/group is deleted, but the record in portfolio still appears. Tried to do a new crawl, but this didn't help. Since the group was deleted, it has disappeared from all other views. 

Is this caused by deleting the project group directly? Should I've done some preliminary steps before deleting a project?
Waited the mandatory 72h to be sure.

#### Version

Please specify what version you are using: [1.2.4 ]

You can find the version you are using in the bottom left corner of any page in the Project Portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Deleted a project - It disappeared from the project-list, but not from the portfolio

#### Steps to Reproduce
Create a project. Delete that project and observe that it is deleted. Check that it still appears in portfolio even though its deleted.

**Comment by olemp** [comment]
Hi @torbjoernm! 

Thanks for reporting!

You probably meant to report this in [Prosjektportalen 365](https://github.com/Puzzlepart/prosjektportalen365)? If not, feel free to comment.

[We have an active issue](https://github.com/Puzzlepart/prosjektportalen365/issues/363) on this in [Prosjektportalen 365](https://github.com/Puzzlepart/prosjektportalen365).

As you can see in this issue the temp fix is:

> Temp fix is to delete the project from the Lists/Prosjekter list

🚀

**Comment by torbjoernm** [comment]
Whoops! Turns out I both searched for the issue and filed it in the wrong project. Sorry about that ;)  Appreciate the quick response and the active issue you're referring to is on line with what we're experiencing. Thanks @olemp!
