### ISSUE TITLE
Issue with building Prosjektportalen - sp-js-provisioning

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#782]
#### Summary

There seems to be an issue with finding/using the correct version of `sp-js-provisioning`. This issue is the same for prosjektportalen-program. The one that is present in package.json now fails with message
```
npm ERR! Command failed: git checkout v0.8.9
npm ERR! error: pathspec 'v0.8.9' did not match any file(s) known to git
```

Tried various other variations of the import
`        "sp-js-provisioning": "git+https://github.com/Puzzlepart/sp-js-provisioning.git",`
and 
`        "sp-js-provisioning": "1.1.0",`

I managed to install packages with these two variations, but failed to build the project. Also experimented with different versions of node, but no luck.

Care to shed some light on what should be the correct setup for this @olemp ?

**Comment by olemp** [comment]
@tarjeieo Nothing has been changed for that repo as far I know.

**Comment by okms** [comment]
All tags had been pruned from https://github.com/Puzzlepart/sp-js-provisioning. I re-created v0.8.9 from commit 33d381d1b7bf112b69456c68607d47a83cc17de2. We could use head or a newer revision in the future. This should resolve the issue for everyone @tarjeieo. It builds using node 8 and 10 for me.

**Comment by tarjeieo** [comment]
Still fails at building with the following error
```
ERROR in [at-loader] ./node_modules/sp-js-provisioning/lib/schema.d.ts:1:10
    TS2305: Module '"../../@pnp/sp"' has no exported member 'CanvasColumnFactorType'.
```

**Comment by olemp** [comment]
> All tags had been pruned from https://github.com/Puzzlepart/sp-js-provisioning. I re-created v0.8.9 from commit 33d381d1b7bf112b69456c68607d47a83cc17de2. We could use head or a newer revision in the future. This should resolve the issue for everyone @tarjeieo. It builds using node 8 and 10 for me.

All tags pruned? How?

**Comment by okms** [comment]
> > All tags had been pruned from https://github.com/Puzzlepart/sp-js-provisioning. I re-created v0.8.9 from commit 33d381d1b7bf112b69456c68607d47a83cc17de2. We could use head or a newer revision in the future. This should resolve the issue for everyone @tarjeieo. It builds using node 8 and 10 for me.
> 
> All tags pruned? How?

I do not know, however this is all the tags i can see 

![image](https://user-images.githubusercontent.com/170147/129681965-ee63d5af-50f5-41f3-b8d5-9f130aac56a8.png)

**Comment by olemp** [comment]
> > > All tags had been pruned from https://github.com/Puzzlepart/sp-js-provisioning. I re-created v0.8.9 from commit 33d381d1b7bf112b69456c68607d47a83cc17de2. We could use head or a newer revision in the future. This should resolve the issue for everyone @tarjeieo. It builds using node 8 and 10 for me.
> > 
> > 
> > All tags pruned? How?
> 
> I do not know, however this is all the tags i can see
> 
> ![image](https://user-images.githubusercontent.com/170147/129681965-ee63d5af-50f5-41f3-b8d5-9f130aac56a8.png)

I have several tags locally.

Could try to repush them.

![image](https://user-images.githubusercontent.com/7606007/129682156-ca11d882-74f0-4257-8515-44203164697a.png)

Did you create `v0.8.9` from the latest commit?

**Comment by olemp** [comment]
> Still fails at building with the following error
> 
> ```
> ERROR in [at-loader] ./node_modules/sp-js-provisioning/lib/schema.d.ts:1:10
>     TS2305: Module '"../../@pnp/sp"' has no exported member 'CanvasColumnFactorType'.
> ```

I recreated the original `v0.8.9` tag. Could you try again?

**Comment by tarjeieo** [comment]
> > Still fails at building with the following error
> > ```
> > ERROR in [at-loader] ./node_modules/sp-js-provisioning/lib/schema.d.ts:1:10
> >     TS2305: Module '"../../@pnp/sp"' has no exported member 'CanvasColumnFactorType'.
> > ```
> 
> I recreated the original `v0.8.9` tag. Could you try again?

Works! 🎸  Thanks Ole&Ole
