### ISSUE TITLE
Use a provisioned css file for the fabric css components on the frontpage. Is this needed?

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#81]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X ] Enhancement

[ ] Bug

[ ] Question

In the Home.aspx page, we should change from this
`    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/4.1.0/css/fabric.min.css">`

to reference a locally deployed file - or is the bundled css enough?

**Comment by olemp** [comment]
That reference can be deleted I guess. We're including the fabric CSS in our main bundle.

**Comment by olemp** [comment]
Fabric is included in our css bundle.

**Comment by tarjeieo** [comment]
Yes, but manually copied to our repo - ideally I would like to include it directly from the source to make it easier to upgrade etc.

**Comment by olemp** [comment]
I've tried, but failed to find the correct CSS file that does the same job as the Fabric.styl. I don't understand why.

**Comment by tarjeieo** [comment]
I might have a look at it for the next minor release

**Comment by olemp** [comment]
Did you look into this @tarjeieo?

**Comment by tarjeieo** [comment]
Looked into this, but couldn't find a package that includes the compiled css files. Added readme on how to update from the releases @ office ui fabric. Good enough.
