### ISSUE TITLE
Vis pokal for over 100% gevinstoppnåelse i gevinstoversikten

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#86]
Vis en liten pokal ved siden av tallet i gevinstoversiktent, bruk pokalen fra office-ui-fabric.

**Comment by olemp** [comment]
Kanskje nok å vise kun pokal? Ikke trend ikon + pokal?

@tarjeieo

**Comment by tarjeieo** [comment]
Jeg synes det er bedre å vise begge.... kan jo ha trender selv for verdier over 100%

**Comment by olemp** [comment]
Du har nok rett J
