### ISSUE TITLE
Show documents on the frontpage without folders (flat view)

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#9]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[X] Enhancement

[ ] Bug

[ ] Question

**Comment by olemp** [comment]
@tarjeieo I've tried to add Scope = 0 for the view in the template, but it doesn't seem to work.

``json
{
                List: "Dokumenter",
                View: {
                    Title: "",
                    ViewFields: ["DocIcon", "LinkFilename", "Modified", "Editor"],
                    AdditionalSettings: {
                        RowLimit: 10,
                        Paged: true,
                        ViewQuery: "<OrderBy><FieldRef Name='Created' Ascending='FALSE' /></OrderBy>",
                        Scope: 0,
                    },
                },
            }
``
