### ISSUE TITLE
Find a workaround to be able to show fields of type People and Managed Metadata in the Office UI Fabric Detail list

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#91]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ X] Enhancement

[ ] Bug

[ ] Question

#### Summary

Currently, when using REST against lists, the people and man. metadata fields does not give correct data which can be rendered. This would be useful in e.g. gevinstoversikt (show responsible) and risk list (show phase and responsible). Can we find a workaround for this?

**Comment by olemp** [comment]
JSOM

**Comment by tarjeieo** [comment]
Perhaps using CAML will also give us the correct values? pnp-js does allow CAML queries.

**Comment by olemp** [comment]
Worth a try!

**Comment by olemp** [comment]
Using JSOM which gives full HTML
