### ISSUE TITLE
Issues with minified bundle

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen#92]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Environment
[ ] SharePoint Online
[x] SharePoint 2013

#### Summary

Please summarize the issue.

**Comment by olemp** [comment]
Reported by @tarjeieo

**Comment by tarjeieo** [comment]
What's this? Remind me please? :D

**Comment by olemp** [comment]
You had some issues at a customer environment @tarjeieo?

**Comment by olemp** [comment]
Should be solved with `v0.9.37`.

**Comment by olemp** [comment]
Please add more details @tarjeieo

**Comment by tarjeieo** [comment]
Cannot reproduce anymore. Tested 2016 onprem in IE and chrome. GJ OMP
