### ISSUE TITLE
Unable to create projects with latest #dev

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#93]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment
[ X] SharePoint Online
[ ] SharePoint 2013

#### Summary

Unable to create projects now with the latest #dev branch. Also tried npm install and a fresh install.

I get the error message
```
/sites/pp-pnp14/siteassets/pp/js/pp.main.js?version=0.9.34:131042 Uncaught (in promise) ReferenceError: Buffer is not defined
    at Object.module.exports [as json2xml] (/sites/pp-pnp14/siteassets/pp/js/pp.main.js?version=0.9.34:131042)
    at /sites/pp-pnp14/siteassets/pp/js/pp.main.js?version=0.9.34:126573
    at Promise (<anonymous>)
    at Lists.processField (/sites/pp-pnp14/siteassets/pp/js/pp.main.js?version=0.9.34:126567)
    at /sites/pp-pnp14/siteassets/pp/js/pp.main.js?version=0.9.34:126546
    at <anonymous>
```

It happens around the time the Gevinstoppfølging gets added content types, if that's related at all.

#### Version

Please specify what version ou are using: [v0.9.34]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by olemp** [comment]
Try v.0.9.36. The excel export has introduced some new webpack config which might have caused it.

**Comment by olemp** [comment]
Excel export is causing a lot of issues. Removed for now.

**Comment by olemp** [comment]
Should work with `v0.9.37`.

https://github.com/Puzzlepart/prosjektportalen/releases/tag/v0.9.37
