### ISSUE TITLE
Project metadata modal dialog is not fixed width in IE - width overflows out of screen

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#94]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment
[ ] SharePoint Online
[ ] SharePoint 2013
[ X] SharePoint 2016

#### Summary
From the portfolio page (but probably also from frontpage) when looking at project metadata of a project with a long status or goal.

**Comment by olemp** [comment]
Should be solved by setting max-width 50%
