### ISSUE TITLE
Åpning av modaldialog for usikkerhetselementer skroller prosjektstatus-siden opp til toppen

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#95]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

**Comment by olemp** [comment]
Suggest using office-ui-fabric Modal or Dialog instead.

**Comment by olemp** [comment]
The drawback of using Modal or Dialog is that we need to render all the fields ourselves. I would prefer using the DispForm.

**Comment by olemp** [comment]
Can't reproduce in IE or Chrome. If this is on-prem specific we should create a new bug with more environment details.

**Comment by olemp** [comment]
https://akifkamalsyed.wordpress.com/2011/05/02/fix-the-position-of-sharepoint-2010-modaldialog/
