### ISSUE TITLE
Create a project status custom form that you can open from the project status page

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen#97]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ X] Enhancement

[ ] Bug

[ ] Question

Would be nice to have an easy way to update just the status and status comment fields from the project status page. With an arrow icon from the first section. Not critical for 2.0.0 though.

**Comment by olemp** [comment]
A better solution would to separate the project status from the project metadata.

**Comment by olemp** [comment]
A better solution would to separate the project status from the project metadata. Then we can just the vanilla SharePoint forms out of the box.

**Comment by olemp** [comment]
For me this is too much to put on one page. Where would the button be placed?

**Comment by olemp** [comment]
@tarjeieo

**Comment by olemp** [comment]
For me this is too much to put on one page. Where would the button be placed @tarjeieo?

**Comment by tarjeieo** [comment]
Let's put this on the backlog for 3.0 - I think some major regrouping is in order by that point (e.g. separating project fields into multiple sections/lists)

**Comment by tarjeieo** [comment]
Closing this until a major rewrite is in order. Not often requested either.
